# Generated by Django 5.0.1 on 2025-12-23 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CostDriver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "driver_name",
                    models.CharField(max_length=100, verbose_name="동인명"),
                ),
                (
                    "impact_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="영향도 (%)",
                    ),
                ),
                (
                    "change_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="변동률 (%)",
                    ),
                ),
                (
                    "trend",
                    models.CharField(
                        choices=[("up", "증가"), ("stable", "안정"), ("down", "감소")],
                        default="stable",
                        max_length=10,
                        verbose_name="추세",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "원가 동인",
                "verbose_name_plural": "원가 동인",
                "db_table": "cost_driver",
                "ordering": ["-fiscal_year", "-fiscal_month", "-impact_rate"],
            },
        ),
        migrations.CreateModel(
            name="CostReductionProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="프로젝트 ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="프로젝트명")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("material", "재료비"),
                            ("labor", "노무비"),
                            ("overhead", "경비"),
                        ],
                        max_length=20,
                        verbose_name="분류",
                    ),
                ),
                (
                    "target_saving",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="목표 절감액 (억원)",
                    ),
                ),
                (
                    "actual_saving",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="실제 절감액 (억원)",
                    ),
                ),
                (
                    "progress",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="진척도 (%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "계획"),
                            ("in-progress", "진행중"),
                            ("completed", "완료"),
                            ("delayed", "지연"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "responsible_person",
                    models.CharField(max_length=100, verbose_name="담당자"),
                ),
                ("due_date", models.DateField(verbose_name="마감일")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "원가 절감 프로젝트",
                "verbose_name_plural": "원가 절감 프로젝트",
                "db_table": "cost_reduction_project",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CostStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("direct_material", "직접재료비"),
                            ("direct_labor", "직접노무비"),
                            ("manufacturing_overhead", "제조경비"),
                            ("selling_admin", "판매관리비"),
                            ("profit", "이익"),
                        ],
                        max_length=30,
                        verbose_name="원가 유형",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="금액 (억원)",
                    ),
                ),
                (
                    "ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="비율 (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "원가 구조",
                "verbose_name_plural": "원가 구조",
                "db_table": "cost_structure",
                "ordering": ["-fiscal_year", "-fiscal_month"],
            },
        ),
        migrations.CreateModel(
            name="ProductCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "product_code",
                    models.CharField(max_length=50, verbose_name="제품코드"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="제품명"),
                ),
                (
                    "production_volume",
                    models.IntegerField(default=0, verbose_name="생산량"),
                ),
                (
                    "material_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="재료비 (원)",
                    ),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="노무비 (원)",
                    ),
                ),
                (
                    "overhead_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="경비 (원)",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="총원가 (원)",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="판매가 (원)",
                    ),
                ),
                (
                    "margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="이익 (원)",
                    ),
                ),
                (
                    "margin_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="이익률 (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "제품별 원가",
                "verbose_name_plural": "제품별 원가",
                "db_table": "cost_product",
                "ordering": ["-fiscal_year", "-fiscal_month", "-total_cost"],
            },
        ),
        migrations.CreateModel(
            name="BreakEvenAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "fixed_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="고정비 (억원)",
                    ),
                ),
                (
                    "variable_cost_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="변동비율 (%)",
                    ),
                ),
                (
                    "break_even_point",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="손익분기점 (억원)",
                    ),
                ),
                (
                    "actual_sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="실제 매출 (억원)",
                    ),
                ),
                (
                    "margin_of_safety",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="안전마진율 (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "손익분기점 분석",
                "verbose_name_plural": "손익분기점 분석",
                "db_table": "cost_break_even",
                "ordering": ["-fiscal_year", "-fiscal_month"],
                "unique_together": {("fiscal_year", "fiscal_month")},
            },
        ),
        migrations.CreateModel(
            name="MonthlyCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="총원가 (억원)",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="단위당 원가 (원)",
                    ),
                ),
                (
                    "material_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="직접재료비",
                    ),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="직접노무비",
                    ),
                ),
                (
                    "overhead_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="제조경비",
                    ),
                ),
                (
                    "selling_admin_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="판매관리비",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "월별 원가",
                "verbose_name_plural": "월별 원가",
                "db_table": "cost_monthly",
                "ordering": ["-fiscal_year", "-fiscal_month"],
                "unique_together": {("fiscal_year", "fiscal_month")},
            },
        ),
    ]
