# Generated by Django 5.0 on 2026-03-03 07:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_sync", "0003_add_null_to_fom_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ERPSource",
            fields=[
                ("erp_source_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "source_code",
                    models.CharField(
                        help_text="YH, FOM, SAP 등 시스템 식별 코드",
                        max_length=20,
                        unique=True,
                        verbose_name="소스 코드",
                    ),
                ),
                (
                    "source_name",
                    models.CharField(max_length=100, verbose_name="소스명"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("postgresql", "PostgreSQL"),
                            ("mssql", "SQL Server"),
                            ("mysql", "MySQL"),
                            ("oracle", "Oracle"),
                            ("api", "REST API"),
                            ("sqlite", "SQLite"),
                        ],
                        max_length=20,
                        verbose_name="소스 타입",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "host",
                    models.CharField(blank=True, max_length=255, verbose_name="호스트"),
                ),
                (
                    "port",
                    models.IntegerField(blank=True, null=True, verbose_name="포트"),
                ),
                (
                    "database_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="데이터베이스"
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(blank=True, max_length=100, verbose_name="스키마"),
                ),
                (
                    "api_base_url",
                    models.URLField(blank=True, verbose_name="API Base URL"),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="API Key"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본 소스"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "ERP 소스",
                "verbose_name_plural": "ERP 소스",
                "db_table": "erp_source",
                "ordering": ["-is_default", "source_code"],
            },
        ),
        migrations.CreateModel(
            name="ERPTargetModel",
            fields=[
                (
                    "target_model_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="예: MonthlySales, WorkOrder 등",
                        max_length=100,
                        unique=True,
                        verbose_name="Django 모델명",
                    ),
                ),
                (
                    "model_label",
                    models.CharField(max_length=100, verbose_name="모델 라벨"),
                ),
                (
                    "app_label",
                    models.CharField(
                        help_text="sales, production, quality 등",
                        max_length=50,
                        verbose_name="앱 라벨",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("fact", "팩트 테이블"),
                            ("dimension", "차원 테이블"),
                            ("snapshot", "스냅샷 테이블"),
                            ("aggregate", "집계 테이블"),
                        ],
                        default="fact",
                        max_length=20,
                        verbose_name="모델 타입",
                    ),
                ),
                (
                    "db_table_name",
                    models.CharField(max_length=100, verbose_name="DB 테이블명"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "MIS 타겟 모델",
                "verbose_name_plural": "MIS 타겟 모델",
                "db_table": "erp_target_model",
                "ordering": ["app_label", "model_name"],
            },
        ),
        migrations.CreateModel(
            name="ERPTableDefinition",
            fields=[
                ("table_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "source_table_name",
                    models.CharField(max_length=100, verbose_name="소스 테이블명"),
                ),
                (
                    "source_table_comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="테이블 설명"
                    ),
                ),
                (
                    "module_code",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="모듈 코드"
                    ),
                ),
                (
                    "module_name",
                    models.CharField(blank=True, max_length=100, verbose_name="모듈명"),
                ),
                (
                    "record_count",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="레코드 수"
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 동기화"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "erp_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_definitions",
                        to="erp_sync.erpsource",
                        verbose_name="ERP 소스",
                    ),
                ),
            ],
            options={
                "verbose_name": "ERP 테이블 정의",
                "verbose_name_plural": "ERP 테이블 정의",
                "db_table": "erp_table_definition",
                "ordering": ["module_code", "source_table_name"],
                "unique_together": {("erp_source", "source_table_name")},
            },
        ),
        migrations.CreateModel(
            name="ERPFieldDefinition",
            fields=[
                ("field_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "source_field_name",
                    models.CharField(max_length=100, verbose_name="소스 필드명"),
                ),
                (
                    "source_field_type",
                    models.CharField(max_length=50, verbose_name="소스 필드 타입"),
                ),
                (
                    "source_field_comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="필드 설명"
                    ),
                ),
                (
                    "is_primary_key",
                    models.BooleanField(default=False, verbose_name="기본키 여부"),
                ),
                (
                    "is_nullable",
                    models.BooleanField(default=True, verbose_name="NULL 허용"),
                ),
                (
                    "is_foreign_key",
                    models.BooleanField(default=False, verbose_name="외래키 여부"),
                ),
                (
                    "referenced_table",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="참조 테이블"
                    ),
                ),
                (
                    "referenced_field",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="참조 필드"
                    ),
                ),
                (
                    "field_position",
                    models.IntegerField(default=0, verbose_name="필드 순서"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "table_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_definitions",
                        to="erp_sync.erptabledefinition",
                        verbose_name="테이블 정의",
                    ),
                ),
            ],
            options={
                "verbose_name": "ERP 필드 정의",
                "verbose_name_plural": "ERP 필드 정의",
                "db_table": "erp_field_definition",
                "ordering": ["table_definition", "field_position"],
                "unique_together": {("table_definition", "source_field_name")},
            },
        ),
        migrations.CreateModel(
            name="ERPTableMapping",
            fields=[
                ("mapping_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "mapping_code",
                    models.CharField(
                        help_text="예: SDY100_YH_TO_MONTHLY_SALES",
                        max_length=50,
                        unique=True,
                        verbose_name="매핑 코드",
                    ),
                ),
                (
                    "mapping_name",
                    models.CharField(max_length=200, verbose_name="매핑명"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "sync_priority",
                    models.IntegerField(
                        choices=[
                            (1, "필수 (실시간)"),
                            (2, "중요 (시간별)"),
                            (3, "일반 (일별)"),
                            (4, "확장 (주별/월별)"),
                        ],
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="동기화 우선순위",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("full", "전체 동기화"),
                            ("incremental", "증분 동기화"),
                            ("cdc", "변경 데이터 캡처"),
                        ],
                        default="incremental",
                        max_length=20,
                        verbose_name="동기화 타입",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "date_column",
                    models.CharField(
                        blank=True,
                        help_text="증분 동기화 기준 컬럼",
                        max_length=100,
                        verbose_name="날짜 컬럼",
                    ),
                ),
                (
                    "custom_query",
                    models.TextField(
                        blank=True,
                        help_text="복잡한 조인이 필요한 경우 사용",
                        verbose_name="사용자 정의 쿼리",
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 동기화"
                    ),
                ),
                (
                    "last_sync_status",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="마지막 상태"
                    ),
                ),
                (
                    "total_sync_count",
                    models.IntegerField(default=0, verbose_name="총 동기화 수"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "created_by",
                    models.CharField(blank=True, max_length=100, verbose_name="생성자"),
                ),
                (
                    "source_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_mappings",
                        to="erp_sync.erptabledefinition",
                        verbose_name="소스 테이블",
                    ),
                ),
                (
                    "target_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_mappings",
                        to="erp_sync.erptargetmodel",
                        verbose_name="타겟 모델",
                    ),
                ),
            ],
            options={
                "verbose_name": "ERP 테이블 매핑",
                "verbose_name_plural": "ERP 테이블 매핑",
                "db_table": "erp_table_mapping",
                "ordering": ["sync_priority", "mapping_code"],
            },
        ),
        migrations.CreateModel(
            name="ERPMappingValidation",
            fields=[
                ("validation_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "validation_type",
                    models.CharField(
                        choices=[
                            ("structure", "구조 검증"),
                            ("data", "데이터 검증"),
                            ("connection", "연결 검증"),
                        ],
                        max_length=50,
                        verbose_name="검증 타입",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "통과"),
                            ("failed", "실패"),
                            ("warning", "경고"),
                        ],
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "validation_details",
                    models.JSONField(default=dict, verbose_name="검증 상세"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="오류 메시지"),
                ),
                (
                    "validated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="검증일시"),
                ),
                (
                    "table_mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validations",
                        to="erp_sync.erptablemapping",
                        verbose_name="테이블 매핑",
                    ),
                ),
            ],
            options={
                "verbose_name": "매핑 검증",
                "verbose_name_plural": "매핑 검증",
                "db_table": "erp_mapping_validation",
                "ordering": ["-validated_at"],
            },
        ),
        migrations.CreateModel(
            name="ERPTargetField",
            fields=[
                (
                    "target_field_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("field_name", models.CharField(max_length=100, verbose_name="필드명")),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("CharField", "문자열"),
                            ("IntegerField", "정수"),
                            ("DecimalField", "소수"),
                            ("DateField", "날짜"),
                            ("DateTimeField", "날짜시간"),
                            ("BooleanField", "불리언"),
                            ("TextField", "긴 텍스트"),
                            ("JSONField", "JSON"),
                            ("ForeignKey", "외래키"),
                            ("FloatField", "실수"),
                        ],
                        max_length=50,
                        verbose_name="필드 타입",
                    ),
                ),
                (
                    "field_label",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="필드 라벨"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="필수 여부"),
                ),
                (
                    "is_unique",
                    models.BooleanField(default=False, verbose_name="유니크 여부"),
                ),
                (
                    "max_length",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="최대 길이"
                    ),
                ),
                (
                    "decimal_places",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="소수점 자리"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "target_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_fields",
                        to="erp_sync.erptargetmodel",
                        verbose_name="타겟 모델",
                    ),
                ),
            ],
            options={
                "verbose_name": "MIS 타겟 필드",
                "verbose_name_plural": "MIS 타겟 필드",
                "db_table": "erp_target_field",
                "ordering": ["target_model", "field_name"],
                "unique_together": {("target_model", "field_name")},
            },
        ),
        migrations.CreateModel(
            name="ERPFieldMapping",
            fields=[
                (
                    "field_mapping_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "is_key_field",
                    models.BooleanField(default=False, verbose_name="키 필드 여부"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="필수 매핑 여부"),
                ),
                (
                    "transform_rule",
                    models.CharField(
                        choices=[
                            ("none", "변환 없음"),
                            ("upper", "대문자 변환"),
                            ("lower", "소문자 변환"),
                            ("trim", "공백 제거"),
                            ("date_format", "날짜 형식 변환"),
                            ("decimal_cast", "소수형 변환"),
                            ("concat", "문자열 결합"),
                            ("lookup", "룩업 테이블 참조"),
                            ("custom", "사용자 정의 함수"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="변환 규칙",
                    ),
                ),
                (
                    "transform_expression",
                    models.TextField(
                        blank=True,
                        help_text="JSON format for complex rules",
                        verbose_name="변환 표현식",
                    ),
                ),
                (
                    "default_value",
                    models.CharField(blank=True, max_length=255, verbose_name="기본값"),
                ),
                (
                    "validation_rule",
                    models.TextField(blank=True, verbose_name="검증 규칙"),
                ),
                (
                    "error_handling",
                    models.CharField(
                        choices=[
                            ("skip", "건너뛰기"),
                            ("log", "로그만 남김"),
                            ("abort", "중단"),
                        ],
                        default="skip",
                        max_length=50,
                        verbose_name="오류 처리",
                    ),
                ),
                (
                    "field_order",
                    models.IntegerField(default=0, verbose_name="필드 순서"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "source_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_mappings",
                        to="erp_sync.erpfielddefinition",
                        verbose_name="소스 필드",
                    ),
                ),
                (
                    "table_mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_mappings",
                        to="erp_sync.erptablemapping",
                        verbose_name="테이블 매핑",
                    ),
                ),
                (
                    "target_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_mappings",
                        to="erp_sync.erptargetfield",
                        verbose_name="타겟 필드",
                    ),
                ),
            ],
            options={
                "verbose_name": "ERP 필드 매핑",
                "verbose_name_plural": "ERP 필드 매핑",
                "db_table": "erp_field_mapping",
                "ordering": ["table_mapping", "field_order"],
                "unique_together": {("table_mapping", "source_field")},
            },
        ),
    ]
