# Generated by Django 5.0 on 2026-03-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_sync", "0004_erpsource_erptargetmodel_erptabledefinition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="erpsource",
            name="password",
            field=models.CharField(blank=True, max_length=255, verbose_name="비밀번호"),
        ),
        migrations.AddField(
            model_name="erpsource",
            name="username",
            field=models.CharField(blank=True, max_length=100, verbose_name="사용자명"),
        ),
    ]
