# Generated by Django 5.0.1 on 2025-12-24 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DepartmentComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                ("department", models.CharField(max_length=100, verbose_name="부서")),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="매출 (억원)",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="비용 (억원)",
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="이익 (억원)",
                    ),
                ),
                ("headcount", models.IntegerField(default=0, verbose_name="인원")),
                (
                    "productivity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="생산성",
                    ),
                ),
                (
                    "target_achievement",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="목표 달성률 (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "부서별 비교",
                "verbose_name_plural": "부서별 비교",
                "db_table": "reports_department_comparison",
                "ordering": ["-fiscal_year", "-fiscal_month", "-profit"],
            },
        ),
        migrations.CreateModel(
            name="KeyMetricSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(max_length=100, verbose_name="지표명"),
                ),
                ("category", models.CharField(max_length=100, verbose_name="분류")),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="현재값",
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="목표값",
                    ),
                ),
                (
                    "previous_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="전기값",
                    ),
                ),
                (
                    "change_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="변동률 (%)",
                    ),
                ),
                (
                    "trend",
                    models.CharField(
                        choices=[("up", "상승"), ("stable", "유지"), ("down", "하락")],
                        default="stable",
                        max_length=10,
                        verbose_name="추세",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("good", "양호"),
                            ("warning", "주의"),
                            ("critical", "위험"),
                        ],
                        default="good",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=50, verbose_name="단위"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "주요 지표 요약",
                "verbose_name_plural": "주요 지표 요약",
                "db_table": "reports_key_metric_summary",
                "ordering": ["-fiscal_year", "-fiscal_month", "category"],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("financial", "재무"),
                            ("operational", "운영"),
                            ("strategic", "전략"),
                            ("hr", "인사"),
                            ("technology", "기술"),
                        ],
                        max_length=20,
                        verbose_name="분류",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "높음"), ("medium", "보통"), ("low", "낮음")],
                        default="medium",
                        max_length=10,
                        verbose_name="우선순위",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "검토대기"),
                            ("approved", "승인"),
                            ("in-progress", "진행중"),
                            ("completed", "완료"),
                            ("rejected", "반려"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "expected_benefit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="예상 효과 (억원)",
                    ),
                ),
                (
                    "required_investment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="필요 투자 (억원)",
                    ),
                ),
                (
                    "roi_estimate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="예상 ROI (%)",
                    ),
                ),
                (
                    "proposed_by",
                    models.CharField(max_length=100, verbose_name="제안자"),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=100, verbose_name="승인자"),
                ),
                (
                    "target_date",
                    models.DateField(blank=True, null=True, verbose_name="목표일"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "권고 사항",
                "verbose_name_plural": "권고 사항",
                "db_table": "reports_recommendation",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RiskOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("risk", "리스크"), ("opportunity", "기회")],
                        max_length=20,
                        verbose_name="유형",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                ("category", models.CharField(max_length=100, verbose_name="분류")),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "높음"), ("medium", "보통"), ("low", "낮음")],
                        default="medium",
                        max_length=10,
                        verbose_name="우선순위",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("identified", "식별"),
                            ("analyzing", "분석중"),
                            ("mitigating", "대응중"),
                            ("resolved", "해결"),
                            ("monitoring", "모니터링"),
                        ],
                        default="identified",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "impact",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="영향도 (억원)",
                    ),
                ),
                (
                    "probability",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="발생확률 (%)",
                    ),
                ),
                (
                    "response_plan",
                    models.TextField(blank=True, verbose_name="대응 계획"),
                ),
                ("owner", models.CharField(max_length=100, verbose_name="담당자")),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="처리 기한"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "리스크/기회",
                "verbose_name_plural": "리스크/기회",
                "db_table": "reports_risk_opportunity",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExecutiveSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="매출 (억원)",
                    ),
                ),
                (
                    "revenue_growth",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="매출 성장률 (%)",
                    ),
                ),
                (
                    "operating_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="영업이익 (억원)",
                    ),
                ),
                (
                    "operating_margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="영업이익률 (%)",
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="순이익 (억원)",
                    ),
                ),
                (
                    "net_margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="순이익률 (%)",
                    ),
                ),
                (
                    "production_volume",
                    models.IntegerField(default=0, verbose_name="생산량"),
                ),
                (
                    "quality_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="품질률 (%)",
                    ),
                ),
                (
                    "employee_count",
                    models.IntegerField(default=0, verbose_name="직원 수"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "경영진 요약",
                "verbose_name_plural": "경영진 요약",
                "db_table": "reports_executive_summary",
                "ordering": ["-fiscal_year", "-fiscal_month"],
                "unique_together": {("fiscal_year", "fiscal_month")},
            },
        ),
        migrations.CreateModel(
            name="MonthlyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("summary", models.TextField(verbose_name="요약")),
                ("highlights", models.TextField(blank=True, verbose_name="주요 성과")),
                ("concerns", models.TextField(blank=True, verbose_name="주요 이슈")),
                (
                    "next_month_plan",
                    models.TextField(blank=True, verbose_name="차월 계획"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "초안"),
                            ("review", "검토중"),
                            ("approved", "승인"),
                            ("published", "발행"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("author", models.CharField(max_length=100, verbose_name="작성자")),
                (
                    "reviewer",
                    models.CharField(blank=True, max_length=100, verbose_name="검토자"),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=100, verbose_name="승인자"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "월간 리포트",
                "verbose_name_plural": "월간 리포트",
                "db_table": "reports_monthly",
                "ordering": ["-fiscal_year", "-fiscal_month"],
                "unique_together": {("fiscal_year", "fiscal_month")},
            },
        ),
    ]
