"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-s!9lbsx4&lhlwj!g+1571y+qt&dey1dvrs^0fhx7et!n^#i#%u')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# ALLOWED_HOSTS - 환경변수에서 읽기
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

# Site URL for API documentation
SITE_URL = os.getenv('SITE_URL', 'http://localhost:8000')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'rest_framework',
    'corsheaders',
    'django_filters',
    'drf_yasg',

    # Celery
    'django_celery_beat',

    # Prometheus Metrics
    'django_prometheus',

    # Local apps
    'financial',
    'production',
    'quality',
    'sales',
    'purchase',
    'esg',
    'cost',
    'business_process',  # O2C, P2P 비즈니스 프로세스 관리
    'domain_agents',     # 도메인 에이전트 분석 (Cost, Quality, Production, etc.)
    'accounting',
    'manufacturing',
    'productivity',
    'development',
    'reports',
    'erp_sync',
    'ontology',
    'ai',  # AI prediction engine

    # AIBIS Enterprise AI Platform 추가
    'events',       # 이벤트 기반 아키텍처
    'governance',   # 거버넌스 레이어
    'control_tower', # 컨트롤 타워

    # Phase 1: Copilot, Data Hub, Event Taxonomy
    'ai.copilot.apps.CopilotConfig',   # AI Copilot 채팅 인터페이스
    'data_hub.apps.DataHubConfig',     # 데이터 통합 계층

    # Phase 2: RAG System
    'rag.apps.RagConfig',              # Retrieval Augmented Generation

    # Phase 3: Advanced Analytics & Integration
    'ml_pipeline.apps.MLPipelineConfig',      # ML Pipeline
    'forecasting.apps.ForecastingConfig',      # Time Series Forecasting
    'anomaly_detection.apps.AnomalyDetectionConfig',  # Anomaly Detection

    # Phase 4: External Integration & Data Visualization
    'integrations.apps.IntegrationsConfig',    # External Integration
    'visualization.apps.VisualizationConfig',  # Data Visualization

    # Phase 5: Performance, Security & DevOps
    'monitoring.apps.MonitoringConfig',       # System Monitoring
    'security.apps.SecurityConfig',           # Security & Audit

    # AXOS ERP V10.4 Integration
    'axos_erp',                               # AXOS ERP V10.4 Production Stack Integration

    'utils',  # 관리 명령(extend_timeseries 등) 및 미들웨어 공용 유틸
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Whitenoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Custom middleware
    'utils.middleware.RequestIDMiddleware',
    'utils.middleware.MetricsCollectionMiddleware',
    'utils.middleware.SecurityHeadersMiddleware',
    'utils.middleware.CacheControlMiddleware',
    # 'utils.rate_limiting.RateLimitMiddleware',  # Redis 필요, 선택적으로 활성화

    # Prometheus metrics (must be last)
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.AllowAny'],
    'DEFAULT_PAGINATION_CLASS': 'utils.standard_pagination.StandardPageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # API Documentation (drf-spectacular)
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # 레이트 리미팅은 선택적으로 활성화 (Redis 필요)
    # 'DEFAULT_THROTTLE_CLASSES': [
    #     'utils.rate_limiting.AnonymousRateThrottle',
    #     'utils.rate_limiting.UserRateThrottle',
    # ],
    # 'DEFAULT_THROTTLE_RATES': {
    #     'anonymous': '100/hour',
    #     'user': '1000/hour',
    #     'staff': '5000/hour',
    #     'burst': '10/second',
    # },
}

# CORS - 환경변수에서 설정
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'True') == 'True'
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if os.getenv('CORS_ALLOWED_ORIGINS') else []
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if os.getenv('CSRF_TRUSTED_ORIGINS') else []

# API Documentation Settings (drf-spectacular)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Claros MIS AI Dashboard API',
    'DESCRIPTION': 'Enterprise Manufacturing Intelligence System API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': '/api',
    'COMPONENT_SPLIT_REQUEST': True,
    'TAGS': [
        {'name': 'Dashboard', 'description': '대시보드 및 KPI 관리'},
        {'name': 'Production', 'description': '생산 현황 및 관리'},
        {'name': 'Quality', 'description': '품질 관리 및 검사'},
        {'name': 'Equipment', 'description': '설비 관리 및 모니터링'},
        {'name': 'Inventory', 'description': '재고 관리'},
        {'name': 'Cost', 'description': '원가 관리'},
        {'name': 'Finance', 'description': '재무 관리'},
        {'name': 'Purchasing', 'description': '구매 관리'},
        {'name': 'AI', 'description': 'AI 예측 및 분석'},
        {'name': 'Copilot', 'description': 'AI 코파일럿'},
        {'name': 'DataHub', 'description': '데이터 허브'},
        {'name': 'RAG', 'description': '검색 증강 생성'},
        {'name': 'ML Pipeline', 'description': '머신러닝 파이프라인'},
        {'name': 'Forecasting', 'description': '시계열 예측'},
        {'name': 'Anomaly Detection', 'description': '이상 탐지'},
        {'name': 'Integrations', 'description': '외부 연동'},
        {'name': 'Visualization', 'description': '데이터 시각화'},
        {'name': 'Monitoring', 'description': '시스템 모니터링'},
        {'name': 'Security', 'description': '보안 및 감사'},
    ],
    'SERVERS': [
        {'url': 'http://localhost:8000', 'description': 'Development Server'},
        {'url': 'https://api.claros-mis.com', 'description': 'Production Server'},
    ],
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# 데이터베이스 구성: 환경변수에 따라 PostgreSQL 사용
# DB_TYPE=prod → 운영 YH PostgreSQL
# DB_TYPE=local → 로컬 PostgreSQL
# DB_TYPE=sqlite → SQLite (개발용)
DB_TYPE = os.getenv('DB_TYPE', 'local')

if DB_TYPE == 'prod':
    # 운영 YH PostgreSQL 데이터베이스
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'YH'),
            'USER': os.getenv('DB_USER', 'yh'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'db!@yh#$1!'),
            'HOST': os.getenv('DB_HOST', '133.186.214.219'),
            'PORT': os.getenv('DB_PORT', '27455'),
            'OPTIONS': {
                'connect_timeout': 10,
                'sslmode': 'require',
            },
            'CONN_MAX_AGE': 600,
            'ATOMIC_REQUESTS': True,
        }
    }
elif DB_TYPE == 'sqlite':
    # SQLite 개발용 (간단한 테스트용)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # 로컬 PostgreSQL (기본)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'claros_mis'),
            'USER': os.getenv('DB_USER', 'claros_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'claros_password'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'OPTIONS': {
                'connect_timeout': 10,
            },
            'CONN_MAX_AGE': 0,  # 개발 환경에서는 연결 유지 안 함
            'ATOMIC_REQUESTS': False,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.getenv('STATIC_ROOT', BASE_DIR / 'staticfiles')

# Whitenoise for static files serving
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==========================================
# Production Security Settings
# ==========================================
if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'
    SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False') == 'True'
    CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False') == 'True'
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False') == 'True'
    SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'False') == 'True'
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'


# ==========================================
# MS SQL ERP Configuration
# ==========================================
MSSQL_CONFIG = {
    'host': os.getenv('MSSQL_HOST', '133.186.214.219'),
    'port': int(os.getenv('MSSQL_PORT', '27455')),
    'user': os.getenv('MSSQL_USER', 'yh'),
    'password': os.getenv('MSSQL_PASSWORD', ''),
    'database': os.getenv('MSSQL_DATABASE', 'YH'),
    'driver': os.getenv('MSSQL_DRIVER', 'ODBC Driver 17 for SQL Server'),
    'encrypt': os.getenv('MSSQL_ENCRYPT', 'no'),
    'trust_server_certificate': os.getenv('MSSQL_TRUST_SERVER_CERTIFICATE', 'yes'),
    'connection_timeout': int(os.getenv('MSSQL_CONNECTION_TIMEOUT', '30')),
}

# Sync Configuration
SYNC_BATCH_SIZE = int(os.getenv('SYNC_BATCH_SIZE', '1000'))
SYNC_RETRY_ATTEMPTS = int(os.getenv('SYNC_RETRY_ATTEMPTS', '3'))
SYNC_RETRY_DELAY = int(os.getenv('SYNC_RETRY_DELAY', '60'))
SYNC_TIMEOUT = int(os.getenv('SYNC_TIMEOUT', '300'))

# Table Sync Intervals (in seconds)
SYNC_SCHEDULE_REALTIME = int(os.getenv('SYNC_SCHEDULE_REALTIME', '900'))      # 15 minutes
SYNC_SCHEDULE_HOURLY = int(os.getenv('SYNC_SCHEDULE_HOURLY', '3600'))         # 1 hour
SYNC_SCHEDULE_DAILY = int(os.getenv('SYNC_SCHEDULE_DAILY', '86400'))          # 1 day
SYNC_SCHEDULE_WEEKLY = int(os.getenv('SYNC_SCHEDULE_WEEKLY', '604800'))       # 1 week
SYNC_SCHEDULE_MONTHLY = int(os.getenv('SYNC_SCHEDULE_MONTHLY', '2592000'))    # 1 month

# KPI Configuration
KPI_CACHE_ENABLED = os.getenv('KPI_CACHE_ENABLED', 'True') == 'True'
KPI_CACHE_TTL = int(os.getenv('KPI_CACHE_TTL', '300'))
KPI_CALCULATION_TIMEOUT = int(os.getenv('KPI_CALCULATION_TIMEOUT', '60'))


# ==========================================
# AIBIS Enterprise AI Platform Configuration
# ==========================================

# 에이전트 프레임워크 설정
AGENT_FRAMEWORK = {
    'ENABLED': os.getenv('AGENT_FRAMEWORK_ENABLED', 'True') == 'True',
    'DEFAULT_TIMEOUT': int(os.getenv('AGENT_DEFAULT_TIMEOUT', '30')),
    'MAX_CONCURRENT_AGENTS': int(os.getenv('AGENT_MAX_CONCURRENT', '10')),
    'LOG_EXECUTION': os.getenv('AGENT_LOG_EXECUTION', 'True') == 'True',
    'ENABLE_AUTO_CORRELATION': os.getenv('AGENT_AUTO_CORRELATION', 'True') == 'True',
}

# 이벤트 설정
EVENT_CONFIG = {
    'AUTO_CORRELATION_ENABLED': True,
    'CORRELATION_TIME_WINDOW_HOURS': 24,
    'MIN_CONFIDENCE_THRESHOLD': 0.5,
    'EVENT_RETENTION_DAYS': int(os.getenv('EVENT_RETENTION_DAYS', '365')),
}

# 에이전트 레이어 설정
AGENT_LAYERS = {
    'orchestration': {
        'priority': 1,
        'agents': ['ChiefOrchestratorAgent', 'IntentAgent', 'AnalysisPlannerAgent'],
    },
    'monitoring': {
        'priority': 2,
        'agents': ['KPIAgent', 'RiskAgent', 'EventDetectionAgent'],
    },
    'intelligence': {
        'priority': 3,
        'agents': ['DataIntegratorAgent', 'ContextBuilderAgent'],
    },
    'analysis': {
        'priority': 4,
        'agents': ['ForecastAgent', 'VarianceAgent', 'RootCauseAgent', 'ScenarioAgent'],
    },
    'decision': {
        'priority': 5,
        'agents': ['RecommendationAgent', 'ApprovalAdvisorAgent', 'AlertAgent'],
    },
    'learning': {
        'priority': 6,
        'agents': ['EvaluationAgent', 'ReflectionAgent', 'MemoryCuratorAgent'],
    },
}

# 거버넌스 설정
GOVERNANCE_CONFIG = {
    'POLICY_EVALUATION_ENABLED': True,
    'APPROVAL_WORKFLOW_ENABLED': True,
    'AUTO_APPROVAL_THRESHOLD': int(os.getenv('AUTO_APPROVAL_THRESHOLD', '1')),
    'ESCALATION_TIMEOUT_HOURS': int(os.getenv('ESCALATION_TIMEOUT_HOURS', '24')),
}

# 지식 그래프 설정
KNOWLEDGE_GRAPH_CONFIG = {
    'ENABLED': True,
    'GRAPH_BACKEND': os.getenv('GRAPH_BACKEND', 'networkx'),  # networkx or neo4j
    'AUTO_UPDATE_ENABLED': True,
    'MAX_GRAPH_SIZE': int(os.getenv('MAX_GRAPH_SIZE', '10000')),
}

# RAG 설정
RAG_CONFIG = {
    'ENABLED': True,
    'CHUNK_SIZE': int(os.getenv('RAG_CHUNK_SIZE', '500')),
    'CHUNK_OVERLAP': int(os.getenv('RAG_CHUNK_OVERLAP', '50')),
    'VECTOR_DB_BACKEND': os.getenv('VECTOR_DB_BACKEND', 'json'),  # json, pgvector, pinecone, weaviate
    'TOP_K_RESULTS': int(os.getenv('RAG_TOP_K', '5')),
}

# LLM Configuration (Phase 1 Upgrade)
LLM_CONFIG = {
    'ENABLED': os.getenv('LLM_ENABLED', 'True') == 'True',
    'PROVIDER': os.getenv('LLM_PROVIDER', 'anthropic'),  # anthropic, openai, azure
    'MODEL': os.getenv('LLM_MODEL', 'claude-sonnet-4-20250514'),
    'API_KEY': os.getenv('ANTHROPIC_API_KEY', ''),
    'MAX_TOKENS': int(os.getenv('LLM_MAX_TOKENS', '4096')),
    'TEMPERATURE': float(os.getenv('LLM_TEMPERATURE', '0.3')),
    'TOP_P': float(os.getenv('LLM_TOP_P', '0.9')),
    'TIMEOUT': int(os.getenv('LLM_TIMEOUT', '120')),
    'MAX_RETRIES': int(os.getenv('LLM_MAX_RETRIES', '3')),
    'ENABLE_STREAMING': os.getenv('LLM_ENABLE_STREAMING', 'False') == 'True',
    'CACHE_ENABLED': os.getenv('LLM_CACHE_ENABLED', 'True') == 'True',
    'CACHE_TTL': int(os.getenv('LLM_CACHE_TTL', '3600')),
}

# LLM API Keys (별도 설정 보안)
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY', '')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')

# 프롬프트 템플릿 설정
PROMPT_TEMPLATE_CONFIG = {
    'TEMPLATE_DIR': os.path.join(BASE_DIR, 'ai', 'prompts'),
    'AUTO_RELOAD': os.getenv('PROMPT_AUTO_RELOAD', 'True') == 'True',
    'ENABLE_VERSIONING': True,
}

# 컨트롤 타워 설정
CONTROL_TOWER_CONFIG = {
    'ENABLED': True,
    'REFRESH_INTERVAL_SECONDS': int(os.getenv('CONTROL_TOWER_REFRESH', '30')),
    'ALERT_THRESHOLD': {
        'critical': 1,
        'high': 3,
        'medium': 5,
    },
}

# AI Prediction Configuration
AI_PREDICTION_ENABLED = os.getenv('AI_PREDICTION_ENABLED', 'True') == 'True'
AI_MODEL_PATH = os.getenv('AI_MODEL_PATH', 'models/')
AI_PREDICTION_CACHE_TTL = int(os.getenv('AI_PREDICTION_CACHE_TTL', '3600'))


# ==========================================
# Celery Configuration
# ==========================================
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_WORKER_CONCURRENCY = int(os.getenv('CELERY_WORKER_CONCURRENCY', '4'))
CELERY_WORKER_AUTOSCALE_MIN = int(os.getenv('CELERY_WORKER_AUTOSCALE_MIN', '2'))
CELERY_WORKER_AUTOSCALE_MAX = int(os.getenv('CELERY_WORKER_AUTOSCALE_MAX', '8'))
CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes
CELERY_WORKER_PREFETCH_MULTIPLIER = 4
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000


# ==========================================
# Structured Logging Configuration
# ==========================================
LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO')
LOG_FORMAT = os.getenv('LOG_FORMAT', 'json')  # 'json' or 'text'
ELASTICSEARCH_URL = os.getenv('ELASTICSEARCH_URL', 'http://localhost:9200')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': 'utils.logging_config.StructuredFormatter',
            'format': '%(asctime)s %(name)s %(levelname)s %(message)s',
        },
        'text': {
            'format': '%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        },
        'verbose': {
            'format': '%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(message)s',
        },
    },
    'filters': {
        'elasticsearch_index': {
            '()': 'utils.logging_config.ElasticsearchIndexFilter',
            'index_prefix': 'claros-mis',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': LOG_FORMAT,
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': '/var/log/claros/app.log',
            'maxBytes': 100 * 1024 * 1024,  # 100MB
            'backupCount': 10,
            'formatter': LOG_FORMAT,
            'filters': ['elasticsearch_index'],
        },
        'error_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': '/var/log/claros/errors.log',
            'maxBytes': 50 * 1024 * 1024,  # 50MB
            'backupCount': 5,
            'formatter': LOG_FORMAT,
            'filters': ['elasticsearch_index'],
            'level': 'ERROR',
        },
    },
    'loggers': {
        '': {  # Root logger
            'handlers': ['console', 'file', 'error_file'],
            'level': LOG_LEVEL,
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'claros_mis': {
            'handlers': ['console', 'file', 'error_file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}


# ==========================================
# Prometheus Metrics Configuration
# ==========================================
ENABLE_METRICS = os.getenv('ENABLE_METRICS', 'True') == 'True'
# Windows-compatible path for prometheus metrics directory
PROMETHEUS_MULTIPROC_DIR = os.getenv('PROMETHEUS_MULTIPROC_DIR', BASE_DIR / 'logs' / 'prometheus')
# Create the directory if it doesn't exist
import os
os.makedirs(PROMETHEUS_MULTIPROC_DIR, exist_ok=True)


# ==========================================
# Adaptive Batch Configuration
# ==========================================
ADAPTIVE_BATCH_ENABLED = os.getenv('ADAPTIVE_BATCH_ENABLED', 'True') == 'True'
BATCH_SIZE_MIN = int(os.getenv('BATCH_SIZE_MIN', '100'))
BATCH_SIZE_MAX = int(os.getenv('BATCH_SIZE_MAX', '5000'))
NETWORK_CHECK_INTERVAL = int(os.getenv('NETWORK_CHECK_INTERVAL', '60'))

# ==========================================
# Logging Configuration
# ==========================================

# 로그 디렉토리 자동 생성
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {module} {funcName} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{levelname}] {asctime} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django.log',
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'error.log',
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

# ============================================================================
# Django 5.1 New Settings
# ============================================================================

# Async handler support for Django 5.1
ASGI_APPLICATION = 'config.asgi.application'

# ============================================================================
# Redis Cache Configuration
# ============================================================================
REDIS_HOST = os.getenv('REDIS_HOST', 'localhost')
REDIS_PORT = os.getenv('REDIS_PORT', '6379')
REDIS_DB = os.getenv('REDIS_DB', '0')
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD', '')
REDIS_URL = f'redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}' if REDIS_PASSWORD else f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'

# Redis 사용 가능 여부 확인
try:
    import redis
    REDIS_AVAILABLE = True
except ImportError:
    REDIS_AVAILABLE = False

if REDIS_AVAILABLE and os.getenv('USE_REDIS_CACHE', 'False') == 'True':
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
                'CONNECTION_POOL_KWARGS': {'max_connections': 100}
            },
            'KEY_PREFIX': 'claros_mis',
            'TIMEOUT': 300,
            'VERSION': 1,
        },
        'kpi_cache': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'claros_kpi',
            'TIMEOUT': 300,
        },
    }
else:
    # Redis 없이 로컬 캐시 사용
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
            'OPTIONS': {
                'MAX_ENTRIES': 1000
            }
        },
        'kpi_cache': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'kpi-cache',
            'OPTIONS': {
                'MAX_ENTRIES': 500
            }
        },
    }

# Cache enabled settings
KPI_CACHE_ENABLED = os.getenv('KPI_CACHE_ENABLED', 'True') == 'True'
KPI_CACHE_TTL = int(os.getenv('KPI_CACHE_TTL', '300'))

# ============================================================================
# Rate Limiting Configuration
# ============================================================================
RATELIMIT_ENABLE = os.getenv('RATELIMIT_ENABLE', 'True') == 'True'
RATELIMIT_USE_CACHE = 'default'

# Rate limits per user type
RATELIMIT_VIEW_RATE_LIMITS = {
    'anonymous': '100/hour',
    'user': '1000/hour',
    'staff': '5000/hour',
}

# ============================================================================
# API Versioning Configuration
# ============================================================================
API_VERSION = os.getenv('API_VERSION', 'v1')
API_VERSIONS = {
    'v1': '1.0',
    'v2': '2.0',
}

# API versioning settings
REST_FRAMEWORK.update({
    'DEFAULT_VERSION': API_VERSION,
    'ALLOWED_VERSIONS': list(API_VERSIONS.keys()),
    'VERSION_PARAM': 'version',
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
})

# ============================================================================
# WebSocket/Channels Configuration
# ============================================================================
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_URL],
            'capacity': 1500,
            'expiry': 10,
        },
    },
}

CHANNEL_WS_PROTOCOLS = ['ws', 'wss']

# ============================================================================
# Django 5.1 Performance Settings
# ============================================================================

# Enable database connection persisting
CONN_MAX_AGE = 600

# Enable transaction pooling for better performance
ATOMIC_REQUESTS = True

# Optimize database queries
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# Async Settings for Django 5.1
# ============================================================================

# Enable async test runner
TEST_RUNNER = 'django.test.runner.DiscoverRunner'

# ============================================================================
# Enhanced Security Settings for Django 5.1
# ============================================================================

# Content Security Policy
SECURE_CONTENT_SECURITY_POLICY = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:; frame-ancestors 'none';"

# Permission Policy
SECURE_PERMISSIONS_POLICY = {
    'accelerometer': [],
    'ambient-light-sensor': [],
    'autoplay': [],
    'camera': [],
    'display-capture': [],
    'document-domain': [],
    'encrypted-media': [],
    'fullscreen': [],
    'geolocation': [],
    'gyroscope': [],
    'interest-cohort': [],
    'magnetometer': [],
    'microphone': [],
    'midi': [],
    'payment': [],
    'picture-in-picture': [],
    'publickey-credentials-get': [],
    'screen-wake-lock': [],
    'sync-xhr': [],
    'usb': [],
    'web-share': [],
    'xr-spatial-tracking': [],
}

# Cross-Origin-Opener-Policy
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'

# Cross-Origin-Resource-Policy
SECURE_CROSS_ORIGIN_RESOURCE_POLICY = 'same-origin'

# ============================================================================
# Django 5.1 Async Database Settings
# ============================================================================

# Enable async database operations (PostgreSQL only)
if DB_TYPE != 'sqlite':
    DATABASES['default']['OPTIONS'] = DATABASES['default'].get('OPTIONS', {})
    DATABASES['default']['OPTIONS']['connect_timeout'] = 10

# ============================================================================
# Django 5.1 Form/Template Settings
# ============================================================================

# Default form rendering
FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

# ============================================================================
# Django 5.1 File Upload Settings
# ============================================================================

# File upload limits
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000
