# Generated by Django 4.2.7 on 2026-03-31 08:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnomalyPattern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="패턴명")),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("seasonal", "계절적"),
                            ("trend", "추세"),
                            ("sporadic", "산발적"),
                            ("cyclical", "주기적"),
                        ],
                        max_length=20,
                        verbose_name="패턴 유형",
                    ),
                ),
                ("metrics", models.JSONField(default=list, verbose_name="관련 지표")),
                (
                    "time_window",
                    models.CharField(max_length=50, verbose_name="시간 윈도우"),
                ),
                ("frequency", models.IntegerField(default=1, verbose_name="빈도")),
                ("conditions", models.JSONField(default=dict, verbose_name="조건")),
                (
                    "threshold_exceeded",
                    models.FloatField(default=2.0, verbose_name="초과 임계값"),
                ),
                (
                    "occurrence_count",
                    models.IntegerField(default=0, verbose_name="발생 횟수"),
                ),
                (
                    "last_occurrence",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 발생"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "이상 패턴",
                "verbose_name_plural": "이상 패턴",
                "db_table": "anomaly_pattern",
                "indexes": [
                    models.Index(
                        fields=["pattern_type", "is_active"],
                        name="anomaly_pat_pattern_a83bfc_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AnomalyDetector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="탐지기명")),
                (
                    "code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="탐지기 코드"
                    ),
                ),
                (
                    "target_metric",
                    models.CharField(max_length=100, verbose_name="타겟 지표"),
                ),
                (
                    "target_entity",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="타겟 엔티티"
                    ),
                ),
                (
                    "detector_type",
                    models.CharField(
                        choices=[
                            ("statistical", "통계적"),
                            ("ml_based", "머신러닝 기반"),
                            ("isolation_forest", "Isolation Forest"),
                            ("autoencoder", "오토인코더"),
                            ("lstm_ad", "LSTM AD"),
                            ("ensemble", "앙상블"),
                        ],
                        max_length=50,
                        verbose_name="탐지기 유형",
                    ),
                ),
                ("parameters", models.JSONField(default=dict, verbose_name="파라미터")),
                ("threshold", models.FloatField(default=2.0, verbose_name="임계값")),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[("low", "낮음"), ("medium", "중간"), ("high", "높음")],
                        default="medium",
                        max_length=20,
                        verbose_name="민감도",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("training", "학습 중"),
                            ("ready", "준비 완료"),
                            ("active", "활성"),
                            ("disabled", "비활성"),
                        ],
                        default="training",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "last_trained",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 학습일"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "이상탐지기",
                "verbose_name_plural": "이상탐지기",
                "db_table": "anomaly_detector",
                "indexes": [
                    models.Index(fields=["code"], name="anomaly_det_code_076260_idx"),
                    models.Index(
                        fields=["target_metric", "status"],
                        name="anomaly_det_target__9fda99_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AnomalyAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("detected_at", models.DateTimeField(verbose_name="감지일")),
                (
                    "metric_name",
                    models.CharField(max_length=100, verbose_name="지표명"),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="엔티티 ID"
                    ),
                ),
                ("actual_value", models.FloatField(verbose_name="실제값")),
                ("expected_value", models.FloatField(verbose_name="예상값")),
                ("deviation_score", models.FloatField(verbose_name="편차 점수")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "낮음"),
                            ("medium", "중간"),
                            ("high", "높음"),
                            ("critical", "매우 높음"),
                        ],
                        max_length=20,
                        verbose_name="심각도",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "열림"),
                            ("investigating", "조사 중"),
                            ("resolved", "해결됨"),
                            ("false_positive", "오탐"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("context", models.JSONField(default=dict, verbose_name="컨텍스트")),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="해결일"),
                ),
                (
                    "resolved_by",
                    models.CharField(blank=True, max_length=100, verbose_name="해결자"),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="해결 비고"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "detector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="anomaly_detection.anomalydetector",
                        verbose_name="이상탐지기",
                    ),
                ),
            ],
            options={
                "verbose_name": "이상 알림",
                "verbose_name_plural": "이상 알림",
                "db_table": "anomaly_alert",
                "indexes": [
                    models.Index(
                        fields=["detector", "-detected_at"],
                        name="anomaly_ale_detecto_01303d_idx",
                    ),
                    models.Index(
                        fields=["status", "-detected_at"],
                        name="anomaly_ale_status_d12b36_idx",
                    ),
                    models.Index(
                        fields=["severity", "-detected_at"],
                        name="anomaly_ale_severit_8b6e65_idx",
                    ),
                ],
            },
        ),
    ]
