# Generated by Django 5.0.1 on 2025-12-23 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("VIP", "VIP"),
                            ("Gold", "Gold"),
                            ("Silver", "Silver"),
                            ("Bronze", "Bronze"),
                            ("New", "New"),
                        ],
                        max_length=20,
                        verbose_name="등급",
                    ),
                ),
                (
                    "customer_count",
                    models.IntegerField(default=0, verbose_name="고객수"),
                ),
                (
                    "sales_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="매출액",
                    ),
                ),
                (
                    "share_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="비중 (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "고객등급별 매출",
                "verbose_name_plural": "고객등급별 매출",
                "db_table": "sales_customer_tier",
                "ordering": ["-fiscal_year", "-fiscal_month"],
            },
        ),
        migrations.CreateModel(
            name="ProductSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "product_code",
                    models.CharField(max_length=50, verbose_name="제품코드"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="제품명"),
                ),
                (
                    "sales_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="매출액",
                    ),
                ),
                (
                    "sales_quantity",
                    models.IntegerField(default=0, verbose_name="판매수량"),
                ),
                (
                    "share_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="비중 (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "제품별 매출",
                "verbose_name_plural": "제품별 매출",
                "db_table": "sales_product",
                "ordering": ["-fiscal_year", "-fiscal_month", "-sales_amount"],
            },
        ),
        migrations.CreateModel(
            name="SalesPipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("lead", "신규 리드"),
                            ("contact", "상담 중"),
                            ("proposal", "제안 제출"),
                            ("negotiation", "협상 중"),
                            ("closing", "계약 임박"),
                        ],
                        max_length=20,
                        verbose_name="단계",
                    ),
                ),
                (
                    "opportunity_count",
                    models.IntegerField(default=0, verbose_name="기회 건수"),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="총 금액",
                    ),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="전환율 (%)",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "영업 파이프라인",
                "verbose_name_plural": "영업 파이프라인",
                "db_table": "sales_pipeline",
                "ordering": ["-fiscal_year", "-fiscal_month"],
            },
        ),
        migrations.CreateModel(
            name="SalesTeamPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "salesperson_name",
                    models.CharField(max_length=100, verbose_name="영업사원명"),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="목표"
                    ),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="실적"
                    ),
                ),
                (
                    "deal_count",
                    models.IntegerField(default=0, verbose_name="계약 건수"),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="성사율 (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "영업팀 성과",
                "verbose_name_plural": "영업팀 성과",
                "db_table": "sales_team_performance",
                "ordering": ["-fiscal_year", "-fiscal_month", "-actual_amount"],
            },
        ),
        migrations.CreateModel(
            name="TopCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "customer_code",
                    models.CharField(max_length=50, verbose_name="거래처코드"),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=200, verbose_name="거래처명"),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="매출액",
                    ),
                ),
                (
                    "growth_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="성장률 (%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "활성"),
                            ("warning", "주의"),
                            ("hot", "HOT"),
                            ("inactive", "비활성"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "주요 거래처",
                "verbose_name_plural": "주요 거래처",
                "db_table": "sales_top_customer",
                "ordering": ["-fiscal_year", "-fiscal_month", "-revenue"],
            },
        ),
        migrations.CreateModel(
            name="MonthlySales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="목표 매출",
                    ),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="실제 매출",
                    ),
                ),
                (
                    "achievement_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="달성률 (%)",
                    ),
                ),
                (
                    "new_customers",
                    models.IntegerField(default=0, verbose_name="신규 거래처"),
                ),
                (
                    "contract_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="계약 성사율 (%)",
                    ),
                ),
                (
                    "pipeline_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="파이프라인 금액",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "월별 매출",
                "verbose_name_plural": "월별 매출",
                "db_table": "sales_monthly",
                "ordering": ["-fiscal_year", "-fiscal_month"],
                "unique_together": {("fiscal_year", "fiscal_month")},
            },
        ),
    ]
