# Generated by Django 5.0.1 on 2025-12-26 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OntologyAnalysisLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(max_length=50, verbose_name="분석 유형"),
                ),
                (
                    "start_category",
                    models.CharField(max_length=10, verbose_name="시작 카테고리"),
                ),
                (
                    "end_category",
                    models.CharField(max_length=10, verbose_name="종료 카테고리"),
                ),
                ("analysis_date", models.DateField(verbose_name="분석 기준일")),
                (
                    "parameters",
                    models.JSONField(default=dict, verbose_name="분석 파라미터"),
                ),
                (
                    "result_summary",
                    models.JSONField(default=dict, verbose_name="분석 결과 요약"),
                ),
                (
                    "record_count",
                    models.IntegerField(default=0, verbose_name="처리 건수"),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(default=0, verbose_name="실행시간(ms)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기"),
                            ("RUNNING", "실행중"),
                            ("COMPLETED", "완료"),
                            ("FAILED", "실패"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="에러 메시지"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료일시"
                    ),
                ),
            ],
            options={
                "verbose_name": "온톨로지 분석 로그",
                "verbose_name_plural": "온톨로지 분석 로그",
                "db_table": "ontology_analysis_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OntologyCategory",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="카테고리 코드",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="카테고리명")),
                (
                    "name_en",
                    models.CharField(blank=True, max_length=50, verbose_name="영문명"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("level", models.IntegerField(default=1, verbose_name="계층 레벨")),
                ("sort_order", models.IntegerField(default=0, verbose_name="정렬순서")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="ontology.ontologycategory",
                        verbose_name="상위 카테고리",
                    ),
                ),
            ],
            options={
                "verbose_name": "온톨로지 카테고리",
                "verbose_name_plural": "온톨로지 카테고리",
                "db_table": "ontology_category",
                "ordering": ["level", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="DataFlowMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_date", models.DateField(verbose_name="기준일자")),
                (
                    "metric_name",
                    models.CharField(max_length=100, verbose_name="지표명"),
                ),
                (
                    "metric_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="지표값",
                    ),
                ),
                (
                    "metric_unit",
                    models.CharField(blank=True, max_length=20, verbose_name="단위"),
                ),
                (
                    "previous_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="이전값",
                    ),
                ),
                (
                    "change_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="변화율(%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("UP", "상승"), ("DOWN", "하락"), ("STABLE", "유지")],
                        default="STABLE",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="ontology.ontologycategory",
                        verbose_name="카테고리",
                    ),
                ),
            ],
            options={
                "verbose_name": "데이터 흐름 지표",
                "verbose_name_plural": "데이터 흐름 지표",
                "db_table": "ontology_data_flow_metrics",
                "ordering": ["-metric_date", "category"],
            },
        ),
        migrations.CreateModel(
            name="OntologyElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, verbose_name="요소 코드")),
                ("name_ko", models.CharField(max_length=100, verbose_name="한글명")),
                ("name_en", models.CharField(max_length=100, verbose_name="영문명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="아이콘"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6", max_length=20, verbose_name="색상코드"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="정렬순서")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="ontology.ontologycategory",
                        verbose_name="카테고리",
                    ),
                ),
            ],
            options={
                "verbose_name": "온톨로지 요소",
                "verbose_name_plural": "온톨로지 요소",
                "db_table": "ontology_element",
                "ordering": ["category", "sort_order"],
                "unique_together": {("category", "code")},
            },
        ),
        migrations.CreateModel(
            name="ERPTableMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_name",
                    models.CharField(max_length=50, verbose_name="ERP 테이블명"),
                ),
                (
                    "table_description",
                    models.CharField(max_length=200, verbose_name="테이블 설명"),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="모듈구분"
                    ),
                ),
                (
                    "key_columns",
                    models.JSONField(default=list, verbose_name="주요 컬럼"),
                ),
                (
                    "link_columns",
                    models.JSONField(default=list, verbose_name="연계 컬럼"),
                ),
                (
                    "data_flow_direction",
                    models.CharField(
                        choices=[("IN", "입력"), ("OUT", "출력"), ("BOTH", "양방향")],
                        default="IN",
                        max_length=10,
                        verbose_name="데이터 흐름",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="erp_tables",
                        to="ontology.ontologyelement",
                        verbose_name="온톨로지 요소",
                    ),
                ),
            ],
            options={
                "verbose_name": "ERP 테이블 맵핑",
                "verbose_name_plural": "ERP 테이블 맵핑",
                "db_table": "ontology_erp_mapping",
                "ordering": ["element", "table_name"],
            },
        ),
        migrations.CreateModel(
            name="OntologyRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("TRANSFORM", "변환"),
                            ("AGGREGATE", "집계"),
                            ("ALLOCATE", "배부"),
                            ("REFERENCE", "참조"),
                            ("CALCULATE", "계산"),
                            ("FLOW", "흐름"),
                        ],
                        max_length=20,
                        verbose_name="관계 유형",
                    ),
                ),
                (
                    "link_key",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="연계 키"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=5,
                        verbose_name="가중치",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "source_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_relations",
                        to="ontology.ontologyelement",
                        verbose_name="소스 요소",
                    ),
                ),
                (
                    "target_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_relations",
                        to="ontology.ontologyelement",
                        verbose_name="타겟 요소",
                    ),
                ),
            ],
            options={
                "verbose_name": "온톨로지 관계",
                "verbose_name_plural": "온톨로지 관계",
                "db_table": "ontology_relation",
                "unique_together": {
                    ("source_element", "target_element", "relation_type")
                },
            },
        ),
    ]
