# Generated by Django 4.2.7 on 2026-03-30 07:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ontology", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OntologyNode",
            fields=[
                (
                    "node_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="노드 ID",
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("entity", "엔티티"),
                            ("concept", "개념"),
                            ("relationship", "관계"),
                            ("event", "이벤트"),
                            ("process", "프로세스"),
                        ],
                        max_length=50,
                        verbose_name="노드 유형",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="이름")),
                (
                    "code",
                    models.CharField(blank=True, max_length=100, verbose_name="코드"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="카테고리"
                    ),
                ),
                ("labels", models.JSONField(default=list, verbose_name="레이블")),
                ("properties", models.JSONField(default=dict, verbose_name="속성")),
                ("metadata", models.JSONField(default=dict, verbose_name="메타데이터")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "온톨로지 노드",
                "verbose_name_plural": "온톨로지 노드",
                "indexes": [
                    models.Index(
                        fields=["node_type", "category"],
                        name="ontology_on_node_ty_ae0ea6_idx",
                    ),
                    models.Index(
                        fields=["name", "code"], name="ontology_on_name_d5f26e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OntologyEdge",
            fields=[
                (
                    "edge_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="엣지 ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("causal", "인과"),
                            ("temporal", "시간적"),
                            ("spatial", "공간적"),
                            ("hierarchical", "계층적"),
                            ("association", "연관"),
                            ("dependency", "의존"),
                            ("transformation", "변환"),
                        ],
                        max_length=50,
                        verbose_name="관계 유형",
                    ),
                ),
                ("properties", models.JSONField(default=dict, verbose_name="속성")),
                ("weight", models.FloatField(default=1.0, verbose_name="가중치")),
                ("confidence", models.FloatField(default=1.0, verbose_name="신뢰도")),
                ("metadata", models.JSONField(default=dict, verbose_name="메타데이터")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "source_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="ontology.ontologynode",
                        verbose_name="소스 노드",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="ontology.ontologynode",
                        verbose_name="타겟 노드",
                    ),
                ),
            ],
            options={
                "verbose_name": "온톨로지 엣지",
                "verbose_name_plural": "온톨로지 엣지",
                "indexes": [
                    models.Index(
                        fields=["source_node", "relationship_type"],
                        name="ontology_on_source__fbeced_idx",
                    ),
                    models.Index(
                        fields=["target_node", "relationship_type"],
                        name="ontology_on_target__543bc1_idx",
                    ),
                ],
                "unique_together": {
                    ("source_node", "target_node", "relationship_type")
                },
            },
        ),
    ]
