# Generated by Django 5.0.1 on 2025-12-23 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_code", models.CharField(max_length=50, verbose_name="품목코드")),
                ("item_name", models.CharField(max_length=200, verbose_name="품목명")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("A", "A등급 (고가/중요)"),
                            ("B", "B등급 (중간)"),
                            ("C", "C등급 (저가)"),
                        ],
                        max_length=1,
                        verbose_name="ABC 등급",
                    ),
                ),
                (
                    "current_stock",
                    models.IntegerField(default=0, verbose_name="현재 재고"),
                ),
                (
                    "safety_stock",
                    models.IntegerField(default=0, verbose_name="안전 재고"),
                ),
                (
                    "stock_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="재고가치",
                    ),
                ),
                (
                    "turnover_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="회전율"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("adequate", "적정"),
                            ("low", "부족"),
                            ("high", "과다"),
                            ("critical", "긴급"),
                        ],
                        default="adequate",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "재고",
                "verbose_name_plural": "재고",
                "db_table": "purchase_inventory",
                "ordering": ["-stock_value"],
            },
        ),
        migrations.CreateModel(
            name="InventoryTurnover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("raw", "원자재"),
                            ("parts", "부자재"),
                            ("finished", "완제품"),
                            ("semi", "반제품"),
                            ("consumable", "소모품"),
                        ],
                        max_length=20,
                        verbose_name="분류",
                    ),
                ),
                (
                    "turnover_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="회전율"
                    ),
                ),
                (
                    "days_in_inventory",
                    models.IntegerField(default=0, verbose_name="재고일수"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "재고 회전율",
                "verbose_name_plural": "재고 회전율",
                "db_table": "purchase_inventory_turnover",
                "ordering": ["-fiscal_year", "-fiscal_month"],
            },
        ),
        migrations.CreateModel(
            name="MaterialPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "material_code",
                    models.CharField(max_length=50, verbose_name="원자재코드"),
                ),
                (
                    "material_name",
                    models.CharField(max_length=200, verbose_name="원자재명"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="단가"
                    ),
                ),
                (
                    "previous_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="전월 단가",
                    ),
                ),
                (
                    "change_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="변동률 (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "원자재 가격",
                "verbose_name_plural": "원자재 가격",
                "db_table": "purchase_material_price",
                "ordering": ["-fiscal_year", "-fiscal_month"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "po_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="PO 번호"
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(max_length=200, verbose_name="공급사"),
                ),
                ("item_name", models.CharField(max_length=200, verbose_name="품목")),
                ("quantity", models.IntegerField(default=0, verbose_name="수량")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="단가"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="총액"
                    ),
                ),
                ("order_date", models.DateField(verbose_name="발주일")),
                ("delivery_date", models.DateField(verbose_name="납기일")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ordered", "발주완료"),
                            ("in-transit", "운송중"),
                            ("received", "입고완료"),
                            ("delayed", "지연"),
                        ],
                        default="ordered",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "is_urgent",
                    models.BooleanField(default=False, verbose_name="긴급 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "발주",
                "verbose_name_plural": "발주",
                "db_table": "purchase_order",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="업체코드"
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(max_length=200, verbose_name="업체명"),
                ),
                (
                    "quality_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="품질 점수",
                    ),
                ),
                (
                    "delivery_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="납기 점수",
                    ),
                ),
                (
                    "price_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="가격 점수",
                    ),
                ),
                (
                    "service_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="서비스 점수",
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="종합 점수",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A", "A등급"),
                            ("B", "B등급"),
                            ("C", "C등급"),
                            ("D", "D등급"),
                        ],
                        default="B",
                        max_length=1,
                        verbose_name="등급",
                    ),
                ),
                (
                    "trend",
                    models.CharField(
                        choices=[("up", "상승"), ("stable", "유지"), ("down", "하락")],
                        default="stable",
                        max_length=10,
                        verbose_name="추세",
                    ),
                ),
                (
                    "purchase_share",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="구매 비중 (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "공급업체",
                "verbose_name_plural": "공급업체",
                "db_table": "purchase_supplier",
                "ordering": ["-total_score"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "purchase_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="구매액",
                    ),
                ),
                (
                    "previous_month_change",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="전월 대비 증감률 (%)",
                    ),
                ),
                (
                    "order_count",
                    models.IntegerField(default=0, verbose_name="발주 건수"),
                ),
                (
                    "pending_orders",
                    models.IntegerField(default=0, verbose_name="입고 대기 건수"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "월별 구매",
                "verbose_name_plural": "월별 구매",
                "db_table": "purchase_monthly",
                "ordering": ["-fiscal_year", "-fiscal_month"],
                "unique_together": {("fiscal_year", "fiscal_month")},
            },
        ),
    ]
