# Generated by Django 4.2.7 on 2026-03-31 08:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IntegrationConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="연동명")),
                (
                    "code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="연동 코드"
                    ),
                ),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("erp", "ERP 시스템"),
                            ("api", "외부 API"),
                            ("database", "데이터베이스"),
                            ("file", "파일"),
                            ("webhook", "웹훅"),
                        ],
                        max_length=50,
                        verbose_name="연동 유형",
                    ),
                ),
                (
                    "endpoint_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="엔드포인트 URL"
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("none", "없음"),
                            ("basic", "Basic Auth"),
                            ("bearer", "Bearer Token"),
                            ("api_key", "API Key"),
                            ("oauth2", "OAuth 2.0"),
                        ],
                        default="none",
                        max_length=50,
                        verbose_name="인증 유형",
                    ),
                ),
                (
                    "auth_config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="인증 설정"
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="요청 헤더"
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="연동 파라미터"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                (
                    "sync_interval",
                    models.IntegerField(default=60, verbose_name="동기화 간격(분)"),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 동기화"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
            ],
            options={
                "verbose_name": "연동 설정",
                "verbose_name_plural": "연동 설정",
                "db_table": "integration_config",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="웹훅명")),
                (
                    "code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="웹훅 코드"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=100, verbose_name="이벤트 유형"),
                ),
                (
                    "target_url",
                    models.URLField(max_length=500, verbose_name="대상 URL"),
                ),
                (
                    "http_method",
                    models.CharField(
                        choices=[("POST", "POST"), ("PUT", "PUT"), ("PATCH", "PATCH")],
                        default="POST",
                        max_length=10,
                        verbose_name="HTTP 메서드",
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="요청 헤더"
                    ),
                ),
                (
                    "payload_template",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="페이로드 템플릿"
                    ),
                ),
                (
                    "retry_policy",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="재시도 정책"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
            ],
            options={
                "verbose_name": "웹훅 설정",
                "verbose_name_plural": "웹훅 설정",
                "db_table": "webhook_config",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataExchange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "exchange_type",
                    models.CharField(
                        choices=[("export", "내보내기"), ("import", "가져오기")],
                        max_length=20,
                        verbose_name="교환 유형",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(max_length=50, verbose_name="데이터 유형"),
                ),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("excel", "Excel"),
                            ("json", "JSON"),
                            ("xml", "XML"),
                        ],
                        max_length=20,
                        verbose_name="파일 형식",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="파일 경로"
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="파일 크기(bytes)"
                    ),
                ),
                (
                    "record_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="레코드 수"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("processing", "처리 중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "columns",
                    models.JSONField(blank=True, default=list, verbose_name="열 정보"),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="필터 조건"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="에러 메시지"),
                ),
                (
                    "requested_by",
                    models.CharField(blank=True, max_length=100, verbose_name="요청자"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="시작 시간"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료 시간"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
            ],
            options={
                "verbose_name": "데이터 교환",
                "verbose_name_plural": "데이터 교환",
                "db_table": "data_exchange",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["exchange_type", "status"],
                        name="data_exchan_exchang_b8119a_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="data_exchan_created_eef0eb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="이벤트 ID"
                    ),
                ),
                ("payload", models.JSONField(verbose_name="전송 데이터")),
                (
                    "response_status",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="응답 상태코드"
                    ),
                ),
                (
                    "response_body",
                    models.TextField(blank=True, verbose_name="응답 본문"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="에러 메시지"),
                ),
                (
                    "attempt_count",
                    models.IntegerField(default=1, verbose_name="시도 횟수"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("delivered", "전송 완료"),
                            ("failed", "실패"),
                            ("retrying", "재시도 중"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="전송 시간"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="integrations.webhookconfig",
                        verbose_name="웹훅",
                    ),
                ),
            ],
            options={
                "verbose_name": "웹훅 전송 기록",
                "verbose_name_plural": "웹훅 전송 기록",
                "db_table": "webhook_delivery",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["webhook", "status"],
                        name="webhook_del_webhook_1ac442_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="webhook_del_created_ebc097_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IntegrationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("sync", "동기화"),
                            ("export", "내보내기"),
                            ("import", "가져오기"),
                            ("webhook", "웹훅"),
                            ("api_call", "API 호출"),
                        ],
                        max_length=50,
                        verbose_name="작업 유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("running", "실행 중"),
                            ("success", "성공"),
                            ("failed", "실패"),
                            ("partial", "부분 성공"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="요청 데이터"
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="응답 데이터"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="에러 메시지"),
                ),
                (
                    "records_processed",
                    models.IntegerField(default=0, verbose_name="처理된 레코드 수"),
                ),
                (
                    "records_succeeded",
                    models.IntegerField(default=0, verbose_name="성공 레코드 수"),
                ),
                (
                    "records_failed",
                    models.IntegerField(default=0, verbose_name="실패 레코드 수"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="시작 시간"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료 시간"
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True, null=True, verbose_name="소요 시간(초)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="integrations.integrationconfig",
                        verbose_name="연동",
                    ),
                ),
            ],
            options={
                "verbose_name": "연동 로그",
                "verbose_name_plural": "연동 로그",
                "db_table": "integration_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["integration", "status"],
                        name="integration_integra_3b94a1_idx",
                    ),
                    models.Index(
                        fields=["action_type", "status"],
                        name="integration_action__babd66_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="integration_created_e48687_idx"
                    ),
                ],
            },
        ),
    ]
