# Generated by Django 5.0.1 on 2025-12-24 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyProductionSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "production_date",
                    models.DateField(unique=True, verbose_name="생산일자"),
                ),
                (
                    "total_target",
                    models.IntegerField(default=0, verbose_name="총 목표 생산량"),
                ),
                (
                    "total_actual",
                    models.IntegerField(default=0, verbose_name="총 실제 생산량"),
                ),
                (
                    "total_defects",
                    models.IntegerField(default=0, verbose_name="총 불량 수"),
                ),
                (
                    "overall_efficiency",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="전체 효율 (%)",
                    ),
                ),
                (
                    "defect_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="불량률 (%)",
                    ),
                ),
                (
                    "active_lines",
                    models.IntegerField(default=0, verbose_name="가동 라인 수"),
                ),
                (
                    "total_workers",
                    models.IntegerField(default=0, verbose_name="총 작업자 수"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "일일 생산 요약",
                "verbose_name_plural": "일일 생산 요약",
                "db_table": "productivity_daily_summary",
                "ordering": ["-production_date"],
            },
        ),
        migrations.CreateModel(
            name="HourlyProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("production_date", models.DateField(verbose_name="생산일자")),
                (
                    "hour",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                        verbose_name="시간",
                    ),
                ),
                ("line_id", models.CharField(max_length=50, verbose_name="라인 ID")),
                ("line_name", models.CharField(max_length=100, verbose_name="라인명")),
                (
                    "target_output",
                    models.IntegerField(default=0, verbose_name="목표 생산량"),
                ),
                (
                    "actual_output",
                    models.IntegerField(default=0, verbose_name="실제 생산량"),
                ),
                (
                    "achievement_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="달성률 (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "시간당 생산량",
                "verbose_name_plural": "시간당 생산량",
                "db_table": "productivity_hourly_production",
                "ordering": ["-production_date", "-hour"],
            },
        ),
        migrations.CreateModel(
            name="LineUtilization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                ("line_id", models.CharField(max_length=50, verbose_name="라인 ID")),
                ("line_name", models.CharField(max_length=100, verbose_name="라인명")),
                (
                    "planned_time",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="계획 가동시간 (시간)",
                    ),
                ),
                (
                    "actual_time",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="실제 가동시간 (시간)",
                    ),
                ),
                (
                    "downtime",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="정지시간 (시간)",
                    ),
                ),
                (
                    "utilization_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="가동률 (%)",
                    ),
                ),
                (
                    "target_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=90,
                        max_digits=5,
                        verbose_name="목표 가동률 (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "라인 가동률",
                "verbose_name_plural": "라인 가동률",
                "db_table": "productivity_line_utilization",
                "ordering": ["-fiscal_year", "-fiscal_month", "-utilization_rate"],
            },
        ),
        migrations.CreateModel(
            name="OEEComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                ("line_id", models.CharField(max_length=50, verbose_name="라인 ID")),
                ("line_name", models.CharField(max_length=100, verbose_name="라인명")),
                (
                    "availability",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="가용성 (%)",
                    ),
                ),
                (
                    "availability_target",
                    models.DecimalField(
                        decimal_places=2,
                        default=90,
                        max_digits=5,
                        verbose_name="가용성 목표 (%)",
                    ),
                ),
                (
                    "performance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="성능 (%)",
                    ),
                ),
                (
                    "performance_target",
                    models.DecimalField(
                        decimal_places=2,
                        default=95,
                        max_digits=5,
                        verbose_name="성능 목표 (%)",
                    ),
                ),
                (
                    "quality_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="품질률 (%)",
                    ),
                ),
                (
                    "quality_target",
                    models.DecimalField(
                        decimal_places=2,
                        default=99,
                        max_digits=5,
                        verbose_name="품질 목표 (%)",
                    ),
                ),
                (
                    "oee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="OEE (%)",
                    ),
                ),
                (
                    "oee_target",
                    models.DecimalField(
                        decimal_places=2,
                        default=85,
                        max_digits=5,
                        verbose_name="OEE 목표 (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "OEE 구성요소",
                "verbose_name_plural": "OEE 구성요소",
                "db_table": "productivity_oee_component",
                "ordering": ["-fiscal_year", "-fiscal_month", "-oee"],
            },
        ),
        migrations.CreateModel(
            name="ProductionEfficiency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                ("category", models.CharField(max_length=100, verbose_name="구분")),
                (
                    "target_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="목표값",
                    ),
                ),
                (
                    "actual_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="실적값",
                    ),
                ),
                (
                    "efficiency",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="효율 (%)",
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=50, verbose_name="단위"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "생산 효율",
                "verbose_name_plural": "생산 효율",
                "db_table": "productivity_efficiency",
                "ordering": ["-fiscal_year", "-fiscal_month", "category"],
            },
        ),
        migrations.CreateModel(
            name="WorkerProductivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "worker_id",
                    models.CharField(max_length=50, verbose_name="작업자 ID"),
                ),
                (
                    "worker_name",
                    models.CharField(max_length=100, verbose_name="작업자명"),
                ),
                ("department", models.CharField(max_length=100, verbose_name="부서")),
                (
                    "work_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="근무시간",
                    ),
                ),
                (
                    "output_quantity",
                    models.IntegerField(default=0, verbose_name="생산량"),
                ),
                (
                    "productivity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="생산성 (개/시간)",
                    ),
                ),
                (
                    "target_productivity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="목표 생산성",
                    ),
                ),
                (
                    "achievement_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="달성률 (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "작업자 생산성",
                "verbose_name_plural": "작업자 생산성",
                "db_table": "productivity_worker",
                "ordering": ["-fiscal_year", "-fiscal_month", "-productivity"],
            },
        ),
    ]
