# Generated by Django 5.0.1 on 2025-12-24 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CycleTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "process_name",
                    models.CharField(max_length=100, verbose_name="공정명"),
                ),
                (
                    "standard_time",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="표준 시간 (초)",
                    ),
                ),
                (
                    "actual_time",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="실제 시간 (초)",
                    ),
                ),
                (
                    "variance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="편차 (초)",
                    ),
                ),
                (
                    "variance_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="편차율 (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "사이클 타임",
                "verbose_name_plural": "사이클 타임",
                "db_table": "manufacturing_cycle_time",
                "ordering": ["-fiscal_year", "-fiscal_month", "process_name"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentDowntime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment_id",
                    models.CharField(max_length=50, verbose_name="설비 ID"),
                ),
                (
                    "equipment_name",
                    models.CharField(max_length=100, verbose_name="설비명"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("breakdown", "고장"),
                            ("maintenance", "정비"),
                            ("changeover", "품목교체"),
                            ("material", "자재대기"),
                            ("quality", "품질문제"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                        verbose_name="사유",
                    ),
                ),
                (
                    "downtime_minutes",
                    models.IntegerField(default=0, verbose_name="다운타임 (분)"),
                ),
                ("description", models.TextField(blank=True, verbose_name="상세 설명")),
                ("start_time", models.DateTimeField(verbose_name="시작 시간")),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="종료 시간"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "설비 다운타임",
                "verbose_name_plural": "설비 다운타임",
                "db_table": "manufacturing_equipment_downtime",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ManpowerAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workshop", models.CharField(max_length=100, verbose_name="작업장")),
                (
                    "shift",
                    models.CharField(
                        choices=[("day", "주간"), ("night", "야간"), ("swing", "교대")],
                        default="day",
                        max_length=10,
                        verbose_name="근무조",
                    ),
                ),
                (
                    "allocated_workers",
                    models.IntegerField(default=0, verbose_name="배정 인원"),
                ),
                (
                    "present_workers",
                    models.IntegerField(default=0, verbose_name="출근 인원"),
                ),
                (
                    "absent_workers",
                    models.IntegerField(default=0, verbose_name="결근 인원"),
                ),
                (
                    "overtime_workers",
                    models.IntegerField(default=0, verbose_name="잔업 인원"),
                ),
                (
                    "attendance_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="출근률 (%)",
                    ),
                ),
                ("date", models.DateField(verbose_name="날짜")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "인력 배치",
                "verbose_name_plural": "인력 배치",
                "db_table": "manufacturing_manpower_allocation",
                "ordering": ["-date", "workshop"],
            },
        ),
        migrations.CreateModel(
            name="OEEMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "equipment_id",
                    models.CharField(max_length=50, verbose_name="설비 ID"),
                ),
                (
                    "equipment_name",
                    models.CharField(max_length=100, verbose_name="설비명"),
                ),
                (
                    "availability",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="가동률 (%)",
                    ),
                ),
                (
                    "performance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="성능 (%)",
                    ),
                ),
                (
                    "quality",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="품질 (%)",
                    ),
                ),
                (
                    "oee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="OEE (%)",
                    ),
                ),
                (
                    "target_oee",
                    models.DecimalField(
                        decimal_places=2,
                        default=85,
                        max_digits=5,
                        verbose_name="목표 OEE (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "OEE 지표",
                "verbose_name_plural": "OEE 지표",
                "db_table": "manufacturing_oee_metric",
                "ordering": ["-fiscal_year", "-fiscal_month", "-oee"],
            },
        ),
        migrations.CreateModel(
            name="WorkshopStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workshop_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="작업장 ID"
                    ),
                ),
                (
                    "workshop_name",
                    models.CharField(max_length=100, verbose_name="작업장명"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "가동중"),
                            ("idle", "대기"),
                            ("maintenance", "정비중"),
                            ("stopped", "중지"),
                        ],
                        default="idle",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "current_product",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="현재 생산품"
                    ),
                ),
                (
                    "operator_count",
                    models.IntegerField(default=0, verbose_name="작업자 수"),
                ),
                (
                    "target_output",
                    models.IntegerField(default=0, verbose_name="목표 생산량"),
                ),
                (
                    "actual_output",
                    models.IntegerField(default=0, verbose_name="실제 생산량"),
                ),
                (
                    "efficiency",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="효율 (%)",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="최종 갱신"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
            ],
            options={
                "verbose_name": "작업장 현황",
                "verbose_name_plural": "작업장 현황",
                "db_table": "manufacturing_workshop_status",
                "ordering": ["workshop_id"],
            },
        ),
        migrations.CreateModel(
            name="WorkStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "standard_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="표준 ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("process", models.CharField(max_length=100, verbose_name="공정")),
                ("version", models.CharField(max_length=20, verbose_name="버전")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "적용중"),
                            ("draft", "초안"),
                            ("obsolete", "폐기"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "standard_time",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="표준 시간 (분)",
                    ),
                ),
                (
                    "required_skill_level",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="필요 숙련도"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "effective_date",
                    models.DateField(blank=True, null=True, verbose_name="시행일"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "작업 표준",
                "verbose_name_plural": "작업 표준",
                "db_table": "manufacturing_work_standard",
                "ordering": ["-updated_at"],
            },
        ),
    ]
