# Generated by Django 5.0.1 on 2025-12-25 01:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerComplaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complaint_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="클레임 번호"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=200, verbose_name="고객명"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="제품명"),
                ),
                (
                    "product_code",
                    models.CharField(max_length=100, verbose_name="제품 코드"),
                ),
                ("complaint_date", models.DateField(verbose_name="접수일자")),
                ("description", models.TextField(verbose_name="내용")),
                (
                    "severity",
                    models.CharField(
                        choices=[("high", "높음"), ("medium", "보통"), ("low", "낮음")],
                        max_length=20,
                        verbose_name="심각도",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "접수"),
                            ("investigating", "조사중"),
                            ("resolving", "개선중"),
                            ("resolved", "완료"),
                            ("closed", "종료"),
                        ],
                        default="received",
                        max_length=20,
                        verbose_name="처리 상태",
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(blank=True, max_length=100, verbose_name="담당자"),
                ),
                ("root_cause", models.TextField(blank=True, verbose_name="근본 원인")),
                (
                    "corrective_action",
                    models.TextField(blank=True, verbose_name="시정 조치"),
                ),
                (
                    "preventive_action",
                    models.TextField(blank=True, verbose_name="예방 조치"),
                ),
                (
                    "resolution_date",
                    models.DateField(blank=True, null=True, verbose_name="완료일자"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "고객 클레임",
                "verbose_name_plural": "고객 클레임",
                "db_table": "customer_complaints",
                "ordering": ["-complaint_date"],
            },
        ),
        migrations.CreateModel(
            name="DefectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="불량 유형")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="코드"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "치명적"),
                            ("major", "중대"),
                            ("minor", "경미"),
                        ],
                        max_length=20,
                        verbose_name="심각도",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "불량 유형",
                "verbose_name_plural": "불량 유형",
                "db_table": "defect_types",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ProcessCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="제품명"),
                ),
                (
                    "product_code",
                    models.CharField(max_length=100, verbose_name="제품 코드"),
                ),
                (
                    "process_name",
                    models.CharField(max_length=200, verbose_name="공정명"),
                ),
                ("measurement_date", models.DateField(verbose_name="측정일자")),
                (
                    "usl",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="상한 규격"
                    ),
                ),
                (
                    "lsl",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="하한 규격"
                    ),
                ),
                (
                    "target",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="목표값"
                    ),
                ),
                (
                    "mean",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="평균"
                    ),
                ),
                (
                    "std_dev",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="표준편차"
                    ),
                ),
                (
                    "cp",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="CP"
                    ),
                ),
                (
                    "cpk",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="CPK"
                    ),
                ),
                (
                    "ppk",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="PPK"
                    ),
                ),
                ("sample_size", models.IntegerField(verbose_name="샘플 수")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "공정 능력",
                "verbose_name_plural": "공정 능력",
                "db_table": "process_capabilities",
                "ordering": ["-measurement_date"],
            },
        ),
        migrations.CreateModel(
            name="QualityInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="검사 번호"
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("incoming", "수입 검사"),
                            ("in_process", "공정 검사"),
                            ("final", "최종 검사"),
                            ("outgoing", "출하 검사"),
                        ],
                        max_length=20,
                        verbose_name="검사 유형",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="제품명"),
                ),
                (
                    "product_code",
                    models.CharField(max_length=100, verbose_name="제품 코드"),
                ),
                (
                    "lot_number",
                    models.CharField(max_length=100, verbose_name="LOT 번호"),
                ),
                ("inspection_date", models.DateField(verbose_name="검사일자")),
                ("inspector", models.CharField(max_length=100, verbose_name="검사자")),
                (
                    "sample_size",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="샘플 수량",
                    ),
                ),
                (
                    "defect_count",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="불량 수량",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pass", "합격"),
                            ("fail", "불합격"),
                            ("conditional", "조건부 합격"),
                        ],
                        max_length=20,
                        verbose_name="검사 결과",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "품질 검사",
                "verbose_name_plural": "품질 검사",
                "db_table": "quality_inspections",
                "ordering": ["-inspection_date"],
            },
        ),
        migrations.CreateModel(
            name="DefectRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="불량 수량",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="발생 위치"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="상세 설명")),
                (
                    "corrective_action",
                    models.TextField(blank=True, verbose_name="시정 조치"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "defect_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="quality.defecttype",
                        verbose_name="불량 유형",
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defect_records",
                        to="quality.qualityinspection",
                        verbose_name="품질 검사",
                    ),
                ),
            ],
            options={
                "verbose_name": "불량 기록",
                "verbose_name_plural": "불량 기록",
                "db_table": "defect_records",
                "ordering": ["-created_at"],
            },
        ),
    ]
