# Generated by Django 5.0.1 on 2026-02-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FactQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_date",
                    models.DateField(db_index=True, verbose_name="검사일자"),
                ),
                (
                    "inspection_type",
                    models.CharField(max_length=20, verbose_name="검사구분"),
                ),
                (
                    "product_id",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="제품코드"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="제품명"),
                ),
                (
                    "lot_no",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="LOT번호"
                    ),
                ),
                (
                    "qty_inspected",
                    models.IntegerField(default=0, verbose_name="검사수량"),
                ),
                ("qty_passed", models.IntegerField(default=0, verbose_name="합격수량")),
                (
                    "qty_failed",
                    models.IntegerField(default=0, verbose_name="불합격수량"),
                ),
                (
                    "qty_rework",
                    models.IntegerField(default=0, verbose_name="재작업수량"),
                ),
                (
                    "defect_type",
                    models.CharField(max_length=50, null=True, verbose_name="불량유형"),
                ),
                (
                    "defect_cause",
                    models.CharField(max_length=50, null=True, verbose_name="불량원인"),
                ),
                (
                    "defect_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="불량률(%)",
                    ),
                ),
                (
                    "measured_value",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="측정값",
                    ),
                ),
                (
                    "spec_lower",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="하한규격",
                    ),
                ),
                (
                    "spec_upper",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="상한규격",
                    ),
                ),
                (
                    "inspector",
                    models.CharField(max_length=50, null=True, verbose_name="검사자"),
                ),
                (
                    "source_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="원천ID"
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(auto_now=True, verbose_name="동기화시각"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "품질검사",
                "verbose_name_plural": "품질검사",
                "db_table": "fact_quality",
                "ordering": ["-inspection_date"],
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["inspection_date", "inspection_type"],
                        name="fact_qualit_inspect_d593b9_idx",
                    ),
                    models.Index(
                        fields=["product_id"], name="fact_qualit_product_f020e5_idx"
                    ),
                    models.Index(
                        fields=["lot_no"], name="fact_qualit_lot_no_9f78ee_idx"
                    ),
                ],
            },
        ),
    ]
