# Generated by Django 4.2.7 on 2026-03-30 07:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "request_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="요청 ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                (
                    "requested_by",
                    models.CharField(max_length=100, verbose_name="요청자"),
                ),
                (
                    "approval_level",
                    models.IntegerField(
                        choices=[
                            (1, "L1"),
                            (2, "L2"),
                            (3, "L3"),
                            (4, "L4"),
                            (5, "L5"),
                            (6, "L6"),
                        ],
                        verbose_name="승인 레벨",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("approved", "승인"),
                            ("rejected", "거부"),
                            ("cancelled", "취소"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "current_approver",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="현재 승인자"
                    ),
                ),
                (
                    "business_impact",
                    models.CharField(
                        choices=[
                            ("low", "낮음"),
                            ("medium", "보통"),
                            ("high", "높음"),
                            ("critical", "긴급"),
                        ],
                        max_length=20,
                        verbose_name="업무 영향도",
                    ),
                ),
                (
                    "approval_history",
                    models.JSONField(default=list, verbose_name="승인 내역"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="거부 사유"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="승인 시각"
                    ),
                ),
            ],
            options={
                "verbose_name": "승인 요청",
                "verbose_name_plural": "승인 요청",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalWorkflow",
            fields=[
                (
                    "workflow_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="워크플로우 ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="코드"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="명칭")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("category", models.CharField(max_length=50, verbose_name="카테고리")),
                (
                    "approval_levels",
                    models.JSONField(default=list, verbose_name="승인 단계"),
                ),
                ("conditions", models.JSONField(default=dict, verbose_name="조건")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "승인 워크플로우",
                "verbose_name_plural": "승인 워크플로우",
                "ordering": ["category", "code"],
            },
        ),
        migrations.CreateModel(
            name="PolicyRule",
            fields=[
                (
                    "rule_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="규칙 ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="규칙 코드"
                    ),
                ),
                ("name_ko", models.CharField(max_length=100, verbose_name="한글명")),
                (
                    "name_en",
                    models.CharField(blank=True, max_length=100, verbose_name="영문명"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("compliance", "준수"),
                            ("security", "보안"),
                            ("quality", "품질"),
                            ("safety", "안전"),
                            ("financial", "재무"),
                            ("operational", "운영"),
                        ],
                        max_length=50,
                        verbose_name="카테고리",
                    ),
                ),
                ("description", models.TextField(verbose_name="설명")),
                ("conditions", models.JSONField(default=list, verbose_name="조건")),
                ("actions", models.JSONField(default=list, verbose_name="액션")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "정보"),
                            ("LOW", "낮음"),
                            ("MEDIUM", "보통"),
                            ("HIGH", "높음"),
                            ("CRITICAL", "긴급"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="심각도",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성여부"),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="메타데이터")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "정책 규칙",
                "verbose_name_plural": "정책 규칙",
                "ordering": ["category", "code"],
            },
        ),
        migrations.CreateModel(
            name="PolicyViolation",
            fields=[
                (
                    "violation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="위반 ID",
                    ),
                ),
                (
                    "violating_entity",
                    models.CharField(max_length=200, verbose_name="위반 주체"),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("user", "사용자"),
                            ("agent", "에이전트"),
                            ("system", "시스템"),
                            ("process", "프로세스"),
                        ],
                        max_length=50,
                        verbose_name="주체 유형",
                    ),
                ),
                (
                    "violation_details",
                    models.JSONField(default=dict, verbose_name="위반 상세"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "정보"),
                            ("LOW", "낮음"),
                            ("MEDIUM", "보통"),
                            ("HIGH", "높음"),
                            ("CRITICAL", "긴급"),
                        ],
                        max_length=20,
                        verbose_name="심각도",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "발생"),
                            ("investigating", "조사중"),
                            ("resolved", "해결"),
                            ("dismissed", "무시"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("resolution", models.TextField(blank=True, verbose_name="해결 방안")),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="해결 시각"
                    ),
                ),
                (
                    "resolved_by",
                    models.CharField(blank=True, max_length=100, verbose_name="해결자"),
                ),
                (
                    "detected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="탐지 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "policy_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="governance.policyrule",
                        verbose_name="정책 규칙",
                    ),
                ),
            ],
            options={
                "verbose_name": "정책 위반",
                "verbose_name_plural": "정책 위반",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.AddIndex(
            model_name="policyrule",
            index=models.Index(
                fields=["category", "is_active"], name="governance__categor_d50dcd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policyrule",
            index=models.Index(fields=["code"], name="governance__code_ea51b2_idx"),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="recommendation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_requests",
                to="ai.recommendation",
                verbose_name="관련 추천",
            ),
        ),
        migrations.AddIndex(
            model_name="policyviolation",
            index=models.Index(
                fields=["policy_rule", "status"], name="governance__policy__c69a6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policyviolation",
            index=models.Index(
                fields=["severity", "status"], name="governance__severit_0200e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["status", "approval_level"],
                name="governance__status_a370b9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["requested_by", "status"], name="governance__request_fb999a_idx"
            ),
        ),
    ]
