# Generated by Django 5.0.1 on 2026-02-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FactCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost_month", models.DateField(db_index=True, verbose_name="원가월")),
                (
                    "product_id",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="제품코드"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="제품명"),
                ),
                (
                    "cost_center",
                    models.CharField(max_length=20, null=True, verbose_name="원가부문"),
                ),
                (
                    "material_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="재료비",
                    ),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="노무비",
                    ),
                ),
                (
                    "overhead_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18, verbose_name="경비"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="단위원가"
                    ),
                ),
                (
                    "standard_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="표준원가",
                    ),
                ),
                (
                    "variance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="원가차이",
                    ),
                ),
                (
                    "variance_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="차이율(%)",
                    ),
                ),
                ("output_qty", models.IntegerField(default=0, verbose_name="생산수량")),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="총원가"
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="원천ID"
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(auto_now=True, verbose_name="동기화시각"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "원가",
                "verbose_name_plural": "원가",
                "db_table": "fact_cost",
                "ordering": ["-cost_month", "product_id"],
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["cost_month"], name="fact_cost_cost_mo_2f5585_idx"
                    ),
                    models.Index(
                        fields=["product_id"], name="fact_cost_product_d98db7_idx"
                    ),
                ],
            },
        ),
    ]
