# Generated by Django 4.2.7 on 2026-03-31 08:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="실험명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("parameters", models.JSONField(default=dict, verbose_name="파라미터")),
                ("metrics", models.JSONField(default=dict, verbose_name="지표")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "실행 중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("artifacts", models.JSONField(default=dict, verbose_name="아티팩트")),
                ("logs", models.TextField(blank=True, verbose_name="로그")),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="시작일"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="완료일"),
                ),
            ],
            options={
                "verbose_name": "ML 실험",
                "verbose_name_plural": "ML 실험",
                "db_table": "ml_experiment",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="FeatureStore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="피쳐명"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=200, verbose_name="표시명"),
                ),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("numerical", "수치형"),
                            ("categorical", "범주형"),
                            ("text", "텍스트"),
                            ("datetime", "날짜시간"),
                            ("boolean", "불린"),
                        ],
                        max_length=20,
                        verbose_name="피쳐 유형",
                    ),
                ),
                (
                    "source_table",
                    models.CharField(max_length=100, verbose_name="소스 테이블"),
                ),
                (
                    "source_column",
                    models.CharField(max_length=100, verbose_name="소스 컬럼"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "data_type",
                    models.CharField(max_length=50, verbose_name="데이터 타입"),
                ),
                (
                    "statistics",
                    models.JSONField(default=dict, verbose_name="통계 정보"),
                ),
                (
                    "transformation",
                    models.JSONField(default=dict, verbose_name="변환 방법"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "피쳐 저장소",
                "verbose_name_plural": "피쳐 저장소",
                "db_table": "ml_feature_store",
            },
        ),
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="모델명")),
                (
                    "code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="모델 코드"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", max_length=50, verbose_name="버전"
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("regression", "회귀"),
                            ("classification", "분류"),
                            ("time_series", "시계열"),
                            ("clustering", "클러스터링"),
                            ("anomaly_detection", "이상탐지"),
                            ("forecasting", "예측"),
                        ],
                        max_length=50,
                        verbose_name="모델 유형",
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(max_length=100, verbose_name="알고리즘"),
                ),
                (
                    "target_feature",
                    models.CharField(max_length=100, verbose_name="타겟 피쳐"),
                ),
                ("features", models.JSONField(default=list, verbose_name="피쳐 목록")),
                (
                    "model_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ml_models/",
                        verbose_name="모델 파일",
                    ),
                ),
                (
                    "hyperparameters",
                    models.JSONField(default=dict, verbose_name="하이퍼파라미터"),
                ),
                ("metrics", models.JSONField(default=dict, verbose_name="성능 지표")),
                (
                    "trained_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="학습일"),
                ),
                (
                    "training_samples",
                    models.IntegerField(default=0, verbose_name="학습 데이터 수"),
                ),
                (
                    "training_time_ms",
                    models.IntegerField(default=0, verbose_name="학습 시간(ms)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("training", "학습 중"),
                            ("trained", "학습 완료"),
                            ("deployed", "배포됨"),
                            ("failed", "실패"),
                            ("archived", "보관됨"),
                        ],
                        default="training",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="에러 메시지"),
                ),
                (
                    "is_deployed",
                    models.BooleanField(default=False, verbose_name="배포 여부"),
                ),
                (
                    "deployed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="배포일"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "created_by",
                    models.CharField(blank=True, max_length=100, verbose_name="생성자"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "ML 모델",
                "verbose_name_plural": "ML 모델",
                "db_table": "ml_model",
            },
        ),
        migrations.CreateModel(
            name="TrainingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("job_name", models.CharField(max_length=200, verbose_name="작업명")),
                ("job_type", models.CharField(max_length=50, verbose_name="작업 유형")),
                (
                    "parameters",
                    models.JSONField(default=dict, verbose_name="학습 파라미터"),
                ),
                (
                    "data_source",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="데이터 소스"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("running", "실행 중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                            ("cancelled", "취소됨"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="진행률(%)")),
                (
                    "current_step",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="현재 단계"
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="결과"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="에러 메시지"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="시작일"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="완료일"),
                ),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="실행 시간(ms)"
                    ),
                ),
                (
                    "cpu_usage",
                    models.FloatField(
                        blank=True, null=True, verbose_name="CPU 사용률(%)"
                    ),
                ),
                (
                    "memory_usage_mb",
                    models.FloatField(
                        blank=True, null=True, verbose_name="메모리 사용량(MB)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_jobs",
                        to="ml_pipeline.mlmodel",
                        verbose_name="ML 모델",
                    ),
                ),
            ],
            options={
                "verbose_name": "학습 작업",
                "verbose_name_plural": "학습 작업",
                "db_table": "ml_training_job",
            },
        ),
        migrations.CreateModel(
            name="PredictionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="요청 ID"
                    ),
                ),
                ("input_data", models.JSONField(verbose_name="입력 데이터")),
                (
                    "prediction_result",
                    models.JSONField(default=dict, verbose_name="예측 결과"),
                ),
                (
                    "inference_time_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="추론 시간(ms)"
                    ),
                ),
                (
                    "requested_by",
                    models.CharField(blank=True, max_length=100, verbose_name="요청자"),
                ),
                (
                    "request_source",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="요청 소스"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="ml_pipeline.mlmodel",
                        verbose_name="ML 모델",
                    ),
                ),
            ],
            options={
                "verbose_name": "예측 요청",
                "verbose_name_plural": "예측 요청",
                "db_table": "ml_prediction_request",
            },
        ),
        migrations.AddIndex(
            model_name="mlmodel",
            index=models.Index(
                fields=["model_type", "status"], name="ml_model_model_t_7cfbe1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mlmodel",
            index=models.Index(
                fields=["code", "version"], name="ml_model_code_a6ca65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mlmodel",
            index=models.Index(
                fields=["is_deployed"], name="ml_model_is_depl_340eff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="featurestore",
            index=models.Index(fields=["name"], name="ml_feature__name_7be4f6_idx"),
        ),
        migrations.AddIndex(
            model_name="featurestore",
            index=models.Index(
                fields=["feature_type"], name="ml_feature__feature_f8fa67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="featurestore",
            index=models.Index(
                fields=["source_table"], name="ml_feature__source__aa6bc8_idx"
            ),
        ),
        migrations.AddField(
            model_name="experiment",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiments",
                to="ml_pipeline.mlmodel",
                verbose_name="ML 모델",
            ),
        ),
        migrations.AddIndex(
            model_name="trainingjob",
            index=models.Index(
                fields=["status", "-created_at"], name="ml_training_status_f1a04b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingjob",
            index=models.Index(
                fields=["model", "-created_at"], name="ml_training_model_i_47bb04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="predictionrequest",
            index=models.Index(
                fields=["model", "-created_at"], name="ml_predicti_model_i_d81dea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="predictionrequest",
            index=models.Index(
                fields=["request_id"], name="ml_predicti_request_a215a6_idx"
            ),
        ),
    ]
