# Generated by Django 4.2.7 on 2026-03-30 07:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentMemory",
            fields=[
                (
                    "memory_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="메모리 ID",
                    ),
                ),
                (
                    "memory_type",
                    models.CharField(
                        choices=[
                            ("pattern", "패턴"),
                            ("context", "컨텍스트"),
                            ("preference", "선호"),
                            ("exception", "예외"),
                        ],
                        default="pattern",
                        max_length=30,
                        verbose_name="유형",
                    ),
                ),
                (
                    "domain",
                    models.CharField(blank=True, max_length=30, verbose_name="도메인"),
                ),
                (
                    "key",
                    models.CharField(db_index=True, max_length=200, verbose_name="키"),
                ),
                ("value", models.JSONField(verbose_name="값")),
                ("frequency", models.IntegerField(default=1, verbose_name="출현 빈도")),
                ("importance", models.FloatField(default=1.0, verbose_name="중요도")),
                (
                    "last_used",
                    models.DateTimeField(auto_now=True, verbose_name="마지막 사용"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
            ],
            options={
                "verbose_name": "Agent 메모리",
                "verbose_name_plural": "Agent 메모리",
                "ordering": ["-last_used"],
            },
        ),
        migrations.CreateModel(
            name="AgentRunLog",
            fields=[
                (
                    "request_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="요청 ID",
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Agent명"
                    ),
                ),
                (
                    "agent_version",
                    models.CharField(blank=True, max_length=20, verbose_name="버전"),
                ),
                (
                    "agent_layer",
                    models.CharField(blank=True, max_length=30, verbose_name="계층"),
                ),
                (
                    "agent_domain",
                    models.CharField(blank=True, max_length=30, verbose_name="도메인"),
                ),
                ("input_data", models.JSONField(default=dict, verbose_name="입력")),
                ("output_data", models.JSONField(default=dict, verbose_name="출력")),
                ("status", models.CharField(max_length=20, verbose_name="상태")),
                ("confidence", models.FloatField(default=0.0, verbose_name="신뢰도")),
                (
                    "execution_time_ms",
                    models.IntegerField(default=0, verbose_name="실행시간(ms)"),
                ),
                (
                    "has_evidence",
                    models.BooleanField(default=False, verbose_name="근거 포함"),
                ),
                (
                    "evaluated",
                    models.BooleanField(default=False, verbose_name="평가 완료"),
                ),
                (
                    "evaluation_score",
                    models.FloatField(blank=True, null=True, verbose_name="평가 점수"),
                ),
                (
                    "evaluation_note",
                    models.TextField(blank=True, verbose_name="평가 노트"),
                ),
                (
                    "parent_run_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="상위 실행 ID"
                    ),
                ),
                (
                    "triggered_event_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="연관 이벤트 ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="생성일시"
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent 실행 로그",
                "verbose_name_plural": "Agent 실행 로그",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisPlan",
            fields=[
                (
                    "plan_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="계획 ID",
                    ),
                ),
                ("request_id", models.UUIDField(db_index=True, verbose_name="요청 ID")),
                (
                    "plan_type",
                    models.CharField(max_length=30, verbose_name="계획 유형"),
                ),
                ("description", models.TextField(verbose_name="설명")),
                ("steps", models.JSONField(default=list, verbose_name="실행 단계")),
                (
                    "status",
                    models.CharField(
                        default="planned", max_length=20, verbose_name="상태"
                    ),
                ),
                (
                    "completed_steps",
                    models.IntegerField(default=0, verbose_name="완료 단계"),
                ),
                (
                    "total_steps",
                    models.IntegerField(default=0, verbose_name="전체 단계"),
                ),
                (
                    "agent_run_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="Agent 실행 ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "분석 계획",
                "verbose_name_plural": "분석 계획",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "doc_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="문서 ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                (
                    "content_type",
                    models.CharField(max_length=50, verbose_name="콘텐츠 유형"),
                ),
                (
                    "source_uri",
                    models.CharField(max_length=500, verbose_name="출처 URI"),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="출처 유형"
                    ),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="메타데이터")),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="처리 완료"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "RAG 문서",
                "verbose_name_plural": "RAG 문서",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReflectionLog",
            fields=[
                (
                    "reflection_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="리플렉션 ID",
                    ),
                ),
                (
                    "reflection_type",
                    models.CharField(
                        choices=[
                            ("outcome", "결과"),
                            ("process", "프로세스"),
                            ("strategy", "전략"),
                        ],
                        default="outcome",
                        max_length=50,
                        verbose_name="반성 유형",
                    ),
                ),
                (
                    "what_went_well",
                    models.TextField(blank=True, verbose_name="잘된 점"),
                ),
                (
                    "what_went_wrong",
                    models.TextField(blank=True, verbose_name="잘못된 점"),
                ),
                (
                    "lessons_learned",
                    models.TextField(blank=True, verbose_name="학습 포인트"),
                ),
                (
                    "improvement_suggestions",
                    models.JSONField(default=list, verbose_name="개선 제안"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "agent_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reflections",
                        to="ai.agentrunlog",
                        verbose_name="Agent 실행",
                    ),
                ),
            ],
            options={
                "verbose_name": "리플렉션 로그",
                "verbose_name_plural": "리플렉션 로그",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "recommendation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="권고 ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                (
                    "domain",
                    models.CharField(blank=True, max_length=30, verbose_name="도메인"),
                ),
                (
                    "process_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="프로세스"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("urgent", "긴급"),
                            ("high", "높음"),
                            ("medium", "보통"),
                            ("low", "낮음"),
                        ],
                        max_length=20,
                        verbose_name="우선순위",
                    ),
                ),
                (
                    "impact_area",
                    models.CharField(max_length=50, verbose_name="영향 영역"),
                ),
                (
                    "related_events",
                    models.JSONField(default=list, verbose_name="관련 이벤트"),
                ),
                (
                    "related_kpis",
                    models.JSONField(default=list, verbose_name="관련 KPI"),
                ),
                (
                    "evidence_refs",
                    models.JSONField(default=list, verbose_name="근거 참조"),
                ),
                (
                    "estimated_impact",
                    models.JSONField(default=dict, verbose_name="예상 효과"),
                ),
                (
                    "action_items",
                    models.JSONField(default=list, verbose_name="액션 항목"),
                ),
                (
                    "approval_level",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="승인 레벨"
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="승인 여부"
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=100, verbose_name="승인자"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="승인일시"
                    ),
                ),
                (
                    "adopted",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="채택 여부"
                    ),
                ),
                (
                    "adoption_feedback",
                    models.TextField(blank=True, verbose_name="채택 피드백"),
                ),
                (
                    "measured_improvement",
                    models.JSONField(blank=True, null=True, verbose_name="측정된 개선"),
                ),
                (
                    "generated_by_agent",
                    models.CharField(max_length=100, verbose_name="생성 Agent"),
                ),
                (
                    "agent_run_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="Agent 실행 ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="만료 시각"
                    ),
                ),
            ],
            options={
                "verbose_name": "권고안",
                "verbose_name_plural": "권고안",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["domain", "priority"],
                        name="ai_recommen_domain_8194f1_idx",
                    ),
                    models.Index(
                        fields=["approved", "adopted"],
                        name="ai_recommen_approve_a35a74_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "chunk_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="청크 ID",
                    ),
                ),
                ("chunk_index", models.IntegerField(verbose_name="청크 인덱스")),
                ("text", models.TextField(verbose_name="텍스트")),
                (
                    "embedding",
                    models.JSONField(blank=True, null=True, verbose_name="임베딩 벡터"),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="메타데이터")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="ai.document",
                        verbose_name="문서",
                    ),
                ),
            ],
            options={
                "verbose_name": "문서 청크",
                "verbose_name_plural": "문서 청크",
                "ordering": ["document", "chunk_index"],
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["content_type", "is_processed"],
                name="ai_document_content_03a161_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentrunlog",
            index=models.Index(
                fields=["agent_name", "status"], name="ai_agentrun_agent_n_f82548_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrunlog",
            index=models.Index(
                fields=["parent_run_id"], name="ai_agentrun_parent__c44c5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrunlog",
            index=models.Index(
                fields=["agent_domain", "created_at"],
                name="ai_agentrun_agent_d_5c6036_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentmemory",
            index=models.Index(
                fields=["memory_type", "is_active"],
                name="ai_agentmem_memory__6ca024_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentmemory",
            index=models.Index(
                fields=["domain", "importance"], name="ai_agentmem_domain_6948fd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agentmemory",
            unique_together={("memory_type", "key")},
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["document", "chunk_index"],
                name="ai_document_documen_798eb2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentchunk",
            unique_together={("document", "chunk_index")},
        ),
    ]
