# Generated by Django 4.2.7 on 2026-03-31 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="O2COrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=50, unique=True)),
                ("customer", models.CharField(max_length=200)),
                ("product", models.CharField(max_length=200)),
                ("quantity", models.IntegerField()),
                ("amount", models.BigIntegerField(help_text="주문 금액 (원)")),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("order_entry", "주문 접수"),
                            ("production", "생산"),
                            ("delivery", "배송"),
                            ("billing", "청구"),
                            ("payment", "입금"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("in_progress", "진행중"),
                            ("completed", "완료"),
                            ("delayed", "지연"),
                            ("cancelled", "취소"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order_date", models.DateField()),
                ("promised_date", models.DateField()),
                ("actual_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "O2C 주문",
                "verbose_name_plural": "O2C 주문",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="P2POrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=50, unique=True)),
                ("supplier", models.CharField(max_length=200)),
                ("material", models.CharField(max_length=200)),
                ("quantity", models.IntegerField()),
                ("amount", models.BigIntegerField(help_text="발주 금액 (원)")),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("requisition", "구매 요청"),
                            ("quotation", "견적"),
                            ("po_creation", "발주"),
                            ("receiving", "입고"),
                            ("invoice", "송장"),
                            ("payment", "지급"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("in_progress", "진행중"),
                            ("completed", "완료"),
                            ("delayed", "지연"),
                            ("cancelled", "취소"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order_date", models.DateField()),
                ("promised_date", models.DateField()),
                ("actual_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "P2P 발주",
                "verbose_name_plural": "P2P 발주",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="ProcessKPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process_type",
                    models.CharField(
                        choices=[("o2c", "O2C"), ("p2p", "P2P")], max_length=10
                    ),
                ),
                ("stage_id", models.CharField(max_length=50)),
                ("kpi_name", models.CharField(max_length=100)),
                ("kpi_code", models.CharField(max_length=50)),
                ("current_value", models.FloatField()),
                ("target_value", models.FloatField()),
                ("unit", models.CharField(max_length=20)),
                (
                    "trend",
                    models.CharField(
                        choices=[("up", "상승"), ("down", "하락"), ("stable", "안정")],
                        max_length=10,
                    ),
                ),
                ("period_type", models.CharField(default="monthly", max_length=20)),
                ("period_value", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "프로세스 KPI",
                "verbose_name_plural": "프로세스 KPI",
                "ordering": ["process_type", "stage_id", "kpi_code"],
                "unique_together": {
                    ("process_type", "stage_id", "kpi_code", "period_value")
                },
            },
        ),
        migrations.CreateModel(
            name="P2PStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_type", models.CharField(default="monthly", max_length=20)),
                (
                    "stage_id",
                    models.CharField(
                        choices=[
                            ("requisition", "구매 요청"),
                            ("quotation", "견적"),
                            ("po_creation", "발주"),
                            ("receiving", "입고"),
                            ("invoice", "송장"),
                            ("payment", "지급"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("in_progress", "진행중"),
                            ("completed", "완료"),
                            ("delayed", "지연"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField()),
                ("duration", models.IntegerField(help_text="소요 시간 (시간)")),
                (
                    "estimated_duration",
                    models.IntegerField(help_text="예상 시간 (시간)"),
                ),
                ("volume", models.IntegerField(help_text="처리 건수")),
                ("value", models.BigIntegerField(help_text="처리 금액 (원)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "P2P 스테이지",
                "verbose_name_plural": "P2P 스테이지",
                "ordering": ["period_type", "order"],
                "unique_together": {("period_type", "stage_id")},
            },
        ),
        migrations.CreateModel(
            name="P2PIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_id", models.CharField(max_length=50, unique=True)),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("delay", "지연"),
                            ("quality", "품질"),
                            ("cost", "비용"),
                            ("supplier", "공급업체"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "낮음"), ("medium", "중간"), ("high", "높음")],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("affected_orders", models.IntegerField(default=0)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="business_process.p2pstage",
                    ),
                ),
            ],
            options={
                "verbose_name": "P2P 이슈",
                "verbose_name_plural": "P2P 이슈",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="O2CStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_type", models.CharField(default="monthly", max_length=20)),
                (
                    "stage_id",
                    models.CharField(
                        choices=[
                            ("order_entry", "주문 접수"),
                            ("production", "생산"),
                            ("delivery", "배송"),
                            ("billing", "청구"),
                            ("payment", "입금"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("in_progress", "진행중"),
                            ("completed", "완료"),
                            ("delayed", "지연"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField()),
                ("duration", models.IntegerField(help_text="소요 시간 (시간)")),
                (
                    "estimated_duration",
                    models.IntegerField(help_text="예상 시간 (시간)"),
                ),
                ("volume", models.IntegerField(help_text="처리 건수")),
                ("value", models.BigIntegerField(help_text="처리 금액 (원)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "O2C 스테이지",
                "verbose_name_plural": "O2C 스테이지",
                "ordering": ["period_type", "order"],
                "unique_together": {("period_type", "stage_id")},
            },
        ),
        migrations.CreateModel(
            name="O2CIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_id", models.CharField(max_length=50, unique=True)),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("delay", "지연"),
                            ("quality", "품질"),
                            ("cost", "비용"),
                            ("capacity", "용량"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "낮음"), ("medium", "중간"), ("high", "높음")],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("affected_orders", models.IntegerField(default=0)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="business_process.o2cstage",
                    ),
                ),
            ],
            options={
                "verbose_name": "O2C 이슈",
                "verbose_name_plural": "O2C 이슈",
                "ordering": ["-created_at"],
            },
        ),
    ]
