# Generated by Django 4.2.7 on 2026-03-31 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CacheStatistics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "cache_key_pattern",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="캐시 키 패턴"
                    ),
                ),
                ("hits", models.IntegerField(default=0, verbose_name="히트 수")),
                ("misses", models.IntegerField(default=0, verbose_name="미스 수")),
                (
                    "avg_size_bytes",
                    models.FloatField(
                        blank=True, null=True, verbose_name="평균 크기(bytes)"
                    ),
                ),
                (
                    "total_size_bytes",
                    models.FloatField(
                        blank=True, null=True, verbose_name="전체 크기(bytes)"
                    ),
                ),
                (
                    "eviction_count",
                    models.IntegerField(default=0, verbose_name="제거 수"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="시간戳"
                    ),
                ),
            ],
            options={
                "verbose_name": "캐시 통계",
                "verbose_name_plural": "캐시 통계",
                "db_table": "cache_statistics",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SystemMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="메트릭명"
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("counter", "카운터"),
                            ("gauge", "게이지"),
                            ("histogram", "히스토그램"),
                            ("summary", "요약"),
                        ],
                        max_length=50,
                        verbose_name="메트릭 유형",
                    ),
                ),
                ("value", models.FloatField(verbose_name="값")),
                (
                    "unit",
                    models.CharField(blank=True, max_length=50, verbose_name="단위"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=dict, verbose_name="태그"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, verbose_name="시간戳"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
            ],
            options={
                "verbose_name": "시스템 메트릭",
                "verbose_name_plural": "시스템 메트릭",
                "db_table": "system_metric",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["metric_name", "-timestamp"],
                        name="system_metr_metric__5c182a_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="system_metr_timesta_344d52_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PerformanceLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "operation_name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="작업명"
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("api_call", "API 호출"),
                            ("db_query", "DB 쿼리"),
                            ("cache_operation", "캐시 작업"),
                            ("external_call", "외부 호출"),
                            ("background_task", "백그라운드 작업"),
                        ],
                        max_length=50,
                        verbose_name="작업 유형",
                    ),
                ),
                (
                    "duration_ms",
                    models.FloatField(db_index=True, verbose_name="소요 시간(ms)"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="메타데이터"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="시간戳",
                    ),
                ),
            ],
            options={
                "verbose_name": "성능 로그",
                "verbose_name_plural": "성능 로그",
                "db_table": "performance_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["operation_name", "-timestamp"],
                        name="performance_operati_4407db_idx",
                    ),
                    models.Index(
                        fields=["operation_type", "-timestamp"],
                        name="performance_operati_108c26_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="performance_timesta_0252e7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HealthCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="서비스명"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "정상"),
                            ("degraded", "성능 저하"),
                            ("unhealthy", "비정상"),
                        ],
                        default="healthy",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("database", "데이터베이스"),
                            ("cache", "캐시"),
                            ("external_api", "외부 API"),
                            ("disk_space", "디스크 공간"),
                            ("memory", "메모리"),
                            ("cpu", "CPU"),
                        ],
                        max_length=50,
                        verbose_name="체크 유형",
                    ),
                ),
                (
                    "response_time_ms",
                    models.FloatField(
                        blank=True, null=True, verbose_name="응답 시간(ms)"
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="상세 정보"
                    ),
                ),
                (
                    "last_check",
                    models.DateTimeField(auto_now=True, verbose_name="마지막 체크"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
            ],
            options={
                "verbose_name": "헬스 체크",
                "verbose_name_plural": "헬스 체크",
                "db_table": "health_check",
                "ordering": ["-last_check"],
                "indexes": [
                    models.Index(
                        fields=["service_name", "-last_check"],
                        name="health_chec_service_d61ac1_idx",
                    ),
                    models.Index(
                        fields=["status", "-last_check"],
                        name="health_chec_status_562c00_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="에러 유형"
                    ),
                ),
                ("error_message", models.TextField(verbose_name="에러 메시지")),
                ("stack_trace", models.TextField(verbose_name="스택 트레이스")),
                (
                    "request_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="요청 경로"
                    ),
                ),
                (
                    "request_method",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="요청 메서드"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 주소"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="해결 여부"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="해결 시간"
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="발생 시간",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_errors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="error_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "에러 로그",
                "verbose_name_plural": "에러 로그",
                "db_table": "error_log",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["error_type", "-occurred_at"],
                        name="error_log_error_t_03de24_idx",
                    ),
                    models.Index(
                        fields=["is_resolved", "-occurred_at"],
                        name="error_log_is_reso_f0f9fc_idx",
                    ),
                    models.Index(
                        fields=["-occurred_at"], name="error_log_occurre_a4c5f0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="APILog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("method", models.CharField(max_length=10, verbose_name="HTTP 메서드")),
                (
                    "path",
                    models.CharField(
                        db_index=True, max_length=500, verbose_name="요청 경로"
                    ),
                ),
                (
                    "query_params",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="쿼리 파라미터"
                    ),
                ),
                (
                    "request_body",
                    models.TextField(blank=True, verbose_name="요청 본문"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 주소"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "status_code",
                    models.IntegerField(db_index=True, verbose_name="상태 코드"),
                ),
                (
                    "response_time_ms",
                    models.FloatField(db_index=True, verbose_name="응답 시간(ms)"),
                ),
                (
                    "response_body",
                    models.TextField(blank=True, verbose_name="응답 본문"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="에러 메시지"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="시간戳",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "API 로그",
                "verbose_name_plural": "API 로그",
                "db_table": "api_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["path", "-timestamp"], name="api_log_path_b1cc09_idx"
                    ),
                    models.Index(
                        fields=["user", "-timestamp"], name="api_log_user_id_2047a0_idx"
                    ),
                    models.Index(
                        fields=["status_code", "-timestamp"],
                        name="api_log_status__910713_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="api_log_timesta_ccc989_idx"
                    ),
                ],
            },
        ),
    ]
