# Generated by Django 4.2.7 on 2026-03-31 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataLineage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_entity_type",
                    models.CharField(
                        choices=[
                            ("table", "Table"),
                            ("column", "Column"),
                            ("mart", "Mart"),
                            ("report", "Report"),
                        ],
                        max_length=20,
                        verbose_name="소스 엔티티 유형",
                    ),
                ),
                (
                    "source_entity",
                    models.CharField(max_length=255, verbose_name="소스 엔티티"),
                ),
                (
                    "target_entity_type",
                    models.CharField(
                        choices=[
                            ("table", "Table"),
                            ("column", "Column"),
                            ("mart", "Mart"),
                            ("report", "Report"),
                        ],
                        max_length=20,
                        verbose_name="타겟 엔티티 유형",
                    ),
                ),
                (
                    "target_entity",
                    models.CharField(max_length=255, verbose_name="타겟 엔티티"),
                ),
                (
                    "transformation",
                    models.TextField(blank=True, verbose_name="변환 설명"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
            ],
            options={
                "verbose_name": "데이터 계보",
                "verbose_name_plural": "데이터 계보들",
                "db_table": "data_hub_lineage",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataQualityRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="규칙명"
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("not_null", "Not Null"),
                            ("unique", "Unique"),
                            ("range", "Range"),
                            ("pattern", "Pattern"),
                            ("custom", "Custom"),
                            ("referential", "Referential"),
                            ("completeness", "Completeness"),
                        ],
                        max_length=20,
                        verbose_name="규칙 유형",
                    ),
                ),
                (
                    "target_table",
                    models.CharField(max_length=100, verbose_name="대상 테이블"),
                ),
                (
                    "target_column",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="대상 컬럼"
                    ),
                ),
                (
                    "rule_params",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="규칙 파라미터"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="심각도",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "error_message",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="에러 메시지"
                    ),
                ),
            ],
            options={
                "verbose_name": "데이터 품질 규칙",
                "verbose_name_plural": "데이터 품질 규칙들",
                "db_table": "data_hub_quality_rule",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="데이터 소스명"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("mssql", "MS SQL Server"),
                            ("postgresql", "PostgreSQL"),
                            ("api", "REST API"),
                            ("file", "File"),
                            ("oracle", "Oracle"),
                            ("mysql", "MySQL"),
                        ],
                        max_length=20,
                        verbose_name="소스 유형",
                    ),
                ),
                (
                    "connection_params",
                    models.JSONField(
                        help_text="호스트, 포트, 사용자, 비밀번호, 데이터베이스 등",
                        verbose_name="연결 파라미터",
                    ),
                ),
                (
                    "sync_schedule",
                    models.CharField(
                        choices=[
                            ("realtime", "Realtime (15min)"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("manual", "Manual"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="동기화 스케줄",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 여부"),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 동기화일시"
                    ),
                ),
                (
                    "last_sync_status",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="마지막 동기화 상태"
                    ),
                ),
                (
                    "last_sync_message",
                    models.TextField(blank=True, verbose_name="마지막 동기화 메시지"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "batch_size",
                    models.IntegerField(default=1000, verbose_name="배치 사이즈"),
                ),
                (
                    "timeout_seconds",
                    models.IntegerField(default=300, verbose_name="타임아웃(초)"),
                ),
                (
                    "retry_attempts",
                    models.IntegerField(default=3, verbose_name="재시도 횟수"),
                ),
            ],
            options={
                "verbose_name": "데이터 소스",
                "verbose_name_plural": "데이터 소스들",
                "db_table": "data_hub_data_source",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DataSyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="시작일시"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료일시"
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="소요 시간(초)"
                    ),
                ),
                (
                    "records_processed",
                    models.IntegerField(default=0, verbose_name="처리된 레코드 수"),
                ),
                (
                    "records_succeeded",
                    models.IntegerField(default=0, verbose_name="성공한 레코드 수"),
                ),
                (
                    "records_failed",
                    models.IntegerField(default=0, verbose_name="실패한 레코드 수"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="에러 메시지"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="메타데이터"
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        default="full",
                        help_text="full, incremental, realtime",
                        max_length=20,
                        verbose_name="동기화 타입",
                    ),
                ),
                (
                    "tables_synced",
                    models.JSONField(
                        blank=True, default=list, verbose_name="동기화된 테이블"
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="data_hub.datasource",
                        verbose_name="데이터 소스",
                    ),
                ),
            ],
            options={
                "verbose_name": "동기화 로그",
                "verbose_name_plural": "동기화 로그들",
                "db_table": "data_hub_sync_log",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DataQualityCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("warning", "Warning"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="검사일시"),
                ),
                (
                    "total_records",
                    models.IntegerField(default=0, verbose_name="전체 레코드 수"),
                ),
                (
                    "failed_records",
                    models.IntegerField(default=0, verbose_name="실패한 레코드 수"),
                ),
                ("failure_rate", models.FloatField(default=0.0, verbose_name="실패율")),
                (
                    "error_details",
                    models.JSONField(
                        blank=True, default=list, verbose_name="에러 상세"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="메타데이터"
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="data_hub.dataqualityrule",
                        verbose_name="품질 규칙",
                    ),
                ),
                (
                    "sync_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_checks",
                        to="data_hub.datasynclog",
                        verbose_name="동기화 로그",
                    ),
                ),
            ],
            options={
                "verbose_name": "데이터 품질 검사",
                "verbose_name_plural": "데이터 품질 검사들",
                "db_table": "data_hub_quality_check",
                "ordering": ["-checked_at"],
            },
        ),
        migrations.CreateModel(
            name="DataMart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="마트명"
                    ),
                ),
                (
                    "mart_type",
                    models.CharField(
                        choices=[
                            ("fact", "Fact Table"),
                            ("dimension", "Dimension Table"),
                            ("aggregate", "Aggregate Table"),
                            ("snapshot", "Snapshot Table"),
                        ],
                        max_length=20,
                        verbose_name="마트 유형",
                    ),
                ),
                (
                    "target_table",
                    models.CharField(max_length=100, verbose_name="대상 테이블명"),
                ),
                ("source_query", models.TextField(verbose_name="소스 쿼리")),
                (
                    "refresh_schedule",
                    models.CharField(
                        choices=[
                            ("realtime", "Realtime"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="갱신 스케줄",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("building", "Building"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 여부"),
                ),
                (
                    "last_refresh_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 갱신일시"
                    ),
                ),
                (
                    "last_refresh_status",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="마지막 갱신 상태"
                    ),
                ),
                ("row_count", models.IntegerField(default=0, verbose_name="행 수")),
                ("size_mb", models.FloatField(default=0.0, verbose_name="크기(MB)")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "business_domain",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="비즈니스 도메인"
                    ),
                ),
                (
                    "depends_on",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dependents",
                        to="data_hub.datamart",
                        verbose_name="의존 마트",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_marts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="소유자",
                    ),
                ),
            ],
            options={
                "verbose_name": "데이터 마트",
                "verbose_name_plural": "데이터 마트들",
                "db_table": "data_hub_mart",
                "ordering": ["name"],
            },
        ),
    ]
