# Generated by Django 4.2.7 on 2026-03-31 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="대화 제목"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 여부"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="메타데이터"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copilot_conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "대화 세션",
                "verbose_name_plural": "대화 세션들",
                "db_table": "copilot_conversation",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=10,
                        verbose_name="역할",
                    ),
                ),
                ("content", models.TextField(verbose_name="메시지 내용")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="메타데이터"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "agent_trace",
                    models.JSONField(
                        blank=True, default=list, verbose_name="에이전트 추적"
                    ),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="실행 시간(ms)"
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(blank=True, null=True, verbose_name="신뢰도"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="copilot.conversation",
                        verbose_name="대화 세션",
                    ),
                ),
            ],
            options={
                "verbose_name": "메시지",
                "verbose_name_plural": "메시지들",
                "db_table": "copilot_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CopilotSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "connected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="연결일시"),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(auto_now=True, verbose_name="마지막 활동일시"),
                ),
                (
                    "disconnected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="연결 종료일시"
                    ),
                ),
                (
                    "client_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="클라이언트 IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="copilot.conversation",
                        verbose_name="대화 세션",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copilot_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "Copilot 세션",
                "verbose_name_plural": "Copilot 세션들",
                "db_table": "copilot_session",
                "ordering": ["-last_activity_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Bad"),
                            (2, "Bad"),
                            (3, "Neutral"),
                            (4, "Good"),
                            (5, "Very Good"),
                        ],
                        verbose_name="평점",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="코멘트")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        blank=True,
                        help_text="accuracy, relevance, helpfulness 등",
                        max_length=50,
                        verbose_name="피드백 유형",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="copilot.conversation",
                        verbose_name="대화 세션",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="copilot.message",
                        verbose_name="메시지",
                    ),
                ),
            ],
            options={
                "verbose_name": "피드백",
                "verbose_name_plural": "피드백들",
                "db_table": "copilot_feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(blank=True, max_length=50, verbose_name="도메인"),
                ),
                (
                    "query_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="쿼리 타입"
                    ),
                ),
                (
                    "intent",
                    models.CharField(blank=True, max_length=50, verbose_name="의도"),
                ),
                (
                    "entities",
                    models.JSONField(blank=True, default=dict, verbose_name="엔티티"),
                ),
                (
                    "parameters",
                    models.JSONField(blank=True, default=dict, verbose_name="파라미터"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="대화 요약")),
                (
                    "related_events",
                    models.JSONField(
                        blank=True, default=list, verbose_name="관련 이벤트"
                    ),
                ),
                (
                    "related_kpis",
                    models.JSONField(blank=True, default=list, verbose_name="관련 KPI"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context",
                        to="copilot.conversation",
                        verbose_name="대화 세션",
                    ),
                ),
            ],
            options={
                "verbose_name": "대화 컨텍스트",
                "verbose_name_plural": "대화 컨텍스트들",
                "db_table": "copilot_conversation_context",
            },
        ),
    ]
