# Generated by Django 5.0.1 on 2026-02-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DimBOM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent_product",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="부모제품코드"
                    ),
                ),
                (
                    "child_product",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="자제품코드"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="소요량"
                    ),
                ),
                ("unit", models.CharField(max_length=10, verbose_name="단위")),
                ("level", models.IntegerField(default=1, verbose_name="레벨")),
                ("sequence", models.IntegerField(default=0, verbose_name="순서")),
                (
                    "is_substitute",
                    models.BooleanField(default=False, verbose_name="대체품여부"),
                ),
                (
                    "substitute_for",
                    models.CharField(max_length=50, null=True, verbose_name="대체대상"),
                ),
                ("valid_from", models.DateField(verbose_name="유효시작일")),
                ("valid_to", models.DateField(null=True, verbose_name="유효종료일")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="사용여부"),
                ),
                (
                    "source_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="원천ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "BOM",
                "verbose_name_plural": "BOM",
                "db_table": "dim_bom",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DimEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="설비코드",
                    ),
                ),
                (
                    "equipment_name",
                    models.CharField(max_length=200, verbose_name="설비명"),
                ),
                ("plant", models.CharField(max_length=10, verbose_name="공장")),
                (
                    "line",
                    models.CharField(max_length=20, null=True, verbose_name="라인"),
                ),
                (
                    "location",
                    models.CharField(
                        max_length=100, null=True, verbose_name="설치위치"
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(max_length=100, null=True, verbose_name="제조사"),
                ),
                (
                    "model",
                    models.CharField(max_length=100, null=True, verbose_name="모델명"),
                ),
                (
                    "capacity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="생산능력",
                    ),
                ),
                ("install_date", models.DateField(null=True, verbose_name="설치일자")),
                (
                    "acquisition_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="취득원가",
                    ),
                ),
                (
                    "depreciation_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="감가상각비",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="ACTIVE", max_length=20, verbose_name="상태"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "설비마스터",
                "verbose_name_plural": "설비마스터",
                "db_table": "dim_equipment",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DimProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="제품코드",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="제품명"),
                ),
                (
                    "product_name_en",
                    models.CharField(
                        max_length=200, null=True, verbose_name="제품명(영문)"
                    ),
                ),
                (
                    "category",
                    models.CharField(max_length=50, null=True, verbose_name="제품군"),
                ),
                (
                    "product_type",
                    models.CharField(max_length=20, null=True, verbose_name="제품유형"),
                ),
                (
                    "product_group",
                    models.CharField(max_length=50, null=True, verbose_name="제품그룹"),
                ),
                (
                    "specification",
                    models.CharField(max_length=200, null=True, verbose_name="규격"),
                ),
                ("unit", models.CharField(max_length=10, verbose_name="단위")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, null=True, verbose_name="중량"
                    ),
                ),
                (
                    "standard_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="표준원가",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="판매가",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="사용여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "제품마스터",
                "verbose_name_plural": "제품마스터",
                "db_table": "dim_product",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="FactEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_date",
                    models.DateField(db_index=True, verbose_name="가동일자"),
                ),
                (
                    "equipment_id",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="설비코드"
                    ),
                ),
                (
                    "equipment_name",
                    models.CharField(max_length=200, verbose_name="설비명"),
                ),
                ("plant", models.CharField(max_length=10, verbose_name="공장")),
                ("line", models.CharField(max_length=20, verbose_name="라인")),
                (
                    "planned_time",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="계획시간"
                    ),
                ),
                (
                    "actual_time",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="실가동시간"
                    ),
                ),
                (
                    "downtime",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="비가동시간"
                    ),
                ),
                (
                    "failure_count",
                    models.IntegerField(default=0, verbose_name="고장횟수"),
                ),
                (
                    "failure_time",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="고장시간",
                    ),
                ),
                ("output_qty", models.IntegerField(default=0, verbose_name="생산수량")),
                ("defect_qty", models.IntegerField(default=0, verbose_name="불량수량")),
                (
                    "availability",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="가동률(%)",
                    ),
                ),
                (
                    "performance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="성능률(%)",
                    ),
                ),
                (
                    "quality_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="품질률(%)",
                    ),
                ),
                (
                    "oee",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, null=True, verbose_name="OEE(%)"
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="원천ID"
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(auto_now=True, verbose_name="동기화시각"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "설비가동",
                "verbose_name_plural": "설비가동",
                "db_table": "fact_equipment",
                "ordering": ["-operation_date", "equipment_id"],
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["operation_date", "plant"],
                        name="fact_equipm_operati_75579e_idx",
                    ),
                    models.Index(
                        fields=["equipment_id"], name="fact_equipm_equipme_bbaacc_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FactProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField(db_index=True, verbose_name="작업일")),
                (
                    "plant",
                    models.CharField(db_index=True, max_length=10, verbose_name="공장"),
                ),
                ("line", models.CharField(max_length=20, verbose_name="라인")),
                (
                    "product_id",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="제품코드"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="제품명"),
                ),
                ("qty_plan", models.IntegerField(default=0, verbose_name="계획수량")),
                ("qty_actual", models.IntegerField(default=0, verbose_name="실적수량")),
                ("qty_bad", models.IntegerField(default=0, verbose_name="불량수량")),
                ("qty_good", models.IntegerField(default=0, verbose_name="양품수량")),
                (
                    "work_hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="작업시간",
                    ),
                ),
                (
                    "setup_time",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="준비시간",
                    ),
                ),
                (
                    "downtime",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="비가동시간",
                    ),
                ),
                (
                    "efficiency",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="효율(%)",
                    ),
                ),
                (
                    "uph",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="시간당생산량",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="원천ID"
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(auto_now=True, verbose_name="동기화시각"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "생산실적",
                "verbose_name_plural": "생산실적",
                "db_table": "fact_production",
                "ordering": ["-work_date", "plant"],
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["work_date", "plant"],
                        name="fact_produc_work_da_8dd6d4_idx",
                    ),
                    models.Index(
                        fields=["product_id"], name="fact_produc_product_2836e0_idx"
                    ),
                ],
            },
        ),
    ]
