# Generated by Django 4.2.7 on 2026-03-31 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RateLimitRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="식별자"
                    ),
                ),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[
                            ("ip", "IP 주소"),
                            ("user", "사용자"),
                            ("api_key", "API 키"),
                        ],
                        default="ip",
                        max_length=50,
                        verbose_name="식별자 유형",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="엔드포인트"
                    ),
                ),
                (
                    "request_count",
                    models.IntegerField(default=1, verbose_name="요청 수"),
                ),
                (
                    "window_start",
                    models.DateTimeField(db_index=True, verbose_name="윈도우 시작"),
                ),
                (
                    "blocked",
                    models.BooleanField(default=False, verbose_name="차단 여부"),
                ),
                (
                    "block_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="차단 해제 시간"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "속도 제한 기록",
                "verbose_name_plural": "속도 제한 기록",
                "db_table": "rate_limit_record",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["identifier", "endpoint", "-window_start"],
                        name="rate_limit__identif_f74358_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="rate_limit__created_5b1470_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="사용자명"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP 주소")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "was_successful",
                    models.BooleanField(default=False, verbose_name="성공 여부"),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="실패 사유"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="시간戳",
                    ),
                ),
            ],
            options={
                "verbose_name": "로그인 시도",
                "verbose_name_plural": "로그인 시도",
                "db_table": "login_attempt",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["username", "-timestamp"],
                        name="login_attem_usernam_769d7f_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-timestamp"],
                        name="login_attem_ip_addr_26064e_idx",
                    ),
                    models.Index(
                        fields=["was_successful", "-timestamp"],
                        name="login_attem_was_suc_96ff97_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_attempt", "로그인 시도"),
                            ("login_success", "로그인 성공"),
                            ("login_failure", "로그인 실패"),
                            ("logout", "로그아웃"),
                            ("permission_denied", "권한 거부"),
                            ("suspicious_activity", "의심스러운 활동"),
                            ("data_access", "데이터 접근"),
                            ("data_modification", "데이터 수정"),
                            ("rate_limit_exceeded", "속도 제한 초과"),
                            ("brute_force_detected", "무차별 대입 공격 감지"),
                        ],
                        db_index=True,
                        max_length=100,
                        verbose_name="이벤트 유형",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "낮음"),
                            ("medium", "중간"),
                            ("high", "높음"),
                            ("critical", "치명적"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="심각도",
                    ),
                ),
                ("description", models.TextField(verbose_name="설명")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 주소"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "request_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="요청 데이터"
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="해결 여부"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="해결 시간"
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="해결 노트"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="시간戳",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "보안 이벤트",
                "verbose_name_plural": "보안 이벤트",
                "db_table": "security_event",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "-timestamp"],
                        name="security_ev_event_t_9f4339_idx",
                    ),
                    models.Index(
                        fields=["severity", "-timestamp"],
                        name="security_ev_severit_5ee6e0_idx",
                    ),
                    models.Index(
                        fields=["is_resolved", "-timestamp"],
                        name="security_ev_is_reso_1c4cf1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="작업"
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("user", "사용자"),
                            ("system", "시스템"),
                            ("api", "API"),
                        ],
                        default="user",
                        max_length=50,
                        verbose_name="수행자 유형",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="대상 유형"
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="대상 ID"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 주소"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="변경 사항"
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(blank=True, default=dict, verbose_name="이전 값"),
                ),
                (
                    "new_values",
                    models.JSONField(blank=True, default=dict, verbose_name="새 값"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "성공"),
                            ("failed", "실패"),
                            ("partial", "부분 성공"),
                        ],
                        default="success",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="에러 메시지"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="시간戳",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="메타데이터"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="수행자",
                    ),
                ),
            ],
            options={
                "verbose_name": "감사 로그",
                "verbose_name_plural": "감사 로그",
                "db_table": "audit_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="audit_log_action_cf8063_idx",
                    ),
                    models.Index(
                        fields=["actor", "-timestamp"],
                        name="audit_log_actor_i_485cf7_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="audit_log_target__0238a6_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="audit_log_timesta_8b04a8_idx"
                    ),
                ],
            },
        ),
    ]
