# Generated by Django 5.0.1 on 2025-12-24 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BudgetActual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                ("category", models.CharField(max_length=100, verbose_name="구분")),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="예산 (억원)",
                    ),
                ),
                (
                    "actual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="실적 (억원)",
                    ),
                ),
                (
                    "variance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="차이 (억원)",
                    ),
                ),
                (
                    "variance_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="차이율 (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "예산 vs 실적",
                "verbose_name_plural": "예산 vs 실적",
                "db_table": "accounting_budget_actual",
                "ordering": ["-fiscal_year", "-fiscal_month", "category"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentProfitability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                ("department", models.CharField(max_length=100, verbose_name="부서")),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="매출 (억원)",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="비용 (억원)",
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="이익 (억원)",
                    ),
                ),
                (
                    "margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="수익률 (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "부서별 수익성",
                "verbose_name_plural": "부서별 수익성",
                "db_table": "accounting_department_profitability",
                "ordering": ["-fiscal_year", "-fiscal_month", "-profit"],
            },
        ),
        migrations.CreateModel(
            name="FinancialRatioAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                ("ratio_name", models.CharField(max_length=100, verbose_name="비율명")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("profitability", "수익성"),
                            ("stability", "안정성"),
                            ("activity", "활동성"),
                            ("growth", "성장성"),
                        ],
                        max_length=20,
                        verbose_name="분류",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="값 (%)",
                    ),
                ),
                (
                    "industry_avg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="업계평균 (%)",
                    ),
                ),
                (
                    "target",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="목표 (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "재무비율 분석",
                "verbose_name_plural": "재무비율 분석",
                "db_table": "accounting_financial_ratio",
                "ordering": ["-fiscal_year", "-fiscal_month", "category"],
            },
        ),
        migrations.CreateModel(
            name="InvestmentROI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(max_length=200, verbose_name="프로젝트명"),
                ),
                (
                    "investment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="투자금액 (억원)",
                    ),
                ),
                (
                    "expected_return",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="예상 수익 (억원)",
                    ),
                ),
                (
                    "actual_return",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="실제 수익 (억원)",
                    ),
                ),
                (
                    "roi",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ROI (%)",
                    ),
                ),
                (
                    "payback_period",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=5,
                        verbose_name="회수기간 (개월)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "계획"),
                            ("in-progress", "진행중"),
                            ("completed", "완료"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="시작일"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="종료일"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "투자 ROI",
                "verbose_name_plural": "투자 ROI",
                "db_table": "accounting_investment_roi",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KPIPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                ("kpi_name", models.CharField(max_length=200, verbose_name="KPI명")),
                (
                    "target",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="목표"
                    ),
                ),
                (
                    "actual",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="실적"
                    ),
                ),
                (
                    "achievement_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="달성률 (%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("achieved", "달성"),
                            ("on-track", "진행중"),
                            ("at-risk", "위험"),
                            ("missed", "미달"),
                        ],
                        default="on-track",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=50, verbose_name="단위"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "KPI 성과",
                "verbose_name_plural": "KPI 성과",
                "db_table": "accounting_kpi_performance",
                "ordering": ["-fiscal_year", "-fiscal_month", "-achievement_rate"],
            },
        ),
        migrations.CreateModel(
            name="BudgetAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                ("department", models.CharField(max_length=100, verbose_name="부서")),
                (
                    "allocated_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="배정 예산 (억원)",
                    ),
                ),
                (
                    "used_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="사용 예산 (억원)",
                    ),
                ),
                (
                    "remaining_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="잔여 예산 (억원)",
                    ),
                ),
                (
                    "usage_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="사용률 (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "예산 배분",
                "verbose_name_plural": "예산 배분",
                "db_table": "accounting_budget_allocation",
                "ordering": ["-fiscal_year", "-allocated_budget"],
                "unique_together": {("fiscal_year", "department")},
            },
        ),
    ]
