# Generated by Django 4.2.7 on 2026-03-31 08:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ForecastAccuracyLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("evaluation_start", models.DateField(verbose_name="평가 시작일")),
                ("evaluation_end", models.DateField(verbose_name="평가 종료일")),
                ("mae", models.FloatField(verbose_name="MAE")),
                ("mape", models.FloatField(verbose_name="MAPE")),
                ("rmse", models.FloatField(verbose_name="RMSE")),
                ("mase", models.FloatField(blank=True, null=True, verbose_name="MASE")),
                ("sample_size", models.IntegerField(verbose_name="표본 크기")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
            ],
            options={
                "verbose_name": "예측 정확도 로그",
                "verbose_name_plural": "예측 정확도 로그",
                "db_table": "forecast_accuracy_log",
            },
        ),
        migrations.CreateModel(
            name="ForecastModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="모델명")),
                (
                    "code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="모델 코드"
                    ),
                ),
                (
                    "target_metric",
                    models.CharField(max_length=100, verbose_name="타겟 지표"),
                ),
                (
                    "time_granularity",
                    models.CharField(
                        default="daily", max_length=20, verbose_name="시간 단위"
                    ),
                ),
                (
                    "forecast_type",
                    models.CharField(
                        choices=[
                            ("arima", "ARIMA"),
                            ("prophet", "Prophet"),
                            ("lstm", "LSTM"),
                            ("exponential_smoothing", "지수평활"),
                            ("theta", "Theta"),
                            ("ensemble", "앙상블"),
                        ],
                        max_length=50,
                        verbose_name="예측 유형",
                    ),
                ),
                (
                    "forecast_horizon",
                    models.IntegerField(default=30, verbose_name="예측 기간"),
                ),
                ("parameters", models.JSONField(default=dict, verbose_name="파라미터")),
                ("mae", models.FloatField(blank=True, null=True, verbose_name="MAE")),
                ("mape", models.FloatField(blank=True, null=True, verbose_name="MAPE")),
                ("rmse", models.FloatField(blank=True, null=True, verbose_name="RMSE")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("training", "학습 중"),
                            ("ready", "준비 완료"),
                            ("active", "활성"),
                            ("deprecated", "사용 안함"),
                        ],
                        default="training",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "last_trained",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 학습일"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "예측 모델",
                "verbose_name_plural": "예측 모델",
                "db_table": "forecast_model",
            },
        ),
        migrations.CreateModel(
            name="ForecastResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("forecast_date", models.DateTimeField(verbose_name="예측 생성일")),
                ("target_start", models.DateField(verbose_name="예측 시작일")),
                ("target_end", models.DateField(verbose_name="예측 종료일")),
                ("forecast_values", models.JSONField(verbose_name="예측값")),
                (
                    "confidence_level",
                    models.FloatField(default=0.95, verbose_name="신뢰 수준"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "forecast_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="forecasting.forecastmodel",
                        verbose_name="예측 모델",
                    ),
                ),
            ],
            options={
                "verbose_name": "예측 결과",
                "verbose_name_plural": "예측 결과",
                "db_table": "forecast_result",
            },
        ),
        migrations.AddIndex(
            model_name="forecastmodel",
            index=models.Index(fields=["code"], name="forecast_mo_code_21d945_idx"),
        ),
        migrations.AddIndex(
            model_name="forecastmodel",
            index=models.Index(
                fields=["target_metric", "status"],
                name="forecast_mo_target__82e333_idx",
            ),
        ),
        migrations.AddField(
            model_name="forecastaccuracylog",
            name="forecast_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accuracy_logs",
                to="forecasting.forecastmodel",
                verbose_name="예측 모델",
            ),
        ),
        migrations.AddIndex(
            model_name="forecastresult",
            index=models.Index(
                fields=["forecast_model", "-forecast_date"],
                name="forecast_re_forecas_1f3f82_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="forecastresult",
            index=models.Index(
                fields=["target_start", "target_end"],
                name="forecast_re_target__f04034_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="forecastaccuracylog",
            index=models.Index(
                fields=["forecast_model", "-created_at"],
                name="forecast_ac_forecas_99cf29_idx",
            ),
        ),
    ]
