# Generated by Django 5.2.13 on 2026-04-21 08:46

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventHub",
            fields=[
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="주제"
                    ),
                ),
                (
                    "event_key",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="이벤트 키"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=100, verbose_name="이벤트 유형"),
                ),
                (
                    "payload_json",
                    models.JSONField(default=dict, verbose_name="페이로드"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="생성 시간"
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="처리 여부"),
                ),
            ],
            options={
                "verbose_name": "이벤트 허브",
                "verbose_name_plural": "이벤트 허브",
                "db_table": "axos_event_hub",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertRecord",
            fields=[
                (
                    "alert_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="알림 유형"
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="제목")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "긴급"),
                            ("HIGH", "높음"),
                            ("MEDIUM", "중간"),
                            ("LOW", "낮음"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="심각도",
                    ),
                ),
                (
                    "source_object_type",
                    models.CharField(max_length=100, verbose_name="소스 객체 유형"),
                ),
                (
                    "source_object_id",
                    models.CharField(max_length=200, verbose_name="소스 객체 ID"),
                ),
                (
                    "dedup_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=200,
                        verbose_name="중복 방지 키",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "열림"),
                            ("ACKNOWLEDGED", "확인됨"),
                            ("RESOLVED", "해결됨"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "detail_json",
                    models.JSONField(default=dict, verbose_name="상세 정보"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="생성 시간"
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="확인 시간"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="해결 시간"
                    ),
                ),
            ],
            options={
                "verbose_name": "알림",
                "verbose_name_plural": "알림",
                "db_table": "axos_alert_records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["alert_type"], name="axos_alert__alert_t_31ea13_idx"
                    ),
                    models.Index(
                        fields=["severity"], name="axos_alert__severit_12f597_idx"
                    ),
                    models.Index(
                        fields=["status"], name="axos_alert__status_36ee6f_idx"
                    ),
                    models.Index(
                        fields=["dedup_key"], name="axos_alert__dedup_k_cf665b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ForecastRecord",
            fields=[
                (
                    "forecast_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="수익"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="비용"
                    ),
                ),
                (
                    "delay_penalty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="지연 벌금",
                    ),
                ),
                (
                    "rework_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="재작업 비용",
                    ),
                ),
                (
                    "forecast_margin",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="예상 마진"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("HIGH", "높음"), ("NORMAL", "정상")],
                        max_length=20,
                        verbose_name="리스크 레벨",
                    ),
                ),
                ("recommendation", models.TextField(verbose_name="권장사항")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="생성 시간"
                    ),
                ),
            ],
            options={
                "verbose_name": "포캐스팅 기록",
                "verbose_name_plural": "포캐스팅 기록",
                "db_table": "axos_forecast_records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["risk_level"], name="axos_foreca_risk_le_73d30e_idx"
                    ),
                    models.Index(
                        fields=["forecast_margin"],
                        name="axos_foreca_forecas_dd5cd0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProcessGraph",
            fields=[
                (
                    "graph_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "node_id",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="노드 ID"
                    ),
                ),
                (
                    "node_label",
                    models.CharField(max_length=500, verbose_name="노드 레이블"),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("product", "제품"),
                            ("material", "자재"),
                            ("equipment", "설비"),
                            ("process", "공정"),
                            ("quality", "품질"),
                            ("order", "주문"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="노드 유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "활성"),
                            ("inactive", "비활성"),
                            ("error", "오류"),
                            ("warning", "경고"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "metadata_json",
                    models.JSONField(default=dict, verbose_name="메타데이터"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시간"),
                ),
            ],
            options={
                "verbose_name": "프로세스 그래프",
                "verbose_name_plural": "프로세스 그래프",
                "db_table": "axos_process_graph",
                "ordering": ["node_id"],
                "indexes": [
                    models.Index(
                        fields=["node_type"], name="axos_proces_node_ty_e9651b_idx"
                    ),
                    models.Index(
                        fields=["status"], name="axos_proces_status_203e86_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProcessGraphEdge",
            fields=[
                (
                    "edge_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_node",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="소스 노드 ID"
                    ),
                ),
                (
                    "target_node",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="타겟 노드 ID"
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=200, verbose_name="레이블"),
                ),
                (
                    "edge_type",
                    models.CharField(
                        choices=[
                            ("flow", "흐름"),
                            ("dependency", "의존성"),
                            ("constraint", "제약"),
                        ],
                        default="flow",
                        max_length=50,
                        verbose_name="엣지 유형",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
            ],
            options={
                "verbose_name": "프로세스 그래프 엣지",
                "verbose_name_plural": "프로세스 그래프 엣지",
                "db_table": "axos_process_graph_edges",
                "ordering": ["source_node", "target_node"],
                "indexes": [
                    models.Index(
                        fields=["source_node", "target_node"],
                        name="axos_proces_source__7127cb_idx",
                    ),
                    models.Index(
                        fields=["edge_type"], name="axos_proces_edge_ty_6371b1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RiskScore",
            fields=[
                (
                    "risk_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="객체 유형"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="객체 ID"
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="리스크 점수",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("LOW", "낮음"), ("MEDIUM", "중간"), ("HIGH", "높음")],
                        max_length=20,
                        verbose_name="리스크 레벨",
                    ),
                ),
                (
                    "explanation_json",
                    models.JSONField(default=dict, verbose_name="설명"),
                ),
                ("features_json", models.JSONField(default=dict, verbose_name="특성")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="생성 시간"
                    ),
                ),
            ],
            options={
                "verbose_name": "리스크 점수",
                "verbose_name_plural": "리스크 점수",
                "db_table": "axos_risk_scores",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="axos_risk_s_object__c3f85b_idx",
                    ),
                    models.Index(fields=["level"], name="axos_risk_s_level_061893_idx"),
                    models.Index(fields=["score"], name="axos_risk_s_score_9d62f0_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowTask",
            fields=[
                (
                    "task_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="태스크 유형"
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="제목")),
                (
                    "owner_role",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="담당자 역할"
                    ),
                ),
                (
                    "source_object_type",
                    models.CharField(max_length=100, verbose_name="소스 객체 유형"),
                ),
                (
                    "source_object_id",
                    models.CharField(max_length=200, verbose_name="소스 객체 ID"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "대기중"),
                            ("IN_PROGRESS", "진행중"),
                            ("COMPLETED", "완료"),
                            ("CANCELLED", "취소"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "detail_json",
                    models.JSONField(default=dict, verbose_name="상세 정보"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="생성 시간"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료 시간"
                    ),
                ),
            ],
            options={
                "verbose_name": "워크플로우 태스크",
                "verbose_name_plural": "워크플로우 태스크",
                "db_table": "axos_workflow_tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task_type"], name="axos_workfl_task_ty_8803fc_idx"
                    ),
                    models.Index(
                        fields=["owner_role"], name="axos_workfl_owner_r_0cdb3a_idx"
                    ),
                    models.Index(
                        fields=["status"], name="axos_workfl_status_fd6aca_idx"
                    ),
                ],
            },
        ),
    ]
