# Generated by Django 5.0.1 on 2026-02-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FactInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inventory_date",
                    models.DateField(db_index=True, verbose_name="재고일자"),
                ),
                (
                    "warehouse",
                    models.CharField(db_index=True, max_length=20, verbose_name="창고"),
                ),
                (
                    "location",
                    models.CharField(max_length=50, null=True, verbose_name="위치"),
                ),
                (
                    "product_id",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="제품코드"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="제품명"),
                ),
                (
                    "lot_no",
                    models.CharField(max_length=50, null=True, verbose_name="LOT번호"),
                ),
                ("qty_on_hand", models.IntegerField(default=0, verbose_name="현재고")),
                (
                    "qty_available",
                    models.IntegerField(default=0, verbose_name="가용재고"),
                ),
                (
                    "qty_reserved",
                    models.IntegerField(default=0, verbose_name="예약재고"),
                ),
                (
                    "qty_in_transit",
                    models.IntegerField(default=0, verbose_name="입고예정"),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="단가"
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="총금액"
                    ),
                ),
                (
                    "safety_stock",
                    models.IntegerField(default=0, verbose_name="안전재고"),
                ),
                (
                    "reorder_point",
                    models.IntegerField(default=0, verbose_name="재주문점"),
                ),
                (
                    "lead_time_days",
                    models.IntegerField(default=0, verbose_name="리드타임(일)"),
                ),
                (
                    "source_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="원천ID"
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(auto_now=True, verbose_name="동기화시각"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "재고",
                "verbose_name_plural": "재고",
                "db_table": "fact_inventory",
                "ordering": ["-inventory_date", "warehouse"],
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["inventory_date", "warehouse"],
                        name="fact_invent_invento_ac3fb7_idx",
                    ),
                    models.Index(
                        fields=["product_id"], name="fact_invent_product_78947e_idx"
                    ),
                ],
            },
        ),
    ]
