# Generated by Django 5.0.1 on 2025-12-23 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnergyConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "energy_source",
                    models.CharField(
                        choices=[
                            ("electricity", "전기"),
                            ("gas", "가스"),
                            ("oil", "유류"),
                            ("steam", "증기"),
                            ("solar", "태양광"),
                        ],
                        max_length=20,
                        verbose_name="에너지원",
                    ),
                ),
                (
                    "consumption",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="소비량 (MWh)",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="비용 (백만원)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "에너지 소비",
                "verbose_name_plural": "에너지 소비",
                "db_table": "esg_energy_consumption",
                "ordering": ["-fiscal_year", "-fiscal_month"],
            },
        ),
        migrations.CreateModel(
            name="EnvironmentalProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="프로젝트 ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="프로젝트명")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("energy", "Energy"),
                            ("environment", "Environment"),
                            ("material", "Material"),
                            ("waste", "Waste"),
                        ],
                        max_length=20,
                        verbose_name="분류",
                    ),
                ),
                ("impact", models.CharField(max_length=200, verbose_name="예상 효과")),
                (
                    "investment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="투자액 (억원)",
                    ),
                ),
                (
                    "saving",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="절감액 (억원)",
                    ),
                ),
                (
                    "progress",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="진척도 (%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "계획"),
                            ("in-progress", "진행중"),
                            ("completed", "완료"),
                            ("delayed", "지연"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="시작일"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="종료일"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "환경 개선 프로젝트",
                "verbose_name_plural": "환경 개선 프로젝트",
                "db_table": "esg_environmental_project",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FourM2EMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("man", "Man (인력)"),
                            ("machine", "Machine (설비)"),
                            ("material", "Material (자재)"),
                            ("method", "Method (방법)"),
                            ("environment", "Environment (환경)"),
                            ("energy", "Energy (에너지)"),
                        ],
                        max_length=20,
                        verbose_name="분류",
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(max_length=100, verbose_name="지표명"),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="목표값",
                    ),
                ),
                (
                    "actual_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="실제값",
                    ),
                ),
                (
                    "unit",
                    models.CharField(default="%", max_length=20, verbose_name="단위"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("excellent", "우수"),
                            ("good", "양호"),
                            ("warning", "주의"),
                            ("critical", "미흡"),
                        ],
                        default="good",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "4M2E 지표",
                "verbose_name_plural": "4M2E 지표",
                "db_table": "esg_4m2e_metric",
                "ordering": ["-fiscal_year", "-fiscal_month", "category"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "metric_name",
                    models.CharField(max_length=100, verbose_name="지표명"),
                ),
                (
                    "actual_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="실제값 (%)",
                    ),
                ),
                (
                    "benchmark",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="벤치마크 (%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("excellent", "우수"),
                            ("good", "양호"),
                            ("warning", "주의"),
                            ("critical", "미흡"),
                        ],
                        default="good",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "지배구조 지표",
                "verbose_name_plural": "지배구조 지표",
                "db_table": "esg_governance_metric",
                "ordering": ["-fiscal_year"],
            },
        ),
        migrations.CreateModel(
            name="SocialResponsibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "activity_name",
                    models.CharField(max_length=200, verbose_name="활동명"),
                ),
                (
                    "participants",
                    models.IntegerField(default=0, verbose_name="참여 인원"),
                ),
                ("hours", models.IntegerField(default=0, verbose_name="활동 시간")),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="예산 (백만원)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "사회적 책임 활동",
                "verbose_name_plural": "사회적 책임 활동",
                "db_table": "esg_social_responsibility",
                "ordering": ["-fiscal_year", "-budget"],
            },
        ),
        migrations.CreateModel(
            name="CarbonEmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "target_emission",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="목표 배출량 (톤)",
                    ),
                ),
                (
                    "actual_emission",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="실제 배출량 (톤)",
                    ),
                ),
                (
                    "reduction_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="감축률 (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "탄소 배출량",
                "verbose_name_plural": "탄소 배출량",
                "db_table": "esg_carbon_emission",
                "ordering": ["-fiscal_year", "-fiscal_month"],
                "unique_together": {("fiscal_year", "fiscal_month")},
            },
        ),
        migrations.CreateModel(
            name="ESGScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "environment_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="환경(E) 점수",
                    ),
                ),
                (
                    "social_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="사회(S) 점수",
                    ),
                ),
                (
                    "governance_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="지배구조(G) 점수",
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="종합 점수",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "ESG 점수",
                "verbose_name_plural": "ESG 점수",
                "db_table": "esg_score",
                "ordering": ["-fiscal_year", "-fiscal_month"],
                "unique_together": {("fiscal_year", "fiscal_month")},
            },
        ),
    ]
