# Generated by Django 4.2.7 on 2026-03-30 07:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="이벤트 ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("KPI_DEVIATION", "KPI 편차"),
                            ("COST_VARIANCE_BREACH", "원가 편차 초과"),
                            ("MATERIAL_PRICE_SPIKE", "자재 단가 급등"),
                            ("SUPPLIER_RISK_ALERT", "공급처 리스크"),
                            ("OUTPUT_SHORTFALL", "생산 실적 미달"),
                            ("CAPACITY_OVERLOAD", "설비 과부하"),
                            ("DEFECT_CLUSTER", "불량 군집"),
                            ("CAPA_OVERDUE", "CAPA 지연"),
                            ("CASHFLOW_STRESS", "현금흐름 압박"),
                            ("BUDGET_OVERRUN", "예산 초과"),
                            ("ABNORMAL_JOURNAL", "전표 이상 패턴"),
                            ("OVERTIME_SURGE", "초과근무 급증"),
                            ("SOP_NONCOMPLIANCE", "SOP 미준수"),
                            ("APPROVAL_BYPASS", "승인 우회"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="이벤트 유형",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "정보"),
                            ("LOW", "낮음"),
                            ("MEDIUM", "보통"),
                            ("HIGH", "높음"),
                            ("CRITICAL", "긴급"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="심각도",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "발생"),
                            ("acknowledged", "확인"),
                            ("in_progress", "처리중"),
                            ("resolved", "해결"),
                            ("dismissed", "무시"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(max_length=50, verbose_name="범위 유형"),
                ),
                ("scope_id", models.CharField(max_length=100, verbose_name="범위 ID")),
                (
                    "scope_name",
                    models.CharField(blank=True, max_length=200, verbose_name="범위명"),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cost", "원가"),
                            ("finance", "재무"),
                            ("purchasing", "구매"),
                            ("production", "생산"),
                            ("quality", "품질"),
                            ("inventory", "재고"),
                            ("maintenance", "설비"),
                            ("sales", "영업"),
                            ("hr", "인사"),
                            ("compliance", "컴플라이언스"),
                        ],
                        max_length=30,
                        verbose_name="도메인",
                    ),
                ),
                (
                    "process_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("O2C", "Order to Cash"),
                            ("P2P", "Procure to Pay"),
                            ("P2Prod", "Plan to Produce"),
                            ("Q2R", "Quality to Resolution"),
                            ("R2R", "Record to Report"),
                            ("H2R", "Hire to Retire"),
                        ],
                        max_length=20,
                        verbose_name="프로세스",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(verbose_name="설명")),
                (
                    "observed_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                        verbose_name="관측값",
                    ),
                ),
                (
                    "threshold_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                        verbose_name="기준값",
                    ),
                ),
                (
                    "deviation_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="편차(%)",
                    ),
                ),
                (
                    "kpi_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="KPI 코드"
                    ),
                ),
                (
                    "kri_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="KRI 코드"
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=100, verbose_name="출처"),
                ),
                (
                    "source_detail",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="출처 상세"
                    ),
                ),
                (
                    "evidence_refs",
                    models.JSONField(
                        blank=True, default=list, verbose_name="근거 참조"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="해결일시"
                    ),
                ),
                (
                    "resolved_by",
                    models.CharField(blank=True, max_length=100, verbose_name="해결자"),
                ),
                (
                    "resolution_note",
                    models.TextField(blank=True, verbose_name="해결 내용"),
                ),
                (
                    "detected_by_agent",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="감지 Agent"
                    ),
                ),
                (
                    "agent_run_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="Agent 실행 ID"
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="확인일시"
                    ),
                ),
                (
                    "acknowledged_by",
                    models.CharField(blank=True, max_length=100, verbose_name="확인자"),
                ),
                (
                    "event_time",
                    models.DateTimeField(
                        db_index=True, verbose_name="이벤트 발생 시각"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "이벤트",
                "verbose_name_plural": "이벤트",
                "ordering": ["-event_time"],
            },
        ),
        migrations.CreateModel(
            name="EventCorrelation",
            fields=[
                (
                    "correlation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="상관관계 ID",
                    ),
                ),
                (
                    "correlation_type",
                    models.CharField(max_length=30, verbose_name="상관 유형"),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="신뢰도",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "analysis_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="분석 방법"
                    ),
                ),
                (
                    "time_lag_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="시간 지연(초)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "source_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correlations_from",
                        to="events.event",
                        verbose_name="소스 이벤트",
                    ),
                ),
                (
                    "target_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correlations_to",
                        to="events.event",
                        verbose_name="타겟 이벤트",
                    ),
                ),
            ],
            options={
                "verbose_name": "이벤트 상관관계",
                "verbose_name_plural": "이벤트 상관관계",
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_type", "severity", "status"],
                name="events_even_event_t_c0cdf6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["scope_type", "scope_id"], name="events_even_scope_t_a27226_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["domain", "process_code"], name="events_even_domain_e0a4bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["status", "event_time"], name="events_even_status_93ee54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventcorrelation",
            index=models.Index(
                fields=["correlation_type", "confidence"],
                name="events_even_correla_6a34dd_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventcorrelation",
            unique_together={("source_event", "target_event")},
        ),
    ]
