# Generated by Django 4.2.7 on 2026-03-31 07:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("report", "보고서"),
                            ("manual", "매뉴얼"),
                            ("policy", "정책"),
                            ("sop", "표준운영절차"),
                            ("knowledge", "지식베이스"),
                            ("log", "로그"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                        verbose_name="문서 유형",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="제목")),
                (
                    "source_path",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="원본 경로"
                    ),
                ),
                (
                    "author",
                    models.CharField(blank=True, max_length=100, verbose_name="작성자"),
                ),
                (
                    "created_at_source",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="원본 생성일"
                    ),
                ),
                (
                    "file_size_bytes",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="파일 크기(bytes)"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="카테고리"
                    ),
                ),
                ("tags", models.JSONField(default=list, verbose_name="태그")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "처리 대기"),
                            ("processing", "처리 중"),
                            ("indexed", "인덱스 완료"),
                            ("failed", "처리 실패"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="에러 메시지"),
                ),
                (
                    "total_chunks",
                    models.IntegerField(default=0, verbose_name="전체 청크 수"),
                ),
                (
                    "indexed_chunks",
                    models.IntegerField(default=0, verbose_name="인덱스된 청크 수"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드일"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="처리완료일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "RAG 문서",
                "verbose_name_plural": "RAG 문서",
                "db_table": "rag_document",
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("content", models.TextField(verbose_name="청크 내용")),
                ("chunk_index", models.IntegerField(verbose_name="청크 순서")),
                (
                    "page_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="페이지 번호"
                    ),
                ),
                (
                    "section_title",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="섹션 제목"
                    ),
                ),
                ("char_count", models.IntegerField(default=0, verbose_name="문자 수")),
                ("token_count", models.IntegerField(default=0, verbose_name="토큰 수")),
                (
                    "chunk_type",
                    models.CharField(
                        choices=[
                            ("semantic", "의미적"),
                            ("fixed", "고정 크기"),
                            ("recursive", "재귀적"),
                        ],
                        default="semantic",
                        max_length=20,
                        verbose_name="청크 유형",
                    ),
                ),
                (
                    "overlap_with_prev",
                    models.IntegerField(
                        default=0, verbose_name="이전 청크와 오버랩 문자 수"
                    ),
                ),
                (
                    "overlap_with_next",
                    models.IntegerField(
                        default=0, verbose_name="다음 청크와 오버랩 문자 수"
                    ),
                ),
                (
                    "embedding_status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("processing", "처리 중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="임베딩 상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "embedded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="임베딩일"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="rag.document",
                        verbose_name="문서",
                    ),
                ),
            ],
            options={
                "verbose_name": "문서 청크",
                "verbose_name_plural": "문서 청크",
                "db_table": "rag_document_chunk",
            },
        ),
        migrations.CreateModel(
            name="RetrievalLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("query", models.TextField(verbose_name="검색 쿼리")),
                (
                    "query_embedding",
                    models.JSONField(blank=True, null=True, verbose_name="쿼리 임베딩"),
                ),
                ("top_k", models.IntegerField(default=5, verbose_name="반환 결과 수")),
                (
                    "similarity_threshold",
                    models.FloatField(default=0.7, verbose_name="유사도 임계값"),
                ),
                (
                    "filter_category",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="필터 카테고리"
                    ),
                ),
                ("results", models.JSONField(default=list, verbose_name="검색 결과")),
                (
                    "result_count",
                    models.IntegerField(default=0, verbose_name="결과 수"),
                ),
                (
                    "search_time_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="검색 시간(ms)"
                    ),
                ),
                (
                    "avg_similarity",
                    models.FloatField(
                        blank=True, null=True, verbose_name="평균 유사도"
                    ),
                ),
                (
                    "user_feedback",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("relevant", "관련 있음"),
                            ("partial", "부분적 관련"),
                            ("irrelevant", "관련 없음"),
                        ],
                        max_length=20,
                        verbose_name="사용자 피드백",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
            ],
            options={
                "verbose_name": "검색 로그",
                "verbose_name_plural": "검색 로그",
                "db_table": "rag_retrieval_log",
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="rag_retriev_created_d8d6d0_idx"
                    ),
                    models.Index(fields=["query"], name="rag_retriev_query_25eba2_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Embedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("vector", models.JSONField(verbose_name="임베딩 벡터")),
                ("model_name", models.CharField(max_length=100, verbose_name="모델명")),
                (
                    "model_version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="모델 버전"
                    ),
                ),
                (
                    "dimension",
                    models.IntegerField(default=1536, verbose_name="벡터 차원"),
                ),
                (
                    "embedding_method",
                    models.CharField(
                        default="openai", max_length=50, verbose_name="임베딩 방법"
                    ),
                ),
                (
                    "computation_time_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="계산 시간(ms)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "chunk",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="rag.documentchunk",
                        verbose_name="문서 청크",
                    ),
                ),
            ],
            options={
                "verbose_name": "임베딩",
                "verbose_name_plural": "임베딩",
                "db_table": "rag_embedding",
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["doc_type", "status"], name="rag_documen_doc_typ_d314d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["category"], name="rag_documen_categor_cc16bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["status", "uploaded_at"], name="rag_documen_status_ba537a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="embedding",
            index=models.Index(
                fields=["model_name"], name="rag_embeddi_model_n_4cb3e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["document", "chunk_index"],
                name="rag_documen_documen_cabdb0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["embedding_status"], name="rag_documen_embeddi_676a18_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentchunk",
            unique_together={("document", "chunk_index")},
        ),
    ]
