# Generated by Django 5.0.1 on 2025-12-25 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ERPAccountLedger",
            fields=[
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                ("ledger_id", models.AutoField(primary_key=True, serialize=False)),
                ("fiscal_year", models.IntegerField(verbose_name="회계년도")),
                ("fiscal_month", models.IntegerField(verbose_name="회계월")),
                ("acct_cd", models.CharField(max_length=20, verbose_name="계정코드")),
                (
                    "acct_nm",
                    models.CharField(blank=True, max_length=100, verbose_name="계정명"),
                ),
                (
                    "dr_amt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="차변금액",
                    ),
                ),
                (
                    "cr_amt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="대변금액",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18, verbose_name="잔액"
                    ),
                ),
            ],
            options={
                "verbose_name": "ERP 계정원장",
                "verbose_name_plural": "ERP 계정원장",
                "db_table": "erp_cam900_yh",
            },
        ),
        migrations.CreateModel(
            name="ERPBarcodeDelivery",
            fields=[
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                (
                    "bar_id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="바코드ID"
                    ),
                ),
                ("bar_no", models.CharField(max_length=50, verbose_name="바코드번호")),
                ("cust_cd", models.CharField(max_length=20, verbose_name="거래처코드")),
                (
                    "cust_nm",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="거래처명"
                    ),
                ),
                ("fac_cd", models.CharField(max_length=10, verbose_name="입고공장")),
                ("wh_cd", models.CharField(max_length=10, verbose_name="입고창고")),
                ("itm_id", models.IntegerField(verbose_name="품목ID")),
                (
                    "itm_cd",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="품목코드"
                    ),
                ),
                (
                    "itm_nm",
                    models.CharField(blank=True, max_length=200, verbose_name="품목명"),
                ),
                ("dlv_dt", models.DateField(verbose_name="납품일자")),
                (
                    "mng_no",
                    models.CharField(blank=True, max_length=50, verbose_name="LOT번호"),
                ),
                (
                    "dlv_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="납품수량",
                    ),
                ),
                (
                    "dlv_bc",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="납품상태"
                    ),
                ),
            ],
            options={
                "verbose_name": "ERP 바코드납품",
                "verbose_name_plural": "ERP 바코드납품",
                "db_table": "erp_bar200",
            },
        ),
        migrations.CreateModel(
            name="ERPBOM",
            fields=[
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                ("bom_id", models.AutoField(primary_key=True, serialize=False)),
                ("parent_itm_id", models.IntegerField(verbose_name="상위품목ID")),
                (
                    "parent_itm_cd",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="상위품목코드"
                    ),
                ),
                (
                    "parent_itm_nm",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="상위품목명"
                    ),
                ),
                ("child_itm_id", models.IntegerField(verbose_name="하위품목ID")),
                (
                    "child_itm_cd",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="하위품목코드"
                    ),
                ),
                (
                    "child_itm_nm",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="하위품목명"
                    ),
                ),
                (
                    "bom_qty",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=18,
                        verbose_name="소요수량",
                    ),
                ),
                (
                    "loss_rt",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=8, verbose_name="손실율"
                    ),
                ),
                ("bom_level", models.IntegerField(default=1, verbose_name="BOM레벨")),
            ],
            options={
                "verbose_name": "ERP BOM",
                "verbose_name_plural": "ERP BOM",
                "db_table": "erp_dmb110_yuhan",
            },
        ),
        migrations.CreateModel(
            name="ERPInventoryCheck",
            fields=[
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                ("check_id", models.AutoField(primary_key=True, serialize=False)),
                ("check_dt", models.DateField(verbose_name="실사일자")),
                ("fac_cd", models.CharField(max_length=10, verbose_name="공장코드")),
                ("wh_cd", models.CharField(max_length=10, verbose_name="창고코드")),
                ("itm_id", models.IntegerField(verbose_name="품목ID")),
                (
                    "itm_cd",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="품목코드"
                    ),
                ),
                (
                    "itm_nm",
                    models.CharField(blank=True, max_length=200, verbose_name="품목명"),
                ),
                (
                    "book_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="장부수량",
                    ),
                ),
                (
                    "check_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="실사수량",
                    ),
                ),
                (
                    "diff_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="차이수량",
                    ),
                ),
                (
                    "lot_no",
                    models.CharField(blank=True, max_length=50, verbose_name="LOT번호"),
                ),
            ],
            options={
                "verbose_name": "ERP 재고실사",
                "verbose_name_plural": "ERP 재고실사",
                "db_table": "erp_leb900_yh",
            },
        ),
        migrations.CreateModel(
            name="ERPLocation",
            fields=[
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                (
                    "loc_cd",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="로케이션코드",
                    ),
                ),
                ("loc_nm", models.CharField(max_length=100, verbose_name="로케이션명")),
                ("fac_cd", models.CharField(max_length=10, verbose_name="공장코드")),
                ("wh_cd", models.CharField(max_length=10, verbose_name="창고코드")),
                (
                    "zone_cd",
                    models.CharField(blank=True, max_length=10, verbose_name="존코드"),
                ),
                (
                    "row_no",
                    models.CharField(blank=True, max_length=10, verbose_name="열"),
                ),
                (
                    "col_no",
                    models.CharField(blank=True, max_length=10, verbose_name="단"),
                ),
                (
                    "use_yn",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="사용여부"
                    ),
                ),
            ],
            options={
                "verbose_name": "ERP 로케이션",
                "verbose_name_plural": "ERP 로케이션",
                "db_table": "erp_lca100",
            },
        ),
        migrations.CreateModel(
            name="ERPLocationStock",
            fields=[
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                ("stock_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "loc_cd",
                    models.CharField(max_length=20, verbose_name="로케이션코드"),
                ),
                ("itm_id", models.IntegerField(verbose_name="품목ID")),
                (
                    "itm_cd",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="품목코드"
                    ),
                ),
                (
                    "itm_nm",
                    models.CharField(blank=True, max_length=200, verbose_name="품목명"),
                ),
                (
                    "lot_no",
                    models.CharField(blank=True, max_length=50, verbose_name="LOT번호"),
                ),
                (
                    "stk_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="재고수량",
                    ),
                ),
                (
                    "stk_dt",
                    models.DateField(blank=True, null=True, verbose_name="재고일자"),
                ),
            ],
            options={
                "verbose_name": "ERP 로케이션재고",
                "verbose_name_plural": "ERP 로케이션재고",
                "db_table": "erp_lcb100",
            },
        ),
        migrations.CreateModel(
            name="ERPMaterialPlan",
            fields=[
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                ("plan_id", models.AutoField(primary_key=True, serialize=False)),
                ("plan_year", models.IntegerField(verbose_name="계획년도")),
                ("plan_mon", models.IntegerField(verbose_name="계획월")),
                ("itm_id", models.IntegerField(verbose_name="품목ID")),
                (
                    "itm_cd",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="품목코드"
                    ),
                ),
                (
                    "itm_nm",
                    models.CharField(blank=True, max_length=200, verbose_name="품목명"),
                ),
                (
                    "req_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="소요수량",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=18, verbose_name="단가"
                    ),
                ),
                (
                    "req_amt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="소요금액",
                    ),
                ),
            ],
            options={
                "verbose_name": "ERP 년간자재계획",
                "verbose_name_plural": "ERP 년간자재계획",
                "db_table": "erp_mmy100_yh",
            },
        ),
        migrations.CreateModel(
            name="ERPMESData",
            fields=[
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                ("tag_id", models.AutoField(primary_key=True, serialize=False)),
                ("tag_dt", models.DateTimeField(verbose_name="수집일시")),
                ("equip_cd", models.CharField(max_length=20, verbose_name="설비코드")),
                ("tag_nm", models.CharField(max_length=50, verbose_name="태그명")),
                ("tag_val", models.CharField(max_length=100, verbose_name="태그값")),
                (
                    "tag_unit",
                    models.CharField(blank=True, max_length=20, verbose_name="단위"),
                ),
            ],
            options={
                "verbose_name": "ERP MES 데이터",
                "verbose_name_plural": "ERP MES 데이터",
                "db_table": "erp_mes_tagvalue_yh",
            },
        ),
        migrations.CreateModel(
            name="ERPMRP",
            fields=[
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                ("mrp_id", models.AutoField(primary_key=True, serialize=False)),
                ("mrp_no", models.CharField(max_length=20, verbose_name="MRP번호")),
                ("mrp_dt", models.DateField(verbose_name="계산일자")),
                ("fac_cd", models.CharField(max_length=10, verbose_name="공장코드")),
                ("plan_fr_dt", models.DateField(verbose_name="계획시작일")),
                ("plan_to_dt", models.DateField(verbose_name="계획종료일")),
                (
                    "status",
                    models.CharField(blank=True, max_length=10, verbose_name="상태"),
                ),
            ],
            options={
                "verbose_name": "ERP 자재소요계산",
                "verbose_name_plural": "ERP 자재소요계산",
                "db_table": "erp_mrp100_yh",
            },
        ),
        migrations.CreateModel(
            name="ERPProductionResult",
            fields=[
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                ("prd_id", models.AutoField(primary_key=True, serialize=False)),
                ("prd_dt", models.DateField(verbose_name="생산일자")),
                ("fac_cd", models.CharField(max_length=10, verbose_name="공장코드")),
                ("line_cd", models.CharField(max_length=20, verbose_name="라인코드")),
                (
                    "equip_cd",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="설비코드"
                    ),
                ),
                ("itm_id", models.IntegerField(verbose_name="품목ID")),
                (
                    "itm_cd",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="품목코드"
                    ),
                ),
                (
                    "itm_nm",
                    models.CharField(blank=True, max_length=200, verbose_name="품목명"),
                ),
                (
                    "plan_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="계획수량",
                    ),
                ),
                (
                    "prd_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="생산수량",
                    ),
                ),
                (
                    "good_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="양품수량",
                    ),
                ),
                (
                    "bad_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="불량수량",
                    ),
                ),
                (
                    "counter_val",
                    models.IntegerField(default=0, verbose_name="카운터값"),
                ),
            ],
            options={
                "verbose_name": "ERP 생산실적",
                "verbose_name_plural": "ERP 생산실적",
                "db_table": "erp_ppc100_counter",
            },
        ),
        migrations.CreateModel(
            name="ERPProductLedger",
            fields=[
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                ("ledger_id", models.AutoField(primary_key=True, serialize=False)),
                ("fiscal_year", models.IntegerField(verbose_name="회계년도")),
                ("fiscal_month", models.IntegerField(verbose_name="회계월")),
                ("fac_cd", models.CharField(max_length=10, verbose_name="공장코드")),
                ("itm_id", models.IntegerField(verbose_name="품목ID")),
                (
                    "itm_cd",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="품목코드"
                    ),
                ),
                (
                    "itm_nm",
                    models.CharField(blank=True, max_length=200, verbose_name="품목명"),
                ),
                (
                    "prev_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="전기이월수량",
                    ),
                ),
                (
                    "prev_amt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="전기이월금액",
                    ),
                ),
                (
                    "in_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="입고수량",
                    ),
                ),
                (
                    "in_amt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="입고금액",
                    ),
                ),
                (
                    "out_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="출고수량",
                    ),
                ),
                (
                    "out_amt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="출고금액",
                    ),
                ),
                (
                    "end_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="기말수량",
                    ),
                ),
                (
                    "end_amt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="기말금액",
                    ),
                ),
            ],
            options={
                "verbose_name": "ERP 제품수불부",
                "verbose_name_plural": "ERP 제품수불부",
                "db_table": "erp_cam300_yh",
            },
        ),
        migrations.CreateModel(
            name="ERPQualityItem",
            fields=[
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                (
                    "itm_id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="품목ID"
                    ),
                ),
                ("itm_cd", models.CharField(max_length=50, verbose_name="품목코드")),
                ("itm_nm", models.CharField(max_length=200, verbose_name="품목명")),
                (
                    "itm_spec",
                    models.CharField(blank=True, max_length=200, verbose_name="규격"),
                ),
                (
                    "itm_unit",
                    models.CharField(blank=True, max_length=10, verbose_name="단위"),
                ),
                (
                    "cust_cd",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="고객코드"
                    ),
                ),
                (
                    "cust_nm",
                    models.CharField(blank=True, max_length=100, verbose_name="고객명"),
                ),
                (
                    "qc_bc",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="검사구분"
                    ),
                ),
                (
                    "use_yn",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="사용여부"
                    ),
                ),
            ],
            options={
                "verbose_name": "ERP 품질품목",
                "verbose_name_plural": "ERP 품질품목",
                "db_table": "erp_qda100_yuhan",
            },
        ),
        migrations.CreateModel(
            name="ERPShipmentInspection",
            fields=[
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                (
                    "qc_no",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="검사번호",
                    ),
                ),
                ("qc_dt", models.DateField(verbose_name="검사일자")),
                ("fac_cd", models.CharField(max_length=10, verbose_name="공장코드")),
                (
                    "cust_cd",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="거래처코드"
                    ),
                ),
                (
                    "cust_nm",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="거래처명"
                    ),
                ),
                ("itm_id", models.IntegerField(verbose_name="품목ID")),
                (
                    "itm_cd",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="품목코드"
                    ),
                ),
                (
                    "itm_nm",
                    models.CharField(blank=True, max_length=200, verbose_name="품목명"),
                ),
                (
                    "lot_no",
                    models.CharField(blank=True, max_length=50, verbose_name="LOT번호"),
                ),
                (
                    "qc_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="검사수량",
                    ),
                ),
                (
                    "pass_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="합격수량",
                    ),
                ),
                (
                    "fail_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="불합격수량",
                    ),
                ),
                (
                    "qc_result",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="검사결과"
                    ),
                ),
                (
                    "inspector",
                    models.CharField(blank=True, max_length=50, verbose_name="검사자"),
                ),
            ],
            options={
                "verbose_name": "ERP 출하검사",
                "verbose_name_plural": "ERP 출하검사",
                "db_table": "erp_qmo100",
            },
        ),
        migrations.CreateModel(
            name="ERPShipmentPlan",
            fields=[
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                (
                    "plan_no",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="계획번호",
                    ),
                ),
                ("dlv_dt", models.DateField(verbose_name="납품일자")),
                ("cust_cd", models.CharField(max_length=20, verbose_name="거래처코드")),
                (
                    "cust_nm",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="거래처명"
                    ),
                ),
                (
                    "sply_cd",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="공급처코드"
                    ),
                ),
                ("rmks", models.TextField(blank=True, verbose_name="비고")),
            ],
            options={
                "verbose_name": "ERP 일일출하계획",
                "verbose_name_plural": "ERP 일일출하계획",
                "db_table": "erp_sda500_yh",
            },
        ),
        migrations.CreateModel(
            name="ERPSPC",
            fields=[
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                ("spc_id", models.AutoField(primary_key=True, serialize=False)),
                ("spc_dt", models.DateField(verbose_name="집계일자")),
                ("fac_cd", models.CharField(max_length=10, verbose_name="공장코드")),
                ("proc_cd", models.CharField(max_length=20, verbose_name="공정코드")),
                (
                    "proc_nm",
                    models.CharField(blank=True, max_length=100, verbose_name="공정명"),
                ),
                (
                    "itm_id",
                    models.IntegerField(blank=True, null=True, verbose_name="품목ID"),
                ),
                (
                    "spec_nm",
                    models.CharField(blank=True, max_length=100, verbose_name="규격명"),
                ),
                (
                    "usl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                        verbose_name="상한",
                    ),
                ),
                (
                    "lsl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                        verbose_name="하한",
                    ),
                ),
                (
                    "avg_val",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                        verbose_name="평균",
                    ),
                ),
                (
                    "std_val",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                        verbose_name="표준편차",
                    ),
                ),
                (
                    "cp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="Cp",
                    ),
                ),
                (
                    "cpk",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="Cpk",
                    ),
                ),
            ],
            options={
                "verbose_name": "ERP SPC",
                "verbose_name_plural": "ERP SPC",
                "db_table": "erp_qpm100_yh",
            },
        ),
        migrations.CreateModel(
            name="ERPSupplier",
            fields=[
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                (
                    "sply_cd",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="공급업체코드",
                    ),
                ),
                (
                    "sply_nm",
                    models.CharField(max_length=100, verbose_name="공급업체명"),
                ),
                (
                    "biz_no",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="사업자번호"
                    ),
                ),
                (
                    "ceo_nm",
                    models.CharField(blank=True, max_length=50, verbose_name="대표자"),
                ),
                (
                    "addr",
                    models.CharField(blank=True, max_length=200, verbose_name="주소"),
                ),
                (
                    "tel_no",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="전화번호"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="이메일"
                    ),
                ),
                (
                    "sply_type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="업체구분"
                    ),
                ),
                (
                    "grade",
                    models.CharField(blank=True, max_length=10, verbose_name="등급"),
                ),
                (
                    "use_yn",
                    models.CharField(
                        default="Y", max_length=1, verbose_name="사용여부"
                    ),
                ),
            ],
            options={
                "verbose_name": "ERP 공급업체",
                "verbose_name_plural": "ERP 공급업체",
                "db_table": "erp_qmm600",
            },
        ),
        migrations.CreateModel(
            name="ERPSupplierEvaluation",
            fields=[
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                ("eval_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sply_cd",
                    models.CharField(max_length=20, verbose_name="공급업체코드"),
                ),
                ("eval_year", models.IntegerField(verbose_name="평가년도")),
                (
                    "eval_term",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="평가기간"
                    ),
                ),
                (
                    "quality_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="품질점수",
                    ),
                ),
                (
                    "delivery_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="납기점수",
                    ),
                ),
                (
                    "price_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="가격점수",
                    ),
                ),
                (
                    "service_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="서비스점수",
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="총점"
                    ),
                ),
                (
                    "grade",
                    models.CharField(blank=True, max_length=10, verbose_name="등급"),
                ),
            ],
            options={
                "verbose_name": "ERP 공급업체평가",
                "verbose_name_plural": "ERP 공급업체평가",
                "db_table": "erp_qmm630",
            },
        ),
        migrations.CreateModel(
            name="ERPSyncConfig",
            fields=[
                ("config_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "erp_table",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="ERP 테이블"
                    ),
                ),
                (
                    "mis_model",
                    models.CharField(max_length=100, verbose_name="MIS 모델"),
                ),
                (
                    "sync_interval",
                    models.CharField(
                        choices=[
                            ("realtime", "실시간"),
                            ("1min", "1분"),
                            ("5min", "5분"),
                            ("15min", "15분"),
                            ("30min", "30분"),
                            ("1hour", "1시간"),
                            ("daily", "일 1회"),
                        ],
                        default="5min",
                        max_length=20,
                        verbose_name="동기화 주기",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 동기화"
                    ),
                ),
                (
                    "sync_query",
                    models.TextField(blank=True, verbose_name="동기화 쿼리"),
                ),
                (
                    "field_mapping",
                    models.JSONField(default=dict, verbose_name="필드 매핑"),
                ),
            ],
            options={
                "verbose_name": "ERP 동기화 설정",
                "verbose_name_plural": "ERP 동기화 설정",
                "db_table": "erp_sync_config",
            },
        ),
        migrations.CreateModel(
            name="ERPSyncLog",
            fields=[
                ("sync_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("full", "전체 동기화"),
                            ("incremental", "증분 동기화"),
                            ("manual", "수동 동기화"),
                        ],
                        max_length=20,
                        verbose_name="동기화 유형",
                    ),
                ),
                (
                    "target_table",
                    models.CharField(max_length=50, verbose_name="대상 테이블"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "실행중"),
                            ("success", "성공"),
                            ("failed", "실패"),
                            ("partial", "부분성공"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="시작시간"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="종료시간"
                    ),
                ),
                (
                    "total_count",
                    models.IntegerField(default=0, verbose_name="전체 건수"),
                ),
                (
                    "success_count",
                    models.IntegerField(default=0, verbose_name="성공 건수"),
                ),
                (
                    "error_count",
                    models.IntegerField(default=0, verbose_name="오류 건수"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="오류 메시지"),
                ),
            ],
            options={
                "verbose_name": "ERP 동기화 로그",
                "verbose_name_plural": "ERP 동기화 로그",
                "db_table": "erp_sync_log",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ERPWorkInProcess",
            fields=[
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                ("wip_id", models.AutoField(primary_key=True, serialize=False)),
                ("fiscal_year", models.IntegerField(verbose_name="회계년도")),
                ("fiscal_month", models.IntegerField(verbose_name="회계월")),
                ("fac_cd", models.CharField(max_length=10, verbose_name="공장코드")),
                ("itm_id", models.IntegerField(verbose_name="품목ID")),
                (
                    "itm_cd",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="품목코드"
                    ),
                ),
                (
                    "itm_nm",
                    models.CharField(blank=True, max_length=200, verbose_name="품목명"),
                ),
                (
                    "wip_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="재공수량",
                    ),
                ),
                (
                    "wip_amt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="재공금액",
                    ),
                ),
                (
                    "mat_amt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="재료비",
                    ),
                ),
                (
                    "labor_amt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="노무비",
                    ),
                ),
                (
                    "exp_amt",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18, verbose_name="경비"
                    ),
                ),
            ],
            options={
                "verbose_name": "ERP 재공품명세",
                "verbose_name_plural": "ERP 재공품명세",
                "db_table": "erp_cam200_yh",
            },
        ),
        migrations.CreateModel(
            name="ERPDeliveryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                ("so_no", models.CharField(max_length=20, verbose_name="수주번호")),
                ("so_sq", models.IntegerField(verbose_name="수주순번")),
                ("sq_no", models.IntegerField(verbose_name="이력순번")),
                ("dlv_dt", models.DateField(verbose_name="납기일자")),
                ("rmks", models.TextField(blank=True, verbose_name="비고")),
            ],
            options={
                "verbose_name": "ERP 납기이력",
                "verbose_name_plural": "ERP 납기이력",
                "db_table": "erp_sdb150_dlv",
                "unique_together": {("so_no", "so_sq", "sq_no")},
            },
        ),
        migrations.CreateModel(
            name="ERPMRPMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                ("mrp_id", models.IntegerField(verbose_name="MRP ID")),
                ("mrp_sq", models.IntegerField(verbose_name="순번")),
                ("itm_id", models.IntegerField(verbose_name="품목ID")),
                (
                    "itm_cd",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="품목코드"
                    ),
                ),
                (
                    "itm_nm",
                    models.CharField(blank=True, max_length=200, verbose_name="품목명"),
                ),
                (
                    "req_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="소요수량",
                    ),
                ),
                (
                    "stk_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="재고수량",
                    ),
                ),
                (
                    "ord_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="발주수량",
                    ),
                ),
                (
                    "net_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="순소요량",
                    ),
                ),
            ],
            options={
                "verbose_name": "ERP 원자재소요량",
                "verbose_name_plural": "ERP 원자재소요량",
                "db_table": "erp_mrp110_yh",
                "unique_together": {("mrp_id", "mrp_sq")},
            },
        ),
        migrations.CreateModel(
            name="ERPSalesYearPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                ("plan_year", models.IntegerField(verbose_name="계획년도")),
                ("plan_rev", models.IntegerField(default=1, verbose_name="계획차수")),
                ("fac_cd", models.CharField(max_length=10, verbose_name="공장코드")),
                ("plan_mon", models.IntegerField(verbose_name="계획월")),
                ("cust_cd", models.CharField(max_length=20, verbose_name="거래처코드")),
                (
                    "cust_nm",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="거래처명"
                    ),
                ),
                ("itm_id", models.IntegerField(verbose_name="품목ID")),
                (
                    "itm_cd",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="품목코드"
                    ),
                ),
                (
                    "itm_nm",
                    models.CharField(blank=True, max_length=200, verbose_name="품목명"),
                ),
                (
                    "plan_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="계획수량",
                    ),
                ),
                (
                    "plan_up",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="계획단가",
                    ),
                ),
                (
                    "plan_amt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="계획금액",
                    ),
                ),
            ],
            options={
                "verbose_name": "ERP 년제품판매계획",
                "verbose_name_plural": "ERP 년제품판매계획",
                "db_table": "erp_sdy100_yh",
                "unique_together": {
                    (
                        "co_cd",
                        "plan_year",
                        "plan_rev",
                        "fac_cd",
                        "plan_mon",
                        "cust_cd",
                        "itm_id",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="ERPShipmentDefect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                ("qc_no", models.CharField(max_length=20, verbose_name="검사번호")),
                ("defect_sq", models.IntegerField(verbose_name="불량순번")),
                ("defect_cd", models.CharField(max_length=20, verbose_name="불량코드")),
                (
                    "defect_nm",
                    models.CharField(blank=True, max_length=100, verbose_name="불량명"),
                ),
                (
                    "defect_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="불량수량",
                    ),
                ),
                (
                    "defect_rt",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=8, verbose_name="불량율"
                    ),
                ),
                ("rmks", models.TextField(blank=True, verbose_name="비고")),
            ],
            options={
                "verbose_name": "ERP 출하검사불량",
                "verbose_name_plural": "ERP 출하검사불량",
                "db_table": "erp_qmo110",
                "unique_together": {("qc_no", "defect_sq")},
            },
        ),
        migrations.CreateModel(
            name="ERPShipmentPlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                ("plan_no", models.CharField(max_length=20, verbose_name="계획번호")),
                ("plan_sq", models.IntegerField(verbose_name="계획순번")),
                ("itm_id", models.IntegerField(verbose_name="품목ID")),
                (
                    "itm_cd",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="품목코드"
                    ),
                ),
                (
                    "itm_nm",
                    models.CharField(blank=True, max_length=200, verbose_name="품목명"),
                ),
                (
                    "plan_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="계획수량",
                    ),
                ),
                (
                    "out_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="출고수량",
                    ),
                ),
                (
                    "rem_qty",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=18, verbose_name="잔량"
                    ),
                ),
                (
                    "so_no",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="수주번호"
                    ),
                ),
                (
                    "so_sq",
                    models.IntegerField(blank=True, null=True, verbose_name="수주순번"),
                ),
                (
                    "qc_yn",
                    models.CharField(blank=True, max_length=1, verbose_name="검사여부"),
                ),
                (
                    "qc_bc",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="검사구분"
                    ),
                ),
            ],
            options={
                "verbose_name": "ERP 출하계획품목",
                "verbose_name_plural": "ERP 출하계획품목",
                "db_table": "erp_sda510_yh",
                "unique_together": {("plan_no", "plan_sq")},
            },
        ),
    ]
