# Generated by Django 5.0.1 on 2026-02-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_sync", "0002_add_fom_erp_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="FOMEquipmentMaster",
            fields=[
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                (
                    "equipment_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="설비ID",
                    ),
                ),
                (
                    "equipment_name",
                    models.CharField(max_length=200, verbose_name="설비명"),
                ),
                ("plant", models.CharField(max_length=10, verbose_name="공장")),
                ("line", models.CharField(max_length=20, verbose_name="라인")),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="위치"),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=100, verbose_name="제조사"),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, verbose_name="모델"),
                ),
                (
                    "capacity",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, null=True, verbose_name="용량"
                    ),
                ),
                (
                    "install_date",
                    models.DateField(blank=True, null=True, verbose_name="설치일자"),
                ),
                (
                    "acquisition_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="취득가",
                    ),
                ),
                (
                    "depreciation_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="감가상각비",
                    ),
                ),
                (
                    "status",
                    models.CharField(blank=True, max_length=20, verbose_name="상태"),
                ),
            ],
            options={
                "verbose_name": "FOM 설비마스터",
                "verbose_name_plural": "FOM 설비마스터",
                "db_table": "fom_equipment_master",
            },
        ),
        migrations.CreateModel(
            name="FOMProductMaster",
            fields=[
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="품목코드",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="품목명"),
                ),
                (
                    "product_name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="품목명(영문)"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="카테고리"
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="품목유형"
                    ),
                ),
                (
                    "product_group",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="품목그룹"
                    ),
                ),
                ("specification", models.TextField(blank=True, verbose_name="규격")),
                (
                    "unit",
                    models.CharField(blank=True, max_length=10, verbose_name="단위"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, null=True, verbose_name="중량"
                    ),
                ),
                (
                    "standard_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="표준원가",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="판매가",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="사용여부"),
                ),
            ],
            options={
                "verbose_name": "FOM 품목마스터",
                "verbose_name_plural": "FOM 품목마스터",
                "db_table": "fom_product",
            },
        ),
        migrations.AlterField(
            model_name="fominventorydata",
            name="qty_available",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=18,
                null=True,
                verbose_name="가용재고",
            ),
        ),
        migrations.AlterField(
            model_name="fominventorydata",
            name="qty_on_hand",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=18,
                null=True,
                verbose_name="재고수량",
            ),
        ),
        migrations.AlterField(
            model_name="fominventorydata",
            name="qty_reserved",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=18,
                null=True,
                verbose_name="예약재고",
            ),
        ),
        migrations.AlterField(
            model_name="fominventorydata",
            name="reorder_point",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=18,
                null=True,
                verbose_name="재발주점",
            ),
        ),
        migrations.AlterField(
            model_name="fominventorydata",
            name="safety_stock",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=18,
                null=True,
                verbose_name="안전재고",
            ),
        ),
        migrations.AlterField(
            model_name="fominventorydata",
            name="total_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=18,
                null=True,
                verbose_name="총금액",
            ),
        ),
        migrations.AlterField(
            model_name="fominventorydata",
            name="unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=18,
                null=True,
                verbose_name="단가",
            ),
        ),
        migrations.AlterField(
            model_name="fomproductiondata",
            name="downtime",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="가동중단시간",
            ),
        ),
        migrations.AlterField(
            model_name="fomproductiondata",
            name="qty_actual",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=18,
                null=True,
                verbose_name="실적수량",
            ),
        ),
        migrations.AlterField(
            model_name="fomproductiondata",
            name="qty_bad",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=18,
                null=True,
                verbose_name="불량수량",
            ),
        ),
        migrations.AlterField(
            model_name="fomproductiondata",
            name="qty_good",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=18,
                null=True,
                verbose_name="양품수량",
            ),
        ),
        migrations.AlterField(
            model_name="fomproductiondata",
            name="qty_plan",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=18,
                null=True,
                verbose_name="계획수량",
            ),
        ),
        migrations.AlterField(
            model_name="fomproductiondata",
            name="work_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="작업시간",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fominventorydata",
            unique_together={("inventory_date", "warehouse", "location", "product_id")},
        ),
        migrations.AlterUniqueTogether(
            name="fomproductiondata",
            unique_together={("work_date", "plant", "line", "product_id")},
        ),
        migrations.CreateModel(
            name="FOMBOMData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                (
                    "parent_product",
                    models.CharField(max_length=50, verbose_name="상위품목"),
                ),
                (
                    "child_product",
                    models.CharField(max_length=50, verbose_name="하위품목"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=18,
                        verbose_name="소요량",
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=10, verbose_name="단위"),
                ),
                ("level", models.IntegerField(default=1, verbose_name="BOM레벨")),
                ("sequence", models.IntegerField(default=1, verbose_name="순번")),
                (
                    "is_substitute",
                    models.BooleanField(default=False, verbose_name="대체여부"),
                ),
                (
                    "substitute_for",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="대체대상"
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(blank=True, null=True, verbose_name="유효시작일"),
                ),
                (
                    "valid_to",
                    models.DateField(blank=True, null=True, verbose_name="유효종료일"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="사용여부"),
                ),
            ],
            options={
                "verbose_name": "FOM BOM",
                "verbose_name_plural": "FOM BOM",
                "db_table": "fom_bom",
                "unique_together": {("parent_product", "child_product", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="FOMCostData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                ("cost_month", models.CharField(max_length=7, verbose_name="원가월")),
                (
                    "product_id",
                    models.CharField(max_length=50, verbose_name="품목코드"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="품목명"),
                ),
                (
                    "cost_center",
                    models.CharField(max_length=20, verbose_name="원가센터"),
                ),
                (
                    "material_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="재료비",
                    ),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="노무비",
                    ),
                ),
                (
                    "overhead_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18, verbose_name="경비"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="단위당원가",
                    ),
                ),
                (
                    "standard_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="표준원가",
                    ),
                ),
                (
                    "variance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="원가차이",
                    ),
                ),
                (
                    "variance_rate",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=8, verbose_name="차이율"
                    ),
                ),
                (
                    "output_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="생산수량",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="총원가",
                    ),
                ),
            ],
            options={
                "verbose_name": "FOM 원가현황",
                "verbose_name_plural": "FOM 원가현황",
                "db_table": "fom_cost",
                "unique_together": {("cost_month", "product_id", "cost_center")},
            },
        ),
        migrations.CreateModel(
            name="FOMEquipmentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                ("operation_date", models.DateField(verbose_name="운전일자")),
                (
                    "equipment_id",
                    models.CharField(max_length=50, verbose_name="설비ID"),
                ),
                (
                    "equipment_name",
                    models.CharField(max_length=200, verbose_name="설비명"),
                ),
                ("plant", models.CharField(max_length=10, verbose_name="공장")),
                ("line", models.CharField(max_length=20, verbose_name="라인")),
                (
                    "planned_time",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="계획가동시간",
                    ),
                ),
                (
                    "actual_time",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="실가동시간",
                    ),
                ),
                (
                    "downtime",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="가동중단시간",
                    ),
                ),
                (
                    "failure_count",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="고장횟수"
                    ),
                ),
                (
                    "failure_time",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="고장시간",
                    ),
                ),
                (
                    "output_qty",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="생산수량"
                    ),
                ),
                (
                    "defect_qty",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="불량수량"
                    ),
                ),
                (
                    "availability",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        null=True,
                        verbose_name="가동률",
                    ),
                ),
                (
                    "performance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        null=True,
                        verbose_name="성능률",
                    ),
                ),
                (
                    "quality_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        null=True,
                        verbose_name="양품률",
                    ),
                ),
                (
                    "oee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        null=True,
                        verbose_name="OEE",
                    ),
                ),
            ],
            options={
                "verbose_name": "FOM 설비운전",
                "verbose_name_plural": "FOM 설비운전",
                "db_table": "fom_equipment",
                "unique_together": {("operation_date", "equipment_id")},
            },
        ),
        migrations.CreateModel(
            name="FOMFinanceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                ("fiscal_month", models.CharField(max_length=7, verbose_name="회계월")),
                (
                    "account_type",
                    models.CharField(max_length=20, verbose_name="계정유형"),
                ),
                (
                    "account_code",
                    models.CharField(max_length=20, verbose_name="계정코드"),
                ),
                (
                    "account_name",
                    models.CharField(max_length=200, verbose_name="계정명"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18, verbose_name="금액"
                    ),
                ),
                (
                    "prev_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="전기금액",
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="매출액",
                    ),
                ),
                (
                    "cogs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="매출원가",
                    ),
                ),
                (
                    "gross_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="매출총이익",
                    ),
                ),
                (
                    "operating_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="영업이익",
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="당기순이익",
                    ),
                ),
            ],
            options={
                "verbose_name": "FOM 재무현황",
                "verbose_name_plural": "FOM 재무현황",
                "db_table": "fom_finance",
                "unique_together": {("fiscal_month", "account_code")},
            },
        ),
        migrations.CreateModel(
            name="FOMQualityData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "erp_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ERP 동기화 시간"
                    ),
                ),
                (
                    "erp_source_table",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ERP 원본 테이블"
                    ),
                ),
                (
                    "erp_source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ERP 원본 ID"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="동기화 여부"),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="동기화 오류"),
                ),
                (
                    "bs_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="사업장코드"
                    ),
                ),
                (
                    "co_cd",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="회사코드"
                    ),
                ),
                (
                    "cid",
                    models.IntegerField(blank=True, null=True, verbose_name="생성자ID"),
                ),
                (
                    "cdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "mid",
                    models.IntegerField(blank=True, null=True, verbose_name="수정자ID"),
                ),
                (
                    "mdt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="수정일시"
                    ),
                ),
                ("inspection_date", models.DateField(verbose_name="검사일자")),
                (
                    "inspection_type",
                    models.CharField(max_length=20, verbose_name="검사유형"),
                ),
                (
                    "product_id",
                    models.CharField(max_length=50, verbose_name="품목코드"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="품목명"),
                ),
                (
                    "lot_no",
                    models.CharField(blank=True, max_length=50, verbose_name="LOT번호"),
                ),
                (
                    "qty_inspected",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="검사수량"
                    ),
                ),
                (
                    "qty_passed",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="합격수량"
                    ),
                ),
                (
                    "qty_failed",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="불량수량"
                    ),
                ),
                (
                    "qty_rework",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="재작업수량"
                    ),
                ),
                (
                    "defect_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="불량유형"
                    ),
                ),
                (
                    "defect_cause",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="불량원인"
                    ),
                ),
                (
                    "defect_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=0,
                        max_digits=8,
                        null=True,
                        verbose_name="불량률",
                    ),
                ),
                (
                    "measured_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                        verbose_name="측정값",
                    ),
                ),
                (
                    "spec_lower",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                        verbose_name="규격하한",
                    ),
                ),
                (
                    "spec_upper",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                        verbose_name="규격상한",
                    ),
                ),
                (
                    "inspector",
                    models.CharField(blank=True, max_length=50, verbose_name="검사자"),
                ),
            ],
            options={
                "verbose_name": "FOM 품질검사",
                "verbose_name_plural": "FOM 품질검사",
                "db_table": "fom_quality",
                "unique_together": {
                    ("inspection_date", "inspection_type", "product_id", "lot_no")
                },
            },
        ),
    ]
