# Generated by Django 5.0 on 2026-03-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_sync", "0005_erpsource_password_erpsource_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="ERPSyncServiceConfig",
            fields=[
                ("config_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("sap", "SAP ERP 서비스"),
                            ("fom", "FOM ERP 서비스"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="서비스 유형",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(max_length=100, verbose_name="서비스명"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("running", "동기화 중"),
                            ("idle", "대기 중"),
                            ("error", "오류 발생"),
                            ("disabled", "비활성화"),
                        ],
                        default="idle",
                        max_length=20,
                        verbose_name="동기화 상태",
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 동기화 시간"
                    ),
                ),
                (
                    "last_error_message",
                    models.TextField(blank=True, verbose_name="마지막 오류 메시지"),
                ),
                (
                    "total_sync_count",
                    models.IntegerField(default=0, verbose_name="총 동기화 횟수"),
                ),
                (
                    "success_sync_count",
                    models.IntegerField(default=0, verbose_name="성공 동기화 횟수"),
                ),
                (
                    "failed_sync_count",
                    models.IntegerField(default=0, verbose_name="실패 동기화 횟수"),
                ),
                (
                    "sync_interval_minutes",
                    models.IntegerField(default=15, verbose_name="동기화 주기(분)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "sync_table_settings",
                    models.JSONField(default=dict, verbose_name="테이블별 동기화 설정"),
                ),
            ],
            options={
                "verbose_name": "ERP 동기화 서비스 설정",
                "verbose_name_plural": "ERP 동기화 서비스 설정",
                "db_table": "erp_sync_service_config",
            },
        ),
    ]
