# Generated by Django 5.2.13 on 2026-04-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_sync", "0006_erpsyncserviceconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="erpsyncserviceconfig",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("sap", "SAP ERP 서비스"),
                    ("fom", "FOM ERP 서비스"),
                    ("sample", "샘플 데이터 서비스"),
                ],
                max_length=20,
                unique=True,
                verbose_name="서비스 유형",
            ),
        ),
    ]
