# Generated by Django 5.2.13 on 2026-04-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp_sync", "0007_alter_erpsyncserviceconfig_service_type"),
    ]

    operations = []
