# Generated by Django 5.2.13 on 2026-07-01 07:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_sync", "0008_auto_20260421_2320"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterProduct",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "product_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="제품 코드"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="제품명"),
                ),
                (
                    "product_name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="제품명(영문)"
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("raw_material", "원자재"),
                            ("semi_finished", "반제품"),
                            ("finished_good", "완제품"),
                            ("packaging", "포장재"),
                            ("consumable", "소모품"),
                        ],
                        max_length=20,
                        verbose_name="제품 유형",
                    ),
                ),
                ("specification", models.TextField(blank=True, verbose_name="규격")),
                (
                    "category_l1",
                    models.CharField(blank=True, max_length=50, verbose_name="대분류"),
                ),
                (
                    "category_l2",
                    models.CharField(blank=True, max_length=50, verbose_name="중분류"),
                ),
                (
                    "category_l3",
                    models.CharField(blank=True, max_length=50, verbose_name="소분류"),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=10, verbose_name="단위"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="중량(kg)",
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(blank=True, max_length=50, verbose_name="치수"),
                ),
                (
                    "standard_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="표준 원가",
                    ),
                ),
                (
                    "last_purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="최근 구매 단가",
                    ),
                ),
                (
                    "erp_sources",
                    models.JSONField(
                        default=dict,
                        help_text="{erp_code: erp_item_id}",
                        verbose_name="ERP 출처",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "마스터 제품",
                "verbose_name_plural": "마스터 제품",
                "db_table": "master_product",
                "ordering": ["product_code"],
            },
        ),
        migrations.CreateModel(
            name="MasterBank",
            fields=[
                ("bank_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "bank_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="은행 코드"
                    ),
                ),
                ("bank_name", models.CharField(max_length=200, verbose_name="은행명")),
                (
                    "bank_name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="은행명(영문)"
                    ),
                ),
                (
                    "bank_type",
                    models.CharField(
                        choices=[
                            ("commercial", "시중은행"),
                            ("specialized", "특수은행"),
                            ("foreign", "외국은행"),
                            ("internet", "인터넷은행"),
                            ("savings", "저축은행"),
                            ("post", "우체국"),
                        ],
                        max_length=20,
                        verbose_name="은행 유형",
                    ),
                ),
                (
                    "bank_category",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="은행 분류"
                    ),
                ),
                (
                    "swift_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="SWIFT 코드"
                    ),
                ),
                (
                    "bank_branch_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="지점 코드"
                    ),
                ),
                (
                    "bank_branch_name",
                    models.CharField(blank=True, max_length=200, verbose_name="지점명"),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=50, verbose_name="연락처"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="이메일"
                    ),
                ),
                (
                    "fax",
                    models.CharField(blank=True, max_length=50, verbose_name="팩스"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=500, verbose_name="주소"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="우편번호"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=50, verbose_name="국가"),
                ),
                (
                    "virtual_account_prefix",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="가상 계정 접두사"
                    ),
                ),
                (
                    "default_account_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="기본 계좌번호"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="결제 수단"
                    ),
                ),
                (
                    "transfer_fee_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="이체 수수료율(%)",
                    ),
                ),
                (
                    "erp_sources",
                    models.JSONField(default=dict, verbose_name="ERP 출처"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "마스터 은행",
                "verbose_name_plural": "마스터 은행",
                "db_table": "master_bank",
                "ordering": ["bank_code"],
                "indexes": [
                    models.Index(
                        fields=["bank_code"], name="master_bank_bank_co_228352_idx"
                    ),
                    models.Index(
                        fields=["bank_type"], name="master_bank_bank_ty_6e7e70_idx"
                    ),
                    models.Index(
                        fields=["swift_code"], name="master_bank_swift_c_b30fee_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MasterCustomer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "customer_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="고객사 코드"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=200, verbose_name="고객사명"),
                ),
                (
                    "customer_name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="고객사명(영문)"
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="고객 유형"
                    ),
                ),
                (
                    "industry",
                    models.CharField(blank=True, max_length=100, verbose_name="산업군"),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=100, verbose_name="담당자"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="이메일"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=50, verbose_name="연락처"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=500, verbose_name="주소"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="우편번호"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=50, verbose_name="국가"),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="결제 조건"
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="KRW", max_length=10, verbose_name="통화"),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="신용 한도",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("strategic", "전략"),
                            ("key", "핵심"),
                            ("standard", "일반"),
                            ("small", "소규모"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="등급",
                    ),
                ),
                (
                    "erp_sources",
                    models.JSONField(default=dict, verbose_name="ERP 출처"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "마스터 고객사",
                "verbose_name_plural": "마스터 고객사",
                "db_table": "master_customer",
                "ordering": ["customer_code"],
                "indexes": [
                    models.Index(
                        fields=["customer_code"], name="master_cust_custome_c68959_idx"
                    ),
                    models.Index(
                        fields=["customer_type"], name="master_cust_custome_31ebd6_idx"
                    ),
                    models.Index(fields=["tier"], name="master_cust_tier_888513_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MasterDepartment",
            fields=[
                ("department_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "department_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="부서 코드"
                    ),
                ),
                (
                    "department_name",
                    models.CharField(max_length=100, verbose_name="부서명"),
                ),
                (
                    "department_name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="부서명(영문)"
                    ),
                ),
                ("level", models.IntegerField(default=1, verbose_name="조직 레벨")),
                (
                    "path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="조직 경로"
                    ),
                ),
                (
                    "department_type",
                    models.CharField(
                        choices=[
                            ("executive", "경영진"),
                            ("production", "생산"),
                            ("sales", "영업"),
                            ("purchase", "구매"),
                            ("quality", "품질"),
                            ("finance", "재무"),
                            ("hr", "인사"),
                            ("it", "IT"),
                            ("support", "지원"),
                        ],
                        max_length=50,
                        verbose_name="부서 유형",
                    ),
                ),
                (
                    "cost_center",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="비용 센터"
                    ),
                ),
                (
                    "plant",
                    models.CharField(blank=True, max_length=50, verbose_name="공장"),
                ),
                (
                    "erp_sources",
                    models.JSONField(default=dict, verbose_name="ERP 출처"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "parent_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_departments",
                        to="erp_sync.masterdepartment",
                        verbose_name="상위 부서",
                    ),
                ),
            ],
            options={
                "verbose_name": "마스터 부서",
                "verbose_name_plural": "마스터 부서",
                "db_table": "master_department",
                "ordering": ["level", "department_code"],
            },
        ),
        migrations.CreateModel(
            name="KRIDefinition",
            fields=[
                ("kri_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "kri_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="KRI 코드"
                    ),
                ),
                ("kri_name", models.CharField(max_length=200, verbose_name="KRI명")),
                (
                    "kri_name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="KRI명(영문)"
                    ),
                ),
                (
                    "kri_type",
                    models.CharField(
                        choices=[
                            ("operational", "운영 리스크"),
                            ("financial", "재무 리스크"),
                            ("supply_chain", "공급망 리스크"),
                            ("quality", "품질 리스크"),
                            ("safety", "안전 리스크"),
                            ("compliance", "준수 리스크"),
                            ("strategic", "전략 리스크"),
                        ],
                        max_length=20,
                        verbose_name="KRI 유형",
                    ),
                ),
                ("domain", models.CharField(max_length=50, verbose_name="도메인")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "aggregation_method",
                    models.CharField(max_length=10, verbose_name="집계 방법"),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=20, verbose_name="단위"),
                ),
                (
                    "risk_level_low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="낮은 리스크 기준",
                    ),
                ),
                (
                    "risk_level_medium",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="중간 리스크 기준",
                    ),
                ),
                (
                    "risk_level_high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="높은 리스크 기준",
                    ),
                ),
                (
                    "calculation_logic",
                    models.TextField(blank=True, verbose_name="계산 로직"),
                ),
                (
                    "source_tables",
                    models.JSONField(default=list, verbose_name="원본 테이블"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "owner_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_kris",
                        to="erp_sync.masterdepartment",
                        verbose_name="담당 부서",
                    ),
                ),
            ],
            options={
                "verbose_name": "KRI 정의",
                "verbose_name_plural": "KRI 정의",
                "db_table": "kri_definition",
                "ordering": ["domain", "kri_code"],
            },
        ),
        migrations.CreateModel(
            name="KPIDefinition",
            fields=[
                ("kpi_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "kpi_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="KPI 코드"
                    ),
                ),
                ("kpi_name", models.CharField(max_length=200, verbose_name="KPI명")),
                (
                    "kpi_name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="KPI명(영문)"
                    ),
                ),
                (
                    "kpi_type",
                    models.CharField(
                        choices=[
                            ("efficiency", "효율성"),
                            ("quality", "품질"),
                            ("cost", "원가"),
                            ("delivery", "납기"),
                            ("safety", "안전"),
                            ("financial", "재무"),
                            ("productivity", "생산성"),
                        ],
                        max_length=20,
                        verbose_name="KPI 유형",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="cost, financial, production, quality, sales, hr",
                        max_length=50,
                        verbose_name="도메인",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "aggregation_method",
                    models.CharField(
                        choices=[
                            ("sum", "합계"),
                            ("avg", "평균"),
                            ("min", "최소"),
                            ("max", "최대"),
                            ("count", "개수"),
                        ],
                        max_length=10,
                        verbose_name="집계 방법",
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=20, verbose_name="단위"),
                ),
                (
                    "target_direction",
                    models.CharField(
                        choices=[
                            ("high", "높을수록 좋음"),
                            ("low", "낮을수록 좋음"),
                            ("target", "목표값 근접"),
                        ],
                        default="high",
                        max_length=10,
                        verbose_name="목표 방향",
                    ),
                ),
                (
                    "threshold_warning",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="경고 임계값",
                    ),
                ),
                (
                    "threshold_critical",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="위험 임계값",
                    ),
                ),
                (
                    "calculation_logic",
                    models.TextField(
                        blank=True,
                        help_text="SQL 또는 Python 표현식",
                        verbose_name="계산 로직",
                    ),
                ),
                (
                    "source_tables",
                    models.JSONField(default=list, verbose_name="원본 테이블"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "owner_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_kpis",
                        to="erp_sync.masterdepartment",
                        verbose_name="담당 부서",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI 정의",
                "verbose_name_plural": "KPI 정의",
                "db_table": "kpi_definition",
                "ordering": ["domain", "kpi_code"],
            },
        ),
        migrations.CreateModel(
            name="MasterEmployee",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "employee_code",
                    models.CharField(max_length=50, unique=True, verbose_name="사번"),
                ),
                (
                    "employee_name",
                    models.CharField(max_length=100, verbose_name="성명"),
                ),
                (
                    "employee_name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="성명(영문)"
                    ),
                ),
                (
                    "position",
                    models.CharField(blank=True, max_length=50, verbose_name="직위"),
                ),
                (
                    "job_title",
                    models.CharField(blank=True, max_length=100, verbose_name="직책"),
                ),
                (
                    "employment_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="고용 형태"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="이메일"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="전화번호"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(blank=True, max_length=50, verbose_name="휴대폰"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "재직"),
                            ("resigned", "퇴사"),
                            ("on_leave", "휴직"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(blank=True, null=True, verbose_name="입사일"),
                ),
                (
                    "resignation_date",
                    models.DateField(blank=True, null=True, verbose_name="퇴사일"),
                ),
                (
                    "erp_sources",
                    models.JSONField(default=dict, verbose_name="ERP 출처"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="erp_sync.masterdepartment",
                        verbose_name="소속 부서",
                    ),
                ),
            ],
            options={
                "verbose_name": "마스터 직원",
                "verbose_name_plural": "마스터 직원",
                "db_table": "master_employee",
                "ordering": ["employee_code"],
            },
        ),
        migrations.AddField(
            model_name="masterdepartment",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_departments",
                to="erp_sync.masteremployee",
                verbose_name="부서장",
            ),
        ),
        migrations.CreateModel(
            name="MasterEquipment",
            fields=[
                ("equipment_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "equipment_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="설비 코드"
                    ),
                ),
                (
                    "equipment_name",
                    models.CharField(max_length=200, verbose_name="설비명"),
                ),
                (
                    "equipment_name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="설비명(영문)"
                    ),
                ),
                (
                    "equipment_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="설비 유형"
                    ),
                ),
                (
                    "equipment_category",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="설비 분류"
                    ),
                ),
                (
                    "plant",
                    models.CharField(blank=True, max_length=50, verbose_name="공장"),
                ),
                (
                    "line",
                    models.CharField(blank=True, max_length=50, verbose_name="라인"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="위치"),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=100, verbose_name="제조사"),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, verbose_name="모델"),
                ),
                (
                    "capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="용량",
                    ),
                ),
                (
                    "capacity_unit",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="용량 단위"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("operational", "가동"),
                            ("maintenance", "정비"),
                            ("breakdown", "고장"),
                            ("idle", "유휴"),
                            ("retired", "폐기"),
                        ],
                        default="operational",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "installation_date",
                    models.DateField(blank=True, null=True, verbose_name="설치일"),
                ),
                (
                    "warranty_expiry",
                    models.DateField(blank=True, null=True, verbose_name="보증 만료일"),
                ),
                (
                    "erp_sources",
                    models.JSONField(default=dict, verbose_name="ERP 출처"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "responsible_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_equipments",
                        to="erp_sync.masteremployee",
                        verbose_name="설비 담당자",
                    ),
                ),
            ],
            options={
                "verbose_name": "마스터 설비",
                "verbose_name_plural": "마스터 설비",
                "db_table": "master_equipment",
                "ordering": ["plant", "line", "equipment_code"],
            },
        ),
        migrations.CreateModel(
            name="MasterProcess",
            fields=[
                ("process_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "process_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="공정 코드"
                    ),
                ),
                (
                    "process_name",
                    models.CharField(max_length=200, verbose_name="공정명"),
                ),
                (
                    "process_name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="공정명(영문)"
                    ),
                ),
                (
                    "process_type",
                    models.CharField(
                        choices=[
                            ("casting", "주조"),
                            ("machining", "가공"),
                            ("forming", "성형"),
                            ("assembly", "조립"),
                            ("inspection", "검사"),
                            ("packing", "포장"),
                            ("heat_treatment", "열처리"),
                            ("surface_treatment", "표면처리"),
                            ("testing", "시험"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                        verbose_name="공정 유형",
                    ),
                ),
                (
                    "process_category",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="공정 분류"
                    ),
                ),
                (
                    "plant",
                    models.CharField(blank=True, max_length=50, verbose_name="공장"),
                ),
                (
                    "line",
                    models.CharField(blank=True, max_length=50, verbose_name="라인"),
                ),
                (
                    "work_center",
                    models.CharField(blank=True, max_length=50, verbose_name="작업장"),
                ),
                (
                    "standard_cycle_time",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="표준 공시간(초)",
                    ),
                ),
                (
                    "standard_setup_time",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="표준 준비 시간(분)",
                    ),
                ),
                (
                    "standard_capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="표준 능률(개/시)",
                    ),
                ),
                (
                    "quality_standard",
                    models.TextField(blank=True, verbose_name="품질 기준"),
                ),
                (
                    "acceptance_criteria",
                    models.TextField(blank=True, verbose_name="합격 기준"),
                ),
                (
                    "erp_sources",
                    models.JSONField(default=dict, verbose_name="ERP 출처"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "equipment",
                    models.ManyToManyField(
                        blank=True,
                        related_name="processes",
                        to="erp_sync.masterequipment",
                        verbose_name="관련 설비",
                    ),
                ),
                (
                    "responsible_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_processes",
                        to="erp_sync.masteremployee",
                        verbose_name="공정 담당자",
                    ),
                ),
            ],
            options={
                "verbose_name": "마스터 공정",
                "verbose_name_plural": "마스터 공정",
                "db_table": "master_process",
                "ordering": ["plant", "line", "process_code"],
            },
        ),
        migrations.CreateModel(
            name="IntegratedSalesOrder",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "order_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="오더 번호"
                    ),
                ),
                (
                    "customer_po",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="고객 PO 번호"
                    ),
                ),
                (
                    "quantity_ordered",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="주문 수량"
                    ),
                ),
                (
                    "quantity_shipped",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="출하 수량",
                    ),
                ),
                (
                    "quantity_invoiced",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="청구 수량",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="단가"
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="KRW", max_length=10, verbose_name="통화"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="총액"
                    ),
                ),
                ("order_date", models.DateField(verbose_name="주문일자")),
                ("request_date", models.DateField(verbose_name="납품 요청일")),
                ("promise_date", models.DateField(verbose_name="납품 약속일")),
                (
                    "actual_shipment_date",
                    models.DateField(blank=True, null=True, verbose_name="실제 출하일"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "작성중"),
                            ("confirmed", "확정"),
                            ("in_production", "생산중"),
                            ("shipped", "출하완료"),
                            ("invoiced", "청구완료"),
                            ("cancelled", "취소"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "progress",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="진행률(%)",
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="비고")),
                (
                    "erp_sources",
                    models.JSONField(default=dict, verbose_name="ERP 출처"),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(auto_now=True, verbose_name="마지막 동기화"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders",
                        to="erp_sync.mastercustomer",
                        verbose_name="고객사",
                    ),
                ),
                (
                    "sales_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_orders",
                        to="erp_sync.masteremployee",
                        verbose_name="영업 담당자",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders",
                        to="erp_sync.masterproduct",
                        verbose_name="제품",
                    ),
                ),
            ],
            options={
                "verbose_name": "통합 영업 오더",
                "verbose_name_plural": "통합 영업 오더",
                "db_table": "integrated_sales_order",
                "ordering": ["-order_date", "order_number"],
            },
        ),
        migrations.CreateModel(
            name="IntegratedQualityRecord",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "record_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="기록 번호"
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("incoming", "입고검사"),
                            ("in_process", "공정검사"),
                            ("final", "최종검사"),
                            ("shipping", "출하검사"),
                            ("customer_claim", "고객클레임"),
                        ],
                        max_length=20,
                        verbose_name="기록 유형",
                    ),
                ),
                (
                    "lot_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="LOT 번호"
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="배치 번호"
                    ),
                ),
                (
                    "inspection_quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="검사 수량"
                    ),
                ),
                (
                    "ok_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="합격 수량",
                    ),
                ),
                (
                    "ng_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="불량 수량",
                    ),
                ),
                (
                    "rework_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="재작업 수량",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("accepted", "합격"),
                            ("rejected", "불합격"),
                            ("conditional", "조건부합격"),
                            ("rework", "재작업"),
                        ],
                        max_length=20,
                        verbose_name="검사 결과",
                    ),
                ),
                (
                    "defect_types",
                    models.JSONField(default=list, verbose_name="불량 유형"),
                ),
                (
                    "defect_details",
                    models.TextField(blank=True, verbose_name="불량 상세"),
                ),
                ("inspection_date", models.DateField(verbose_name="검사일자")),
                (
                    "claim_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="클레임 번호"
                    ),
                ),
                (
                    "capa_required",
                    models.BooleanField(default=False, verbose_name="CAPA 필요"),
                ),
                (
                    "capa_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="CAPA 번호"
                    ),
                ),
                (
                    "capa_due_date",
                    models.DateField(blank=True, null=True, verbose_name="CAPA 기한"),
                ),
                (
                    "capa_status",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="CAPA 상태"
                    ),
                ),
                (
                    "erp_sources",
                    models.JSONField(default=dict, verbose_name="ERP 출처"),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(auto_now=True, verbose_name="마지막 동기화"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_records",
                        to="erp_sync.mastercustomer",
                        verbose_name="고객사",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections",
                        to="erp_sync.masteremployee",
                        verbose_name="검사자",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_records",
                        to="erp_sync.masterproduct",
                        verbose_name="제품",
                    ),
                ),
            ],
            options={
                "verbose_name": "통합 품질 기록",
                "verbose_name_plural": "통합 품질 기록",
                "db_table": "integrated_quality_record",
                "ordering": ["-inspection_date", "record_number"],
            },
        ),
        migrations.CreateModel(
            name="IntegratedProductionOrder",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "order_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="오더 번호"
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("standard", "표준"),
                            ("rework", "재작업"),
                            ("disassembly", "분해"),
                            ("rush", "긴급"),
                        ],
                        max_length=20,
                        verbose_name="오더 유형",
                    ),
                ),
                (
                    "quantity_ordered",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="계획 수량"
                    ),
                ),
                (
                    "quantity_produced",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="생산 수량",
                    ),
                ),
                (
                    "quantity_scrapped",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="폐기 수량",
                    ),
                ),
                ("plant", models.CharField(max_length=50, verbose_name="공장")),
                (
                    "line",
                    models.CharField(blank=True, max_length=50, verbose_name="라인"),
                ),
                ("start_date_scheduled", models.DateField(verbose_name="계획 시작일")),
                (
                    "start_date_actual",
                    models.DateField(blank=True, null=True, verbose_name="실제 시작일"),
                ),
                ("end_date_scheduled", models.DateField(verbose_name="계획 종료일")),
                (
                    "end_date_actual",
                    models.DateField(blank=True, null=True, verbose_name="실제 종료일"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "생성"),
                            ("released", "해제"),
                            ("in_progress", "진행중"),
                            ("completed", "완료"),
                            ("cancelled", "취소"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "progress",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="진행률(%)",
                    ),
                ),
                (
                    "standard_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="표준 원가",
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="실제 원가",
                    ),
                ),
                (
                    "erp_sources",
                    models.JSONField(default=dict, verbose_name="ERP 출처"),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(auto_now=True, verbose_name="마지막 동기화"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "production_supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_orders",
                        to="erp_sync.masteremployee",
                        verbose_name="생산 담당자",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_orders",
                        to="erp_sync.masterequipment",
                        verbose_name="설비",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_orders",
                        to="erp_sync.masterproduct",
                        verbose_name="제품",
                    ),
                ),
            ],
            options={
                "verbose_name": "통합 생산 오더",
                "verbose_name_plural": "통합 생산 오더",
                "db_table": "integrated_production_order",
                "ordering": ["-start_date_scheduled", "order_number"],
            },
        ),
        migrations.CreateModel(
            name="MasterVendor",
            fields=[
                ("vendor_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "vendor_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="공급처 코드"
                    ),
                ),
                (
                    "vendor_name",
                    models.CharField(max_length=200, verbose_name="공급처명"),
                ),
                (
                    "vendor_name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="공급처명(영문)"
                    ),
                ),
                (
                    "vendor_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="공급처 유형"
                    ),
                ),
                (
                    "business_type",
                    models.CharField(blank=True, max_length=50, verbose_name="업태"),
                ),
                (
                    "business_category",
                    models.CharField(blank=True, max_length=50, verbose_name="업종"),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=100, verbose_name="담당자"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="이메일"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=50, verbose_name="연락처"),
                ),
                (
                    "fax",
                    models.CharField(blank=True, max_length=50, verbose_name="팩스"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=500, verbose_name="주소"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="우편번호"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=50, verbose_name="국가"),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=50, verbose_name="지역"),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="결제 조건"
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="KRW", max_length=10, verbose_name="통화"),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="신용 한도",
                    ),
                ),
                (
                    "rating",
                    models.CharField(blank=True, max_length=10, verbose_name="등급"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "낮음"),
                            ("medium", "중간"),
                            ("high", "높음"),
                            ("critical", "매우높음"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="리스크 수준",
                    ),
                ),
                (
                    "erp_sources",
                    models.JSONField(default=dict, verbose_name="ERP 출처"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "마스터 공급처",
                "verbose_name_plural": "마스터 공급처",
                "db_table": "master_vendor",
                "ordering": ["vendor_code"],
                "indexes": [
                    models.Index(
                        fields=["vendor_code"], name="master_vend_vendor__1dbb06_idx"
                    ),
                    models.Index(
                        fields=["vendor_type"], name="master_vend_vendor__646fad_idx"
                    ),
                    models.Index(
                        fields=["risk_level"], name="master_vend_risk_le_2690f1_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="masterproduct",
            name="primary_vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_products",
                to="erp_sync.mastervendor",
                verbose_name="주 공급처",
            ),
        ),
        migrations.CreateModel(
            name="KRIFact",
            fields=[
                (
                    "fact_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="날짜")),
                ("year", models.IntegerField(db_index=True, verbose_name="년")),
                ("quarter", models.IntegerField(db_index=True, verbose_name="분기")),
                ("month", models.IntegerField(db_index=True, verbose_name="월")),
                (
                    "plant",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, verbose_name="공장"
                    ),
                ),
                (
                    "line",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, verbose_name="라인"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, verbose_name="부서"
                    ),
                ),
                (
                    "actual_value",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="실제값"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "낮음"),
                            ("medium", "중간"),
                            ("high", "높음"),
                            ("critical", "매우높음"),
                        ],
                        default="low",
                        max_length=20,
                        verbose_name="리스크 수준",
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="리스크 점수",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "source_system",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="출처 시스템"
                    ),
                ),
                (
                    "source_table",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="출처 테이블"
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="계산 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시각"),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="메타데이터")),
                (
                    "kri",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="erp_sync.kridefinition",
                        verbose_name="KRI",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kri_facts",
                        to="erp_sync.mastervendor",
                        verbose_name="공급처",
                    ),
                ),
            ],
            options={
                "verbose_name": "KRI 팩트",
                "verbose_name_plural": "KRI 팩트",
                "db_table": "kri_fact",
                "ordering": ["-date", "kri"],
            },
        ),
        migrations.CreateModel(
            name="KPIFact",
            fields=[
                (
                    "fact_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="날짜")),
                ("year", models.IntegerField(db_index=True, verbose_name="년")),
                ("quarter", models.IntegerField(db_index=True, verbose_name="분기")),
                ("month", models.IntegerField(db_index=True, verbose_name="월")),
                ("week", models.IntegerField(blank=True, null=True, verbose_name="주")),
                (
                    "plant",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, verbose_name="공장"
                    ),
                ),
                (
                    "line",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, verbose_name="라인"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, verbose_name="부서"
                    ),
                ),
                (
                    "actual_value",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="실적값"
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="목표값",
                    ),
                ),
                (
                    "baseline_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="기준값",
                    ),
                ),
                (
                    "achievement_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="달성율(%)",
                    ),
                ),
                (
                    "variance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="차이",
                    ),
                ),
                (
                    "variance_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="차이율(%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("good", "양호"),
                            ("warning", "주의"),
                            ("critical", "위험"),
                            ("neutral", "중립"),
                        ],
                        default="neutral",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="출처 시스템"
                    ),
                ),
                (
                    "source_table",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="출처 테이블"
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="계산 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시각"),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="메타데이터")),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="erp_sync.kpidefinition",
                        verbose_name="KPI",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kpi_facts",
                        to="erp_sync.mastercustomer",
                        verbose_name="고객사",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kpi_facts",
                        to="erp_sync.masterproduct",
                        verbose_name="제품",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kpi_facts",
                        to="erp_sync.mastervendor",
                        verbose_name="공급처",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI 팩트",
                "verbose_name_plural": "KPI 팩트",
                "db_table": "kpi_fact",
                "ordering": ["-date", "kpi"],
            },
        ),
        migrations.CreateModel(
            name="IntegratedMaterial",
            fields=[
                ("material_id", models.AutoField(primary_key=True, serialize=False)),
                ("plant", models.CharField(max_length=50, verbose_name="공장")),
                (
                    "warehouse",
                    models.CharField(blank=True, max_length=50, verbose_name="창고"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="위치"),
                ),
                (
                    "quantity_on_hand",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="현재고량",
                    ),
                ),
                (
                    "quantity_reserved",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="예약된 수량",
                    ),
                ),
                (
                    "quantity_available",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="가용 수량",
                    ),
                ),
                (
                    "safety_stock",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="안전 재고",
                    ),
                ),
                (
                    "moving_average_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="이동 평균 단가",
                    ),
                ),
                (
                    "standard_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="표준 단가",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="총 재고 가액",
                    ),
                ),
                (
                    "lead_time_days",
                    models.IntegerField(default=0, verbose_name="리드타임(일)"),
                ),
                (
                    "last_receipt_date",
                    models.DateField(blank=True, null=True, verbose_name="최종 입고일"),
                ),
                (
                    "last_issue_date",
                    models.DateField(blank=True, null=True, verbose_name="최종 출고일"),
                ),
                (
                    "turnover_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="회전율",
                    ),
                ),
                (
                    "days_of_supply",
                    models.IntegerField(default=0, verbose_name="공급 가능 일수"),
                ),
                (
                    "is_abcs",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="ABC 분류"
                    ),
                ),
                (
                    "is_slow_moving",
                    models.BooleanField(default=False, verbose_name="저회전 여부"),
                ),
                (
                    "erp_sources",
                    models.JSONField(default=dict, verbose_name="ERP 출처"),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(auto_now=True, verbose_name="마지막 동기화"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to="erp_sync.masterproduct",
                        verbose_name="제품",
                    ),
                ),
                (
                    "primary_vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplied_materials",
                        to="erp_sync.mastervendor",
                        verbose_name="주 공급처",
                    ),
                ),
            ],
            options={
                "verbose_name": "통합 자재",
                "verbose_name_plural": "통합 자재",
                "db_table": "integrated_material",
                "ordering": ["plant", "warehouse", "product"],
            },
        ),
        migrations.CreateModel(
            name="MasterWarehouse",
            fields=[
                ("warehouse_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "warehouse_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="창고 코드"
                    ),
                ),
                (
                    "warehouse_name",
                    models.CharField(max_length=200, verbose_name="창고명"),
                ),
                (
                    "warehouse_name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="창고명(영문)"
                    ),
                ),
                (
                    "warehouse_type",
                    models.CharField(
                        choices=[
                            ("raw_material", "원자재 창고"),
                            ("finished_good", "완제품 창고"),
                            ("semi_finished", "반제품 창고"),
                            ("component", "부품 창고"),
                            ("consumable", "소모품 창고"),
                            ("general", "일반 창고"),
                        ],
                        max_length=20,
                        verbose_name="창고 유형",
                    ),
                ),
                (
                    "plant",
                    models.CharField(blank=True, max_length=50, verbose_name="공장"),
                ),
                (
                    "building",
                    models.CharField(blank=True, max_length=50, verbose_name="건물"),
                ),
                (
                    "floor",
                    models.CharField(blank=True, max_length=20, verbose_name="층"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="위치"),
                ),
                (
                    "capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="용량",
                    ),
                ),
                (
                    "capacity_unit",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="용량 단위"
                    ),
                ),
                (
                    "current_utilization",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="현재 사용률(%)",
                    ),
                ),
                (
                    "temperature_controlled",
                    models.BooleanField(default=False, verbose_name="온도 제어 여부"),
                ),
                (
                    "temperature_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="최저 온도(°C)",
                    ),
                ),
                (
                    "temperature_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="최고 온도(°C)",
                    ),
                ),
                (
                    "erp_sources",
                    models.JSONField(default=dict, verbose_name="ERP 출처"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_warehouses",
                        to="erp_sync.masteremployee",
                        verbose_name="창고 관리자",
                    ),
                ),
            ],
            options={
                "verbose_name": "마스터 창고",
                "verbose_name_plural": "마스터 창고",
                "db_table": "master_warehouse",
                "ordering": ["plant", "warehouse_code"],
            },
        ),
        migrations.CreateModel(
            name="MasterAccount",
            fields=[
                ("account_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "account_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="계정 코드"
                    ),
                ),
                (
                    "account_name",
                    models.CharField(max_length=200, verbose_name="계정과목명"),
                ),
                (
                    "account_name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="계정과목명(영문)"
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "자산"),
                            ("liability", "부채"),
                            ("equity", "자본"),
                            ("revenue", "수익"),
                            ("expense", "비용"),
                        ],
                        max_length=20,
                        verbose_name="계정 유형",
                    ),
                ),
                (
                    "category_l1",
                    models.CharField(blank=True, max_length=50, verbose_name="대분류"),
                ),
                (
                    "category_l2",
                    models.CharField(blank=True, max_length=50, verbose_name="중분류"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "is_consolidated",
                    models.BooleanField(default=False, verbose_name="통합 항목 여부"),
                ),
                (
                    "is_tax_related",
                    models.BooleanField(default=True, verbose_name="세무 관련 여부"),
                ),
                (
                    "tax_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="세목 코드"
                    ),
                ),
                (
                    "erp_sources",
                    models.JSONField(default=dict, verbose_name="ERP 출처"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "control_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_accounts",
                        to="erp_sync.masteraccount",
                        verbose_name="통제 계정",
                    ),
                ),
            ],
            options={
                "verbose_name": "마스터 계정과목",
                "verbose_name_plural": "마스터 계정과목",
                "db_table": "master_account",
                "ordering": ["account_code"],
                "indexes": [
                    models.Index(
                        fields=["account_code"], name="master_acco_account_005beb_idx"
                    ),
                    models.Index(
                        fields=["account_type"], name="master_acco_account_c62509_idx"
                    ),
                    models.Index(
                        fields=["category_l1", "category_l2"],
                        name="master_acco_categor_4e4732_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="kridefinition",
            index=models.Index(
                fields=["kri_code"], name="kri_definit_kri_cod_b53568_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kridefinition",
            index=models.Index(
                fields=["kri_type"], name="kri_definit_kri_typ_a50d1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kridefinition",
            index=models.Index(fields=["domain"], name="kri_definit_domain_4d8a00_idx"),
        ),
        migrations.AddIndex(
            model_name="kpidefinition",
            index=models.Index(
                fields=["kpi_code"], name="kpi_definit_kpi_cod_c5571b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kpidefinition",
            index=models.Index(
                fields=["kpi_type"], name="kpi_definit_kpi_typ_084991_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kpidefinition",
            index=models.Index(fields=["domain"], name="kpi_definit_domain_ee6354_idx"),
        ),
        migrations.AddIndex(
            model_name="masteremployee",
            index=models.Index(
                fields=["employee_code"], name="master_empl_employe_7a15d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="masteremployee",
            index=models.Index(
                fields=["department"], name="master_empl_departm_81e5f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="masteremployee",
            index=models.Index(fields=["status"], name="master_empl_status_c936f9_idx"),
        ),
        migrations.AddIndex(
            model_name="masterdepartment",
            index=models.Index(
                fields=["department_code"], name="master_depa_departm_e2963b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="masterdepartment",
            index=models.Index(
                fields=["department_type"], name="master_depa_departm_e853b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="masterdepartment",
            index=models.Index(fields=["level"], name="master_depa_level_ca53a2_idx"),
        ),
        migrations.AddIndex(
            model_name="masterequipment",
            index=models.Index(
                fields=["equipment_code"], name="master_equi_equipme_59840b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="masterequipment",
            index=models.Index(
                fields=["equipment_type"], name="master_equi_equipme_e3c71f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="masterequipment",
            index=models.Index(
                fields=["plant", "line"], name="master_equi_plant_bcf47f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="masterequipment",
            index=models.Index(fields=["status"], name="master_equi_status_a7dc14_idx"),
        ),
        migrations.AddIndex(
            model_name="masterprocess",
            index=models.Index(
                fields=["process_code"], name="master_proc_process_acb796_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="masterprocess",
            index=models.Index(
                fields=["process_type"], name="master_proc_process_42a2f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="masterprocess",
            index=models.Index(
                fields=["plant", "line"], name="master_proc_plant_e3a7ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integratedsalesorder",
            index=models.Index(
                fields=["order_number"], name="integrated__order_n_a23d10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integratedsalesorder",
            index=models.Index(fields=["status"], name="integrated__status_3889e1_idx"),
        ),
        migrations.AddIndex(
            model_name="integratedsalesorder",
            index=models.Index(
                fields=["customer"], name="integrated__custome_382d25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integratedsalesorder",
            index=models.Index(
                fields=["order_date"], name="integrated__order_d_9a29f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integratedqualityrecord",
            index=models.Index(
                fields=["record_number"], name="integrated__record__dfff5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integratedqualityrecord",
            index=models.Index(
                fields=["record_type"], name="integrated__record__05febe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integratedqualityrecord",
            index=models.Index(
                fields=["inspection_date"], name="integrated__inspect_0395bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integratedqualityrecord",
            index=models.Index(fields=["result"], name="integrated__result_6444f0_idx"),
        ),
        migrations.AddIndex(
            model_name="integratedqualityrecord",
            index=models.Index(
                fields=["product"], name="integrated__product_ee560a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integratedproductionorder",
            index=models.Index(
                fields=["order_number"], name="integrated__order_n_b46385_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integratedproductionorder",
            index=models.Index(fields=["status"], name="integrated__status_06a030_idx"),
        ),
        migrations.AddIndex(
            model_name="integratedproductionorder",
            index=models.Index(
                fields=["start_date_scheduled"], name="integrated__start_d_70e31a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integratedproductionorder",
            index=models.Index(
                fields=["product"], name="integrated__product_b21ac3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="masterproduct",
            index=models.Index(
                fields=["product_code"], name="master_prod_product_c93e89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="masterproduct",
            index=models.Index(
                fields=["product_type"], name="master_prod_product_8f9f96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="masterproduct",
            index=models.Index(
                fields=["category_l1", "category_l2"],
                name="master_prod_categor_b864b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="krifact",
            index=models.Index(
                fields=["kri", "date"], name="kri_fact_kri_id_f7b745_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="krifact",
            index=models.Index(
                fields=["date", "plant"], name="kri_fact_date_10d652_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="krifact",
            index=models.Index(
                fields=["year", "month"], name="kri_fact_year_47e543_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="krifact",
            unique_together={("kri", "date", "plant", "line", "vendor")},
        ),
        migrations.AddIndex(
            model_name="kpifact",
            index=models.Index(
                fields=["kpi", "date"], name="kpi_fact_kpi_id_582aeb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kpifact",
            index=models.Index(
                fields=["date", "plant"], name="kpi_fact_date_0abe0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kpifact",
            index=models.Index(
                fields=["year", "month"], name="kpi_fact_year_48c036_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="kpifact",
            unique_together={("kpi", "date", "plant", "line", "product")},
        ),
        migrations.AddIndex(
            model_name="integratedmaterial",
            index=models.Index(
                fields=["product", "plant"], name="integrated__product_543ca2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integratedmaterial",
            index=models.Index(
                fields=["quantity_available"], name="integrated__quantit_1b099e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integratedmaterial",
            index=models.Index(
                fields=["last_synced_at"], name="integrated__last_sy_c7bb9b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="integratedmaterial",
            unique_together={("product", "plant", "warehouse")},
        ),
        migrations.AddIndex(
            model_name="masterwarehouse",
            index=models.Index(
                fields=["warehouse_code"], name="master_ware_warehou_c0e3a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="masterwarehouse",
            index=models.Index(
                fields=["warehouse_type"], name="master_ware_warehou_9bec0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="masterwarehouse",
            index=models.Index(fields=["plant"], name="master_ware_plant_46975f_idx"),
        ),
    ]
