# Generated by Django 5.2.13 on 2026-07-05 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_sync", "0009_masterproduct_masterbank_mastercustomer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ERPConnectionConfigModel",
            fields=[
                ("config_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "source_code",
                    models.CharField(
                        help_text="YH, FOM, LOCAL 등 시스템 식별 코드",
                        max_length=20,
                        unique=True,
                        verbose_name="소스 코드",
                    ),
                ),
                (
                    "source_name",
                    models.CharField(max_length=100, verbose_name="소스명"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("postgresql", "PostgreSQL"),
                            ("mssql", "SQL Server"),
                            ("mysql", "MySQL"),
                            ("sqlite", "SQLite"),
                        ],
                        default="postgresql",
                        max_length=20,
                        verbose_name="소스 타입",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "host",
                    models.CharField(blank=True, max_length=255, verbose_name="호스트"),
                ),
                (
                    "port",
                    models.IntegerField(blank=True, null=True, verbose_name="포트"),
                ),
                (
                    "database_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="데이터베이스"
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(blank=True, max_length=100, verbose_name="스키마"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="사용자명"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="비밀번호"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="False인 경우 원격 연결 시도하지 않음",
                        verbose_name="활성화 여부",
                    ),
                ),
                (
                    "use_fallback",
                    models.BooleanField(
                        default=True,
                        help_text="연결 실패 시 로컬 백업 DB 사용",
                        verbose_name="폴백 사용",
                    ),
                ),
                (
                    "connection_timeout",
                    models.IntegerField(default=10, verbose_name="연결 타임아웃(초)"),
                ),
                (
                    "query_timeout",
                    models.IntegerField(default=30, verbose_name="쿼리 타임아웃(초)"),
                ),
                (
                    "max_retry_attempts",
                    models.IntegerField(default=3, verbose_name="최대 재시도 횟수"),
                ),
                (
                    "cooldown_seconds",
                    models.IntegerField(default=300, verbose_name="쿨다운(초)"),
                ),
                (
                    "suppress_errors",
                    models.BooleanField(
                        default=True,
                        help_text="True인 경우 연결 에러를 DEBUG 레벨로만 기록",
                        verbose_name="에러 억제",
                    ),
                ),
                (
                    "last_connection_attempt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 연결 시도"
                    ),
                ),
                (
                    "last_connection_success",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 연결 성공"
                    ),
                ),
                (
                    "last_connection_error",
                    models.TextField(blank=True, verbose_name="마지막 연결 에러"),
                ),
                (
                    "failure_count",
                    models.IntegerField(default=0, verbose_name="실패 횟수"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "fallback_source",
                    models.ForeignKey(
                        blank=True,
                        help_text="연결 실패 시 사용할 로컬 백업 DB 소스",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="erp_sync.erpconnectionconfigmodel",
                        verbose_name="폴백 소스",
                    ),
                ),
            ],
            options={
                "verbose_name": "ERP 연결 설정",
                "verbose_name_plural": "ERP 연결 설정",
                "db_table": "erp_connection_config",
                "ordering": ["source_code"],
            },
        ),
    ]
