# Generated by Django 5.0.1 on 2025-12-25 01:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="라인명")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="라인 코드"
                    ),
                ),
                ("location", models.CharField(max_length=200, verbose_name="위치")),
                (
                    "capacity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="일일 생산능력",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="가동 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "생산 라인",
                "verbose_name_plural": "생산 라인",
                "db_table": "production_lines",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="설비명")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="설비 코드"
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(max_length=200, verbose_name="제조사"),
                ),
                ("model", models.CharField(max_length=200, verbose_name="모델명")),
                ("purchase_date", models.DateField(verbose_name="구매일자")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "가동중"),
                            ("idle", "대기"),
                            ("maintenance", "정비중"),
                            ("breakdown", "고장"),
                        ],
                        default="idle",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "last_maintenance",
                    models.DateField(blank=True, null=True, verbose_name="최근 정비일"),
                ),
                (
                    "next_maintenance",
                    models.DateField(
                        blank=True, null=True, verbose_name="다음 정비 예정일"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "production_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="production.productionline",
                        verbose_name="생산 라인",
                    ),
                ),
            ],
            options={
                "verbose_name": "생산 설비",
                "verbose_name_plural": "생산 설비",
                "db_table": "equipment",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="작업지시 번호"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="제품명"),
                ),
                (
                    "product_code",
                    models.CharField(max_length=100, verbose_name="제품 코드"),
                ),
                (
                    "target_quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="목표 수량",
                    ),
                ),
                (
                    "actual_quantity",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="실제 생산량",
                    ),
                ),
                (
                    "defect_quantity",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="불량 수량",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "계획"),
                            ("in_progress", "진행중"),
                            ("completed", "완료"),
                            ("cancelled", "취소"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("planned_start", models.DateTimeField(verbose_name="계획 시작일시")),
                ("planned_end", models.DateTimeField(verbose_name="계획 종료일시")),
                (
                    "actual_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="실제 시작일시"
                    ),
                ),
                (
                    "actual_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="실제 종료일시"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "production_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_orders",
                        to="production.productionline",
                        verbose_name="생산 라인",
                    ),
                ),
            ],
            options={
                "verbose_name": "작업 지시서",
                "verbose_name_plural": "작업 지시서",
                "db_table": "work_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("production_date", models.DateField(verbose_name="생산일자")),
                ("target_quantity", models.IntegerField(verbose_name="목표 생산량")),
                ("actual_quantity", models.IntegerField(verbose_name="실제 생산량")),
                (
                    "defect_quantity",
                    models.IntegerField(default=0, verbose_name="불량 수량"),
                ),
                (
                    "operating_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="가동 시간",
                    ),
                ),
                (
                    "downtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="비가동 시간",
                    ),
                ),
                (
                    "efficiency",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="생산 효율 (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "production_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_productions",
                        to="production.productionline",
                        verbose_name="생산 라인",
                    ),
                ),
            ],
            options={
                "verbose_name": "일일 생산 실적",
                "verbose_name_plural": "일일 생산 실적",
                "db_table": "daily_productions",
                "ordering": ["-production_date"],
                "unique_together": {("production_line", "production_date")},
            },
        ),
    ]
