# Generated by Django 5.0.1 on 2025-12-24 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InnovationMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("product", "제품혁신"),
                            ("process", "공정혁신"),
                            ("service", "서비스혁신"),
                            ("business", "비즈니스혁신"),
                        ],
                        max_length=20,
                        verbose_name="분류",
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(max_length=100, verbose_name="지표명"),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="목표값",
                    ),
                ),
                (
                    "actual_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="실적값",
                    ),
                ),
                (
                    "achievement_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="달성률 (%)",
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=50, verbose_name="단위"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "혁신 지표",
                "verbose_name_plural": "혁신 지표",
                "db_table": "development_innovation_metric",
                "ordering": ["-fiscal_year", "-fiscal_month", "category"],
            },
        ),
        migrations.CreateModel(
            name="Patent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="등록번호"
                    ),
                ),
                (
                    "application_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="출원번호"
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="명칭")),
                (
                    "ip_type",
                    models.CharField(
                        choices=[
                            ("patent", "특허"),
                            ("utility", "실용신안"),
                            ("design", "디자인"),
                            ("trademark", "상표"),
                        ],
                        default="patent",
                        max_length=20,
                        verbose_name="유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("filed", "출원"),
                            ("pending", "심사중"),
                            ("granted", "등록"),
                            ("rejected", "거절"),
                            ("expired", "만료"),
                        ],
                        default="filed",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("inventor", models.CharField(max_length=200, verbose_name="발명자")),
                ("applicant", models.CharField(max_length=200, verbose_name="출원인")),
                ("application_date", models.DateField(verbose_name="출원일")),
                (
                    "registration_date",
                    models.DateField(blank=True, null=True, verbose_name="등록일"),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="만료일"),
                ),
                (
                    "related_project",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="관련 프로젝트"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "특허/지식재산권",
                "verbose_name_plural": "특허/지식재산권",
                "db_table": "development_patent",
                "ordering": ["-application_date"],
            },
        ),
        migrations.CreateModel(
            name="RDPersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(max_length=50, unique=True, verbose_name="사번"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("department", models.CharField(max_length=100, verbose_name="부서")),
                ("position", models.CharField(max_length=100, verbose_name="직위")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("junior", "주니어"),
                            ("senior", "시니어"),
                            ("lead", "리드"),
                            ("manager", "매니저"),
                            ("director", "디렉터"),
                        ],
                        default="junior",
                        max_length=20,
                        verbose_name="등급",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(max_length=200, verbose_name="전문분야"),
                ),
                (
                    "years_of_experience",
                    models.IntegerField(default=0, verbose_name="경력 연수"),
                ),
                (
                    "current_project",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="현재 프로젝트"
                    ),
                ),
                (
                    "publications",
                    models.IntegerField(default=0, verbose_name="논문 수"),
                ),
                ("patents", models.IntegerField(default=0, verbose_name="특허 수")),
                ("join_date", models.DateField(verbose_name="입사일")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "R&D 인력",
                "verbose_name_plural": "R&D 인력",
                "db_table": "development_rd_personnel",
                "ordering": ["department", "name"],
            },
        ),
        migrations.CreateModel(
            name="RDProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="프로젝트 ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="프로젝트명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "기획"),
                            ("research", "연구"),
                            ("development", "개발"),
                            ("testing", "시험"),
                            ("completed", "완료"),
                            ("cancelled", "취소"),
                        ],
                        default="planning",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "높음"), ("medium", "보통"), ("low", "낮음")],
                        default="medium",
                        max_length=10,
                        verbose_name="우선순위",
                    ),
                ),
                (
                    "progress",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="진행률 (%)",
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="예산 (억원)",
                    ),
                ),
                (
                    "spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="사용액 (억원)",
                    ),
                ),
                ("team_lead", models.CharField(max_length=100, verbose_name="팀장")),
                ("team_size", models.IntegerField(default=0, verbose_name="팀 인원")),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("target_date", models.DateField(verbose_name="목표 완료일")),
                (
                    "actual_end_date",
                    models.DateField(blank=True, null=True, verbose_name="실제 완료일"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "R&D 프로젝트",
                "verbose_name_plural": "R&D 프로젝트",
                "db_table": "development_rd_project",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TechnologyRoadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "technology_name",
                    models.CharField(max_length=200, verbose_name="기술명"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("short-term", "단기 (1년 이내)"),
                            ("mid-term", "중기 (1-3년)"),
                            ("long-term", "장기 (3년 이상)"),
                        ],
                        default="short-term",
                        max_length=20,
                        verbose_name="단계",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "계획"),
                            ("in-progress", "진행중"),
                            ("completed", "완료"),
                            ("delayed", "지연"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "progress",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="진행률 (%)",
                    ),
                ),
                ("target_year", models.IntegerField(verbose_name="목표 연도")),
                (
                    "expected_impact",
                    models.TextField(blank=True, verbose_name="기대 효과"),
                ),
                (
                    "required_investment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="필요 투자액 (억원)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "기술 로드맵",
                "verbose_name_plural": "기술 로드맵",
                "db_table": "development_technology_roadmap",
                "ordering": ["target_year", "phase"],
            },
        ),
        migrations.CreateModel(
            name="RDBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                ("category", models.CharField(max_length=100, verbose_name="분류")),
                (
                    "allocated_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="배정 예산 (억원)",
                    ),
                ),
                (
                    "spent_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="집행 예산 (억원)",
                    ),
                ),
                (
                    "remaining_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="잔여 예산 (억원)",
                    ),
                ),
                (
                    "execution_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="집행률 (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "R&D 예산",
                "verbose_name_plural": "R&D 예산",
                "db_table": "development_rd_budget",
                "ordering": ["-fiscal_year", "category"],
                "unique_together": {("fiscal_year", "category")},
            },
        ),
    ]
