# Generated by Django 5.0.1 on 2026-02-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0002_financialstatement_beginning_equity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialstatement",
            name="current_liabilities",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="유동부채"
            ),
        ),
    ]
