# Generated by Django 5.0.1 on 2025-12-24 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialRatio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "roe",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="자기자본이익률",
                        max_digits=5,
                        verbose_name="ROE (%)",
                    ),
                ),
                (
                    "roa",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="총자산이익률",
                        max_digits=5,
                        verbose_name="ROA (%)",
                    ),
                ),
                (
                    "operating_margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="영업이익률 (%)",
                    ),
                ),
                (
                    "net_margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="순이익률 (%)",
                    ),
                ),
                (
                    "debt_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="부채비율 (%)",
                    ),
                ),
                (
                    "current_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="유동비율 (%)",
                    ),
                ),
                (
                    "quick_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="당좌비율 (%)",
                    ),
                ),
                (
                    "asset_turnover",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="총자산회전율",
                    ),
                ),
                (
                    "inventory_turnover",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="재고자산회전율",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "재무비율",
                "verbose_name_plural": "재무비율",
                "db_table": "financial_ratios",
                "ordering": ["-fiscal_year", "-fiscal_month"],
                "unique_together": {("fiscal_year", "fiscal_month")},
            },
        ),
        migrations.CreateModel(
            name="FinancialStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statement_type",
                    models.CharField(
                        choices=[
                            ("income", "손익계산서"),
                            ("balance", "재무상태표"),
                            ("cashflow", "현금흐름표"),
                        ],
                        max_length=20,
                        verbose_name="재무제표 유형",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="회계연도")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="회계월",
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="매출액",
                    ),
                ),
                (
                    "cost_of_sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="매출원가",
                    ),
                ),
                (
                    "gross_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="매출총이익",
                    ),
                ),
                (
                    "operating_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="판매관리비",
                    ),
                ),
                (
                    "operating_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="영업이익",
                    ),
                ),
                (
                    "net_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="당기순이익",
                    ),
                ),
                (
                    "total_assets",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="총자산",
                    ),
                ),
                (
                    "current_assets",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="유동자산",
                    ),
                ),
                (
                    "non_current_assets",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="비유동자산",
                    ),
                ),
                (
                    "total_liabilities",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="총부채",
                    ),
                ),
                (
                    "total_equity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="총자본",
                    ),
                ),
                (
                    "operating_cashflow",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="영업활동 현금흐름",
                    ),
                ),
                (
                    "investing_cashflow",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="투자활동 현금흐름",
                    ),
                ),
                (
                    "financing_cashflow",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="재무활동 현금흐름",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "재무제표",
                "verbose_name_plural": "재무제표",
                "db_table": "financial_statements",
                "ordering": ["-fiscal_year", "-fiscal_month"],
                "unique_together": {("statement_type", "fiscal_year", "fiscal_month")},
            },
        ),
    ]
