# Generated by Django 5.0.1 on 2026-02-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialstatement",
            name="beginning_equity",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="기초자본"
            ),
        ),
        migrations.AddField(
            model_name="financialstatement",
            name="dividend_paid",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="배당금 지급"
            ),
        ),
        migrations.AddField(
            model_name="financialstatement",
            name="ending_equity",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="기말자본"
            ),
        ),
        migrations.AddField(
            model_name="financialstatement",
            name="other_comprehensive_income",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="기타포괄손익"
            ),
        ),
        migrations.AddField(
            model_name="financialstatement",
            name="treasury_stock",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="자기주식"
            ),
        ),
        migrations.AlterField(
            model_name="financialstatement",
            name="statement_type",
            field=models.CharField(
                choices=[
                    ("income", "손익계산서"),
                    ("balance", "재무상태표"),
                    ("cashflow", "현금흐름표"),
                    ("equity", "자본변동표"),
                ],
                max_length=20,
                verbose_name="재무제표 유형",
            ),
        ),
        migrations.CreateModel(
            name="FactFinance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fiscal_month",
                    models.DateField(db_index=True, verbose_name="회계월"),
                ),
                (
                    "account_type",
                    models.CharField(max_length=20, verbose_name="계정구분"),
                ),
                (
                    "account_code",
                    models.CharField(max_length=50, verbose_name="계정코드"),
                ),
                (
                    "account_name",
                    models.CharField(max_length=200, verbose_name="계정명"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="금액"
                    ),
                ),
                (
                    "prev_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="전기금액",
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="매출액",
                    ),
                ),
                (
                    "cogs",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="매출원가",
                    ),
                ),
                (
                    "gross_profit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="매출총이익",
                    ),
                ),
                (
                    "operating_profit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="영업이익",
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="당기순이익",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="원천ID"
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(auto_now=True, verbose_name="동기화시각"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "재무",
                "verbose_name_plural": "재무",
                "db_table": "fact_finance",
                "ordering": ["-fiscal_month", "account_code"],
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["fiscal_month", "account_type"],
                        name="fact_financ_fiscal__8868c7_idx",
                    )
                ],
            },
        ),
    ]
