# Generated by Django 4.2.7 on 2026-03-30 07:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ControlTowerConfig",
            fields=[
                (
                    "config_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="설정 ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="명칭")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="코드"),
                ),
                (
                    "tower_type",
                    models.CharField(
                        choices=[
                            ("executive", "경영진"),
                            ("functional", "기능별"),
                            ("process", "프로세스"),
                        ],
                        max_length=30,
                        verbose_name="타워 유형",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("config", models.JSONField(default=dict, verbose_name="설정")),
                ("metrics", models.JSONField(default=list, verbose_name="메트릭")),
                (
                    "alert_config",
                    models.JSONField(default=dict, verbose_name="알림 설정"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "컨트롤 타워 설정",
                "verbose_name_plural": "컨트롤 타워 설정",
                "ordering": ["tower_type", "code"],
            },
        ),
        migrations.CreateModel(
            name="DashboardLayout",
            fields=[
                (
                    "layout_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="레이아웃 ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="명칭")),
                ("layout", models.JSONField(default=dict, verbose_name="레이아웃")),
                ("widgets", models.JSONField(default=list, verbose_name="위젯")),
                ("is_default", models.BooleanField(default=False, verbose_name="기본")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "tower_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layouts",
                        to="control_tower.controltowerconfig",
                        verbose_name="타워 설정",
                    ),
                ),
            ],
            options={
                "verbose_name": "대시보드 레이아웃",
                "verbose_name_plural": "대시보드 레이아웃",
                "ordering": ["tower_config", "-is_default", "name"],
            },
        ),
    ]
