# Generated by Django 4.2.7 on 2026-03-31 08:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChartTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="템플릿명")),
                (
                    "code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="템플릿 코드"
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(max_length=50, verbose_name="차트 유형"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="카테고리"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "config_schema",
                    models.JSONField(default=dict, verbose_name="설정 스키마"),
                ),
                (
                    "default_config",
                    models.JSONField(default=dict, verbose_name="기본 설정"),
                ),
                (
                    "preview_image",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="미리보기 이미지"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="공개 여부"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                (
                    "created_by",
                    models.CharField(blank=True, max_length=100, verbose_name="생성자"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "차트 템플릿",
                "verbose_name_plural": "차트 템플릿",
                "db_table": "chart_template",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="대시보드명")),
                (
                    "code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="대시보드 코드"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("layout", models.JSONField(default=dict, verbose_name="레이아웃")),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("default", "기본"),
                            ("dark", "다크"),
                            ("light", "라이트"),
                            ("colorful", "컬러풀"),
                        ],
                        default="default",
                        max_length=50,
                        verbose_name="테마",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="공개 여부"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                (
                    "refresh_interval",
                    models.IntegerField(default=300, verbose_name="새로고침 간격(초)"),
                ),
                (
                    "created_by",
                    models.CharField(blank=True, max_length=100, verbose_name="생성자"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "last_viewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 조회"
                    ),
                ),
            ],
            options={
                "verbose_name": "대시보드",
                "verbose_name_plural": "대시보드",
                "db_table": "dashboard",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataStream",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="스트림명")),
                (
                    "code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="스트림 코드"
                    ),
                ),
                ("topic", models.CharField(max_length=200, verbose_name="토픽")),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("kpi", "KPI"),
                            ("metric", "메트릭"),
                            ("log", "로그"),
                            ("event", "이벤트"),
                            ("alert", "알림"),
                        ],
                        max_length=50,
                        verbose_name="데이터 유형",
                    ),
                ),
                (
                    "source",
                    models.CharField(max_length=200, verbose_name="데이터 소스"),
                ),
                ("query", models.TextField(blank=True, verbose_name="쿼리")),
                (
                    "update_frequency",
                    models.IntegerField(default=1000, verbose_name="업데이트 주기(ms)"),
                ),
                (
                    "buffer_size",
                    models.IntegerField(default=100, verbose_name="버퍼 크기"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                (
                    "subscriber_count",
                    models.IntegerField(default=0, verbose_name="구독자 수"),
                ),
                (
                    "last_update_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 업데이트"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
            ],
            options={
                "verbose_name": "데이터 스트림",
                "verbose_name_plural": "데이터 스트림",
                "db_table": "data_stream",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VisualizationSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="사용자 ID"
                    ),
                ),
                (
                    "default_theme",
                    models.CharField(
                        default="default", max_length=50, verbose_name="기본 테마"
                    ),
                ),
                (
                    "chart_preferences",
                    models.JSONField(default=dict, verbose_name="차트 설정"),
                ),
                (
                    "color_palette",
                    models.JSONField(default=list, verbose_name="색상 팔레트"),
                ),
                (
                    "language",
                    models.CharField(default="ko", max_length=10, verbose_name="언어"),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Seoul", max_length=50, verbose_name="시간대"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "시각화 설정",
                "verbose_name_plural": "시각화 설정",
                "db_table": "visualization_settings",
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("line", "선 그래프"),
                            ("bar", "막대 그래프"),
                            ("pie", "원 그래프"),
                            ("area", "영역 그래프"),
                            ("scatter", "산점도"),
                            ("heatmap", "히트맵"),
                            ("treemap", "트리맵"),
                            ("gauge", "게이지"),
                            ("table", "테이블"),
                            ("kpi", "KPI 카드"),
                            ("funnel", "깔때기 차트"),
                            ("sankey", "산키 다이어그램"),
                            ("radar", "레이더 차트"),
                        ],
                        max_length=50,
                        verbose_name="위젯 유형",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="위젯 제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("position", models.JSONField(default=dict, verbose_name="위치 정보")),
                ("size", models.JSONField(default=dict, verbose_name="크기 정보")),
                (
                    "data_config",
                    models.JSONField(default=dict, verbose_name="데이터 설정"),
                ),
                (
                    "chart_config",
                    models.JSONField(default=dict, verbose_name="차트 설정"),
                ),
                (
                    "refresh_interval",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="새로고침 간격(초)"
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="데이터 소스"
                    ),
                ),
                ("query", models.TextField(blank=True, verbose_name="쿼리")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="순서")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="visualization.dashboard",
                        verbose_name="대시보드",
                    ),
                ),
            ],
            options={
                "verbose_name": "대시보드 위젯",
                "verbose_name_plural": "대시보드 위젯",
                "db_table": "dashboard_widget",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
